/**
 * Books, music and film — how the thing was made, not who made it.
 *
 * "Who wrote X" is a quiz. These ask why a piece is the shape it is: what a constraint did to
 * a work, what a title is hiding, what an artist was solving. A table that has never read the
 * book can still reason its way to most of them.
 */
import type { Question } from '../types'

export const ARTS: readonly Question[] = [
  {
    id: 'a001',
    theme: 'arts',
    q: 'Why are so many nineteenth-century novels enormously long and full of cliffhangers?',
    a: 'They were serialised and paid by instalment',
    note: 'Dickens wrote to a monthly deadline for a monthly audience. The form dictated the length and the pacing.',
  },
  {
    id: 'a002',
    theme: 'arts',
    q: 'Why does an orchestra tune to the oboe rather than to any other instrument?',
    a: 'Its pitch is stable and its tone cuts through',
    note: 'It is also hardest to adjust quickly, so it is easier for everybody else to come to it.',
  },
  {
    id: 'a003',
    theme: 'arts',
    q: 'What practical problem does a film’s "shot–reverse shot" solve, and why is it so invisible?',
    a: 'It shows a conversation from both sides — the audience has been trained to ignore the cut',
    note: 'Continuity editing works by never being noticed. Notice it once and it is hard to unsee.',
  },
  {
    id: 'a004',
    theme: 'arts',
    q: 'Why did Renaissance painters put so many mirrors, convex glass and reflective armour in their paintings?',
    a: 'To demonstrate technical skill',
    note: 'A reflection is the hardest thing to paint convincingly. It was showing off, and everyone knew it.',
  },
  {
    id: 'a005',
    theme: 'arts',
    q: 'What is a "MacGuffin", and who named it?',
    a: 'A plot device everyone wants that does not matter in itself — Hitchcock',
    note: 'The briefcase, the microfilm, the falcon. Its only job is to make people move.',
  },
  {
    id: 'a006',
    theme: 'arts',
    q: 'Why do so many pop songs change key near the end?',
    a: 'To renew interest after repetition',
    note: 'The "truck driver’s gear change". Loved by audiences, despised by musicians.',
  },
  {
    id: 'a007',
    theme: 'arts',
    q: 'Why are early photographs of people so rarely smiling, and what are the two explanations?',
    a: 'Long exposures, and the convention that a portrait was a serious record',
    note: 'People could hold a neutral face; a smile held for thirty seconds becomes a grimace.',
  },
  {
    id: 'a008',
    theme: 'arts',
    q: 'What is the reason a piano has 88 keys rather than more?',
    a: 'Beyond that the notes stop being musically useful — they blur',
    note: 'Bösendorfer built extra bass keys anyway, mostly for sympathetic resonance rather than playing.',
  },
  {
    id: 'a009',
    theme: 'arts',
    q: 'Why did silent films use such exaggerated acting?',
    a: 'The story had to be legible without dialogue',
    note: 'Many silent actors were subtle. The exaggeration is remembered because it survived in parody.',
  },
  {
    id: 'a010',
    theme: 'arts',
    q: 'What did the introduction of the paint tube do to painting?',
    a: 'It let painters work outdoors — which made Impressionism possible',
    note: 'Renoir said without the tube there would have been no Impressionism. Technology first, movement second.',
  },
  {
    id: 'a011',
    theme: 'arts',
    q: 'Why is a symphony orchestra arranged with strings at the front and percussion at the back?',
    a: 'Volume — quiet instruments need to be closer',
    note: 'A single trumpet can drown thirty violins. The seating plan is a mixing desk made of chairs.',
  },
  {
    id: 'a012',
    theme: 'arts',
    q: 'What constraint produced the shape of a sonnet, and what does the "turn" do?',
    a: 'Fourteen lines with a fixed rhyme scheme; the turn reverses or complicates the argument',
    note: 'A sonnet is a small machine for changing your mind in public.',
  },
  {
    id: 'a013',
    theme: 'arts',
    q: 'Why do so many classic album covers have no text on them?',
    a: 'Confidence, and record shops filed by spine anyway',
    note: 'Led Zeppelin IV famously has no title at all. Their label objected and lost.',
  },
  {
    id: 'a014',
    theme: 'arts',
    q: 'What is "chiaroscuro", and what problem was it solving?',
    a: 'Strong light and shade — making flat paint look three-dimensional',
    note: 'Caravaggio pushed it until the background disappeared entirely, which was also cheaper to paint.',
  },
  {
    id: 'a015',
    theme: 'arts',
    q: 'Why are so many operas in Italian even when written by composers who did not speak it?',
    a: 'It was the professional language of opera, and the vowels suit singing',
    note: 'Open vowels and few consonant clusters. Mozart wrote in Italian and German and knew the difference.',
  },
  {
    id: 'a016',
    theme: 'arts',
    q: 'What is the practical reason theatre curtains are traditionally red?',
    a: 'Red keeps looking rich under warm stage lighting and hides wear',
    note: 'It also reads as dark on the eye at low light, so the audience settles.',
  },
  {
    id: 'a017',
    theme: 'arts',
    q: 'Why did Shakespeare write so many parts for boys playing women, and how did playwrights use it?',
    a: 'Women could not act — plays used disguise plots to make it a joke',
    note: 'A boy playing a woman pretending to be a boy. The audience knew, and that was the point.',
  },
  {
    id: 'a018',
    theme: 'arts',
    q: 'What does a film composer mean by "Mickey Mousing", and why is it now avoided?',
    a: 'Music matching action exactly — it reads as comic',
    note: 'From cartoon scoring. In drama it makes the audience aware of the score, which kills it.',
  },
  {
    id: 'a019',
    theme: 'arts',
    q: 'Why do most feature films run between 90 and 120 minutes?',
    a: 'Cinema scheduling and audience attention, not artistic law',
    note: 'More screenings per day means more revenue. The art form is shaped by the timetable.',
  },
  {
    id: 'a020',
    theme: 'arts',
    q: 'What is the "rule of thirds", and what is the honest argument against teaching it?',
    a: 'Placing subjects on third-lines — critics say it substitutes a formula for looking',
    note: 'Useful scaffolding, terrible ceiling. Most great compositions break it deliberately.',
  },
  {
    id: 'a021',
    theme: 'arts',
    q: 'Why did the invention of photography change painting so profoundly?',
    a: 'Painting no longer had to record likeness, so it went after everything else',
    note: 'Impressionism, abstraction, expressionism. A job was taken away and the trade reinvented itself.',
  },
  {
    id: 'a022',
    theme: 'arts',
    q: 'What is the reason vinyl records have a wider groove at the start of a loud passage?',
    a: 'Louder means bigger excursion — the cutter needs room',
    note: 'Which is why long, loud sides sound worse: less space per revolution.',
  },
  {
    id: 'a023',
    theme: 'arts',
    q: 'Why is the last movement of a classical symphony usually the fastest?',
    a: 'To send the audience out — the form ends on energy',
    note: 'Except when a composer deliberately breaks it, which is why Tchaikovsky’s Sixth is so unsettling.',
  },
  {
    id: 'a024',
    theme: 'arts',
    q: 'What does "in medias res" mean, and why do so many epics start that way?',
    a: 'In the middle of things — it starts on action and fills in later',
    note: 'The Iliad opens nine years into a ten-year war. Beginning at the beginning is a modern habit.',
  },
  {
    id: 'a025',
    theme: 'arts',
    q: 'Why do museums light oil paintings much more brightly than works on paper?',
    a: 'Paper and its pigments fade irreversibly',
    note: 'Watercolours are often shown in rotation and rested in the dark for years between exhibitions.',
  },
  {
    id: 'a026',
    theme: 'arts',
    q: 'What did the Hays Code do to American cinema, and what technique did it accidentally invent?',
    a: 'Censored content — and produced an entire language of implication',
    note: 'Cutting away, the closing door, the train entering a tunnel. Restriction as a style engine.',
  },
  {
    id: 'a027',
    theme: 'arts',
    q: 'Why are so many pop songs about three and a half minutes long?',
    a: 'The physical limit of a 78rpm single, long after the format died',
    note: 'A convention with no remaining technical basis, kept by radio and then by habit.',
  },
  {
    id: 'a028',
    theme: 'arts',
    q: 'What is a "found object" in art, and what did Duchamp actually claim about it?',
    a: 'An ordinary object presented as art — that the choosing was the artistic act',
    note: 'The urinal was submitted under a pseudonym and rejected by a jury he sat on.',
  },
  {
    id: 'a029',
    theme: 'arts',
    q: 'Why do orchestras still use a conductor when everyone can read the score?',
    a: 'To unify interpretation and timing in a large group',
    note: 'Small ensembles do without. Past about twenty players the physics of sound delay makes it necessary.',
  },
  {
    id: 'a030',
    theme: 'arts',
    q: 'What is the reason Greek statues are white, and what does it get wrong about them?',
    a: 'The paint has weathered off — they were brightly coloured',
    note: 'Traces survive under ultraviolet. Neoclassical taste for white marble is an accident of decay.',
  },
  {
    id: 'a031',
    theme: 'arts',
    q: 'Why does a novel written in the first person have a structural problem a third-person one does not?',
    a: 'The narrator must survive to tell it, and can only know what they know',
    note: 'Which authors solve with letters, diaries, unreliable narrators, or by cheating.',
  },
  {
    id: 'a032',
    theme: 'arts',
    q: 'What is "the fourth wall", and where does the name come from?',
    a: 'The imaginary wall between stage and audience — from a box set with three real walls',
    note: 'Diderot described it before anyone named it. Breaking it is much older than the term.',
  },
  {
    id: 'a033',
    theme: 'arts',
    q: 'Why is blue such a late arrival in painting compared to red and yellow?',
    a: 'Blue pigment was rare and extremely expensive',
    note: 'Ultramarine came from lapis lazuli, mined in Afghanistan. Contracts specified how much a painter could use.',
  },
  {
    id: 'a034',
    theme: 'arts',
    q: 'What does a "leitmotif" do, and which composer is most associated with it?',
    a: 'A musical theme tied to a character or idea — Wagner',
    note: 'Film scoring runs on it. Star Wars is a Wagnerian system with lightsabers.',
  },
  {
    id: 'a035',
    theme: 'arts',
    q: 'Why do so many great novels have terrible first drafts, according to writers themselves?',
    a: 'The draft is for discovering the book, not for writing it',
    note: 'Almost every writer who has said anything useful about it says the same thing in different words.',
  },
  {
    id: 'a036',
    theme: 'arts',
    q: 'What did the invention of the close-up do to acting?',
    a: 'It made small expression legible, so performances got quieter',
    note: 'Theatre projects to the back row; film projects to a lens two feet away.',
  },
  {
    id: 'a037',
    theme: 'arts',
    q: 'Why is a haiku traditionally about a season, and what is the technical term?',
    a: 'A seasonal reference — the kigo',
    note: 'The syllable count is the part that travels. The seasonal word is the part that matters.',
  },
  {
    id: 'a038',
    theme: 'arts',
    q: 'What is the reason theatres call it "break a leg" instead of wishing good luck?',
    a: 'Superstition that direct good wishes are unlucky',
    note: 'Explanations involving actual legs and curtain lines are all later inventions.',
  },
  {
    id: 'a039',
    theme: 'arts',
    q: 'Why do animation studios traditionally test a character by having them carry a heavy object?',
    a: 'Weight is the hardest thing to animate convincingly',
    note: 'If the weight reads, everything else will. It is the animator’s equivalent of drawing hands.',
  },
  {
    id: 'a040',
    theme: 'arts',
    q: 'What is the "uncanny valley", and why does it matter to animation?',
    a: 'Near-human images become unsettling — so stylised characters often work better',
    note: 'Which is why Pixar humans are caricatured and the realistic ones age so badly.',
  },
  {
    id: 'a041',
    theme: 'arts',
    q: 'Why did jazz standards become standards, and what makes a tune suitable?',
    a: 'A strong chord progression that supports improvisation',
    note: 'The melody is almost incidental. Musicians learn the changes and discard the tune.',
  },
  {
    id: 'a042',
    theme: 'arts',
    q: 'What is a "palimpsest", and why is one occasionally more valuable than what is written on it?',
    a: 'A reused manuscript — the erased text underneath may be unique',
    note: 'The Archimedes Palimpsest had a prayer book written over lost mathematics.',
  },
  {
    id: 'a043',
    theme: 'arts',
    q: 'Why do film credits list the director last among the opening credits but the cast first?',
    a: 'Contractual convention — the final position is the position of authorship',
    note: 'Credit order is negotiated to a level of detail that would astonish an audience.',
  },
  {
    id: 'a044',
    theme: 'arts',
    q: 'What is the practical reason so much medieval music has no dynamics or tempo marks?',
    a: 'It was written for performers who already knew how it went',
    note: 'Notation records what cannot be assumed. What is missing tells you what was common knowledge.',
  },
  {
    id: 'a045',
    theme: 'arts',
    q: 'Why did Impressionist painters use so few blacks?',
    a: 'They painted shadows as colour, not as absence of light',
    note: 'Look at a shadow on snow. It is blue, and once you have seen it you cannot paint it grey.',
  },
  {
    id: 'a046',
    theme: 'arts',
    q: 'What does a "bildungsroman" follow, and give an example.',
    a: 'A character’s formation from youth to maturity — Great Expectations, Jane Eyre',
    note: 'The German word stuck because English has no compact equivalent.',
  },
  {
    id: 'a047',
    theme: 'arts',
    q: 'Why are cathedral acoustics so unsuitable for speech, and what music did they produce instead?',
    a: 'Long reverberation blurs consonants — so plainchant and slow polyphony',
    note: 'The building wrote the music. Change the room and the style changes with it.',
  },
  {
    id: 'a048',
    theme: 'arts',
    q: 'What is "Chekhov’s gun", and what is the corresponding failure it warns against?',
    a: 'Anything shown must be used — otherwise it is a promise broken',
    note: 'Audiences track objects. Introducing one and dropping it is a debt you have not paid.',
  },
  {
    id: 'a049',
    theme: 'arts',
    q: 'Why do so many musicals put the big number about two-thirds of the way through?',
    a: 'It is the emotional low point turned outward — the "eleven o’clock number"',
    note: 'Named for when it fell in a show that started at half past eight.',
  },
  {
    id: 'a050',
    theme: 'arts',
    q: 'What is the reason painters use an underpainting in a single colour before the real colours?',
    a: 'To establish values without worrying about hue',
    note: 'Get the light right in grey and the colour is much easier. Grisaille is the training version of this.',
  },
  {
    id: 'a051',
    theme: 'arts',
    q: 'Why did the Beatles stop touring, and what did it do to their records?',
    a: 'They could not be heard live — so they made records that could not be played live',
    note: 'Sgt. Pepper is what happens when a band gives up on reproducing itself on stage.',
  },
  {
    id: 'a052',
    theme: 'arts',
    q: 'What does an editor mean by "kill your darlings"?',
    a: 'Cut the lines you are proudest of if they do not serve the work',
    note: 'Usually attributed to Faulkner; actually Arthur Quiller-Couch, who put it more brutally.',
  },
  {
    id: 'a053',
    theme: 'arts',
    q: 'Why is a violin’s shape essentially unchanged since the seventeenth century?',
    a: 'It was optimised early and any change makes it sound different rather than better',
    note: 'Attempts to improve it exist. Nobody plays them.',
  },
  {
    id: 'a054',
    theme: 'arts',
    q: 'What is "negative space" in composition, and why do beginners struggle with it?',
    a: 'The shape of the emptiness — beginners draw objects, not gaps',
    note: 'Drawing the space between chair legs is the standard exercise for exactly this reason.',
  },
  {
    id: 'a055',
    theme: 'arts',
    q: 'Why are opera surtitles a relatively recent invention, and what did they change?',
    a: 'They arrived in the 1980s — audiences finally knew what was being sung',
    note: 'Fiercely resisted as vulgar. Now nearly universal, and attendance went up.',
  },
  {
    id: 'a056',
    theme: 'arts',
    q: 'What is a "roman à clef", and why would an author write one?',
    a: 'A novel about real people under invented names — deniability',
    note: 'The key is the reader working out who is who. Libel law is usually the reason.',
  },
  {
    id: 'a057',
    theme: 'arts',
    q: 'Why do photographers talk about "the golden hour", and what is physically happening?',
    a: 'Low sun means longer atmospheric path — warm, soft, directional light',
    note: 'The same scattering that makes sunsets red makes faces flattering.',
  },
  {
    id: 'a058',
    theme: 'arts',
    q: 'What did the arrival of the LP do to popular music that the single could not?',
    a: 'Made the album a form in itself',
    note: 'Forty minutes of continuous authored sequence. An entirely new artistic unit, invented by packaging.',
  },
  {
    id: 'a059',
    theme: 'arts',
    q: 'Why do so many horror films take place in the dark, beyond the obvious?',
    a: 'The audience fills in what it cannot see — imagination beats any effect',
    note: 'Also very much cheaper. The two reasons have always pushed the same way.',
  },
  {
    id: 'a060',
    theme: 'arts',
    q: 'What is "sfumato", and which painting is the most cited example?',
    a: 'Smoky, edgeless transitions — the Mona Lisa',
    note: 'Especially at the corners of the mouth, which is why the expression seems to change.',
  },
  {
    id: 'a061',
    theme: 'arts',
    q: 'Why do orchestras place the first and second violins as they do, and what did older seating do differently?',
    a: 'Modern puts them together on the left; older split them left and right',
    note: 'Composers wrote antiphonal passages that only work split. Modern seating loses the effect entirely.',
  },
  {
    id: 'a062',
    theme: 'arts',
    q: 'What is the reason so many pop producers use a "drop" and what does it exploit?',
    a: 'Removing everything then returning — contrast makes the return feel louder',
    note: 'Nothing gets louder. Expectation and silence do the work.',
  },
  {
    id: 'a063',
    theme: 'arts',
    q: 'Why are books traditionally printed in signatures of 16 or 32 pages?',
    a: 'A sheet folded repeatedly gives those counts',
    note: 'It is why page counts cluster on multiples of 16, and why blank pages appear at the end.',
  },
  {
    id: 'a064',
    theme: 'arts',
    q: 'What is a "false ending" in music, and why does it work more than once?',
    a: 'A convincing close that resumes — listeners forgive it because the return is a reward',
    note: 'Beethoven does it repeatedly in the Fifth, to the point where it stops being a trick and becomes a joke.',
  },
  {
    id: 'a065',
    theme: 'arts',
    q: 'Why did so many twentieth-century architects put buildings on stilts?',
    a: 'To free the ground for movement and light',
    note: 'Le Corbusier’s pilotis. In practice it produced a great many windy, unused spaces.',
  },
  {
    id: 'a066',
    theme: 'arts',
    q: 'What is the practical purpose of a "read-through" before a production, beyond hearing the script?',
    a: 'Timing, and finding what does not work when spoken',
    note: 'Writers hear their own bad lines the moment somebody else says them. Nothing else does that.',
  },
  {
    id: 'a067',
    theme: 'arts',
    q: 'Why do museums increasingly display the frames as well as the paintings?',
    a: 'The frame is part of the work and its history',
    note: 'Many were changed to suit later fashions. Restoring an original frame changes how a picture reads.',
  },
  {
    id: 'a068',
    theme: 'arts',
    q: 'What single technical change made the modern piano possible, and what did it allow?',
    a: 'A cast iron frame — much higher string tension, therefore volume',
    note: 'A fortepiano cannot fill a concert hall. The instrument grew to fit the audience.',
  },
  {
    id: 'a069',
    theme: 'arts',
    q: 'Why is the "Voyager Golden Record" a strange artistic object as well as a scientific one?',
    a: 'It is a curated anthology for an audience that may not exist',
    note: 'Greetings in 55 languages, whale song, and Chuck Berry. Sagan chaired the committee.',
  },
  {
    id: 'a070',
    theme: 'arts',
    q: 'What does "avant-garde" literally mean, and what does the metaphor imply about art?',
    a: 'The advance guard — that art scouts ahead of society',
    note: 'A military term borrowed by nineteenth-century radicals. It assumes a direction of travel.',
  },
  {
    id: 'a071',
    theme: 'arts',
    q: 'Why did Michelangelo object to being asked to paint the Sistine ceiling?',
    a: 'He considered himself a sculptor',
    note: 'He signed letters "Michelangelo, sculptor" throughout the four years he spent painting it.',
  },
  {
    id: 'a072',
    theme: 'arts',
    q: 'What is "method acting", and what is the most common criticism of it?',
    a: 'Drawing on real emotion and staying in character — critics say it burdens everyone else',
    note: 'Olivier’s alleged reply: "Have you tried acting, dear boy?" Probably apocryphal, endlessly repeated.',
  },
  {
    id: 'a073',
    theme: 'arts',
    q: 'Why is so much street art deliberately temporary?',
    a: 'Permanence requires permission, which changes what can be said',
    note: 'Impermanence is not a limitation of the form; for many artists it is the form.',
  },
  {
    id: 'a074',
    theme: 'arts',
    q: 'What did the Dogme 95 manifesto forbid, and what was it reacting against?',
    a: 'Props, artificial light, non-diegetic music, credited directors — against spectacle',
    note: 'A vow of chastity for filmmakers. Several signatories broke it in their own films.',
  },
  {
    id: 'a075',
    theme: 'arts',
    q: 'Why does a well-designed book have wider outer margins than inner ones?',
    a: 'Two inner margins meet at the spine and read as one space',
    note: 'And your thumbs go in the outer ones. Typography is mostly about hands and eyes.',
  },
  {
    id: 'a076',
    theme: 'arts',
    q: 'What is "musique concrète", and what made it possible?',
    a: 'Music composed from recorded sound — the tape recorder',
    note: 'Schaeffer, 1948. Sampling is the same idea with better tools and worse manners.',
  },
  {
    id: 'a077',
    theme: 'arts',
    q: 'Why do so many classic film noir scenes have venetian blind shadows?',
    a: 'Cheap, atmospheric, and it hides a small set',
    note: 'Style born of budget. The look outlived every reason it was invented for.',
  },
  {
    id: 'a078',
    theme: 'arts',
    q: 'What is the "Bechdel test", and what is it actually measuring?',
    a: 'Two named women talking about something other than a man — the aggregate, not the individual film',
    note: 'Alison Bechdel credits a friend. A good film can fail it; the point is how many do.',
  },
  {
    id: 'a079',
    theme: 'arts',
    q: 'Why do sculptors work in clay before bronze, and what happens to the clay?',
    a: 'It is a model for casting — usually destroyed in the process',
    note: 'Lost-wax casting. The original is consumed to make the copy, which is a strange thing to accept.',
  },
  {
    id: 'a080',
    theme: 'arts',
    q: 'What is a "ghost note" in music, and why would you write one?',
    a: 'A note felt rather than heard — it carries rhythm without pitch',
    note: 'Funk drumming is largely made of them. Remove them and the groove disappears.',
  },
  {
    id: 'a081',
    theme: 'arts',
    q: 'Why are most film sets built with removable walls?',
    a: 'To get the camera where a real room would not allow',
    note: 'Called wild walls. Real locations are much harder to light and shoot in, which is why sets survive.',
  },
  {
    id: 'a082',
    theme: 'arts',
    q: 'What does it mean that Shakespeare’s plays were not published in a reliable collected form in his lifetime?',
    a: 'Much of what we have depends on colleagues’ memories and printers’ copies',
    note: 'The First Folio, seven years after his death. Without it eighteen plays would be lost.',
  },
  {
    id: 'a083',
    theme: 'arts',
    q: 'Why did the Impressionists exhibit independently rather than in the official Salon?',
    a: 'They were repeatedly rejected',
    note: 'The Salon des Refusés was set up because the rejections had become a scandal in themselves.',
  },
  {
    id: 'a084',
    theme: 'arts',
    q: 'What is "diegetic" sound, and give an example of a film playing with the boundary.',
    a: 'Sound from within the story world — many films reveal the score to be a radio',
    note: 'Blazing Saddles rides into the Count Basie Orchestra sitting in the desert.',
  },
  {
    id: 'a085',
    theme: 'arts',
    q: 'Why do many novelists write the ending before the middle?',
    a: 'The middle is easier when you know what it has to reach',
    note: 'The middle is where most abandoned novels die, and knowing the destination is the usual cure.',
  },
  {
    id: 'a086',
    theme: 'arts',
    q: 'What is the reason large public sculptures are often bronze rather than marble?',
    a: 'It survives weather and pollution far better',
    note: 'Marble outdoors dissolves slowly in acidic rain. Many famous originals are now indoors with copies outside.',
  },
  {
    id: 'a087',
    theme: 'arts',
    q: 'Why does a photograph of a fast-moving propeller sometimes look bent?',
    a: 'A rolling shutter reads the sensor line by line',
    note: 'The bottom of the frame is recorded milliseconds after the top. The camera photographs time as well as space.',
  },
  {
    id: 'a088',
    theme: 'arts',
    q: 'What is a "cadenza", and what was originally expected of the soloist?',
    a: 'An unaccompanied passage — originally improvised',
    note: 'Composers began writing them out when they stopped trusting performers to improvise well.',
  },
  {
    id: 'a089',
    theme: 'arts',
    q: 'Why are so many statues of people on horseback, and what did the pose supposedly encode?',
    a: 'Equestrian statues signal command — legend says hoof position encoded how the rider died',
    note: 'The hoof code is a myth. Enough people believe it that guides still repeat it.',
  },
  {
    id: 'a090',
    theme: 'arts',
    q: 'What did the arrival of streaming do to television structure?',
    a: 'Removed the act breaks written for advertising',
    note: 'Episodes stopped needing cliffhangers every twelve minutes, and their lengths stopped being uniform.',
  },
  {
    id: 'a091',
    theme: 'arts',
    q: 'Why is a fugue difficult to write, in one sentence?',
    a: 'Every voice must be independently good and simultaneously correct against all the others',
    note: 'Bach wrote them as though it were easy, which has irritated composers for three hundred years.',
  },
  {
    id: 'a092',
    theme: 'arts',
    q: 'What is "trompe-l’œil", and where is it most often found?',
    a: 'Painting that fools the eye into seeing three dimensions — ceilings and walls',
    note: 'Baroque churches open into painted skies. The technique is older than perspective theory.',
  },
  {
    id: 'a093',
    theme: 'arts',
    q: 'Why do museums put a rope or a line on the floor rather than glass in front of most paintings?',
    a: 'Glass reflects and changes the surface',
    note: 'Distance is cheaper, reversible, and lets you see the brushwork. Glass is for the very valuable.',
  },
  {
    id: 'a094',
    theme: 'arts',
    q: 'What is the reason so many folk songs exist in dozens of versions with different words?',
    a: 'They were transmitted orally and adapted locally',
    note: 'The Child ballads catalogue variants across centuries. There is no original to be faithful to.',
  },
  {
    id: 'a095',
    theme: 'arts',
    q: 'Why did architects abandon load-bearing walls in tall buildings, and what replaced them?',
    a: 'A steel or concrete frame — the wall became a skin',
    note: 'Which is why a skyscraper can be all glass. The windows are not holes in anything.',
  },
  {
    id: 'a096',
    theme: 'arts',
    q: 'What does "sotto voce" instruct a performer to do, and what is its equivalent in prose?',
    a: 'Under the breath — an aside or a parenthesis',
    note: 'Both are ways of saying something while pretending not to.',
  },
  {
    id: 'a097',
    theme: 'arts',
    q: 'Why is it significant that so much ancient Greek drama survives only in fragments quoted by others?',
    a: 'Our sense of the period is filtered through what later writers found worth quoting',
    note: 'We have seven plays of Sophocles out of about 120. The canon is a survival accident.',
  },
  {
    id: 'a098',
    theme: 'arts',
    q: 'What is the practical reason film is shot out of sequence?',
    a: 'Cost — everything on one set or location is shot together',
    note: 'Actors must know exactly where their character is emotionally on any given morning.',
  },
  {
    id: 'a099',
    theme: 'arts',
    q: 'Why do some paintings have a "pentimento", and what does it show?',
    a: 'The artist changed their mind — the earlier version shows through as the paint thins',
    note: 'Literally "repentance". X-rays now find them routinely, and they are the closest thing to a painter’s draft.',
  },
  {
    id: 'a100',
    theme: 'arts',
    q: 'What is the argument that a cover version can be better than the original, and name the usual example?',
    a: 'A song is a structure, not a recording — "Hurt", "Respect", "All Along the Watchtower"',
    note: 'Dylan said he considered Hendrix’s version the definitive one and played it that way afterwards.',
  },
]
