/**
 * Everyday things — the objects in the room, and why they are that shape.
 *
 * The best theme for a table with no specialists, because everybody has already handled the
 * evidence. Every question here is about something within arm's reach, and the answer is
 * almost always a constraint somebody was solving.
 */
import type { Question } from '../types'

export const EVERYDAY: readonly Question[] = [
  {
    id: 'e001',
    theme: 'everyday',
    q: 'Why do most manhole covers have a round lid rather than a square one?',
    a: 'A round lid cannot fall through its own hole',
    note: 'A square one dropped diagonally goes straight down onto whoever is below.',
  },
  {
    id: 'e002',
    theme: 'everyday',
    q: 'Why is there a small hole in the barrel of a ballpoint pen?',
    a: 'To equalise pressure so the ink flows',
    note: 'Also so a swallowed cap does not block the airway, which is a separate and later design rule for caps.',
  },
  {
    id: 'e003',
    theme: 'everyday',
    q: 'What is the tiny fifth pocket in a pair of jeans for?',
    a: 'A pocket watch',
    note: 'It has outlived the watch by a century and nobody has thought to remove it.',
  },
  {
    id: 'e004',
    theme: 'everyday',
    q: 'Why does a bath towel dry you better than a smooth cloth of the same size?',
    a: 'Loops give an enormous increase in surface area',
    note: 'Terry cloth is essentially a fabric made mostly of edges.',
  },
  {
    id: 'e005',
    theme: 'everyday',
    q: 'Why are aeroplane windows round rather than square?',
    a: 'Corners concentrate stress and crack',
    note: 'Two Comet airliners broke up in 1954 before anybody understood why. Every window since has been rounded.',
  },
  {
    id: 'e006',
    theme: 'everyday',
    q: 'What is the purpose of the tiny bumps on the F and J keys of a keyboard?',
    a: 'To find the home row without looking',
    note: 'Index fingers. The whole touch-typing system is anchored on two pieces of moulded plastic.',
  },
  {
    id: 'e007',
    theme: 'everyday',
    q: 'Why do lift buttons in many buildings have a raised dot beside a particular number?',
    a: 'Braille, and often a marker for the ground floor',
    note: 'The ground floor button is frequently a different shape too, so it can be found by touch in a crowd.',
  },
  {
    id: 'e008',
    theme: 'everyday',
    q: 'Why does a wine bottle have a punt — the dent in the bottom?',
    a: 'Historically strength and stability from glassblowing; now mostly convention',
    note: 'It also collects sediment and gives a place for a thumb when pouring. The strength argument is the real origin.',
  },
  {
    id: 'e009',
    theme: 'everyday',
    q: 'Why are tennis balls fuzzy?',
    a: 'The nap controls aerodynamics and slows the ball',
    note: 'A smooth ball of the same weight would be almost unplayable at professional pace.',
  },
  {
    id: 'e010',
    theme: 'everyday',
    q: 'Why do pill bottles have cotton wool in them, and why is it now pointless?',
    a: 'To stop tablets breaking in transit — modern packing makes it unnecessary',
    note: 'It actually draws in moisture once opened, so it is worse than nothing. Most makers have stopped.',
  },
  {
    id: 'e011',
    theme: 'everyday',
    q: 'Why does a key have a specific pattern of notches, and what is the mechanism it is operating?',
    a: 'It lifts pins to a shear line so the cylinder can turn',
    note: 'Each notch sets one pin to exactly the right height. The whole lock is a row of tiny measurements.',
  },
  {
    id: 'e012',
    theme: 'everyday',
    q: 'Why are the tops of screws sometimes cross-shaped rather than a single slot?',
    a: 'The driver self-centres, and it can be turned by machine',
    note: 'Phillips heads were designed to cam out under torque, so an assembly line could not overtighten.',
  },
  {
    id: 'e013',
    theme: 'everyday',
    q: 'What is the reason toothpaste tubes have a coloured square at the crimped end?',
    a: 'A registration mark for the packing machine',
    note: 'Not a code for the ingredients, which is one of the most durable myths on the internet.',
  },
  {
    id: 'e014',
    theme: 'everyday',
    q: 'Why do office chairs have five castors rather than four?',
    a: 'Five gives stability without a corner to tip over',
    note: 'Four legs means four directions where the base is narrow. Five spreads the risk evenly.',
  },
  {
    id: 'e015',
    theme: 'everyday',
    q: 'Why is there a coin slot on some supermarket trolleys?',
    a: 'To make people return them',
    note: 'A refundable deposit is far cheaper than paying somebody to collect trolleys from a car park.',
  },
  {
    id: 'e016',
    theme: 'everyday',
    q: 'Why do fire engines in some countries have their name written backwards on the front?',
    a: 'To be read in a rear-view mirror',
    note: 'A design that assumes its reader is looking the wrong way, which is a rare thing to plan for.',
  },
  {
    id: 'e017',
    theme: 'everyday',
    q: 'Why do bricks have holes through them?',
    a: 'Less material, lighter, better keying for mortar and more even firing',
    note: 'The mortar squeezes through and locks the courses together. Four benefits from removing material.',
  },
  {
    id: 'e018',
    theme: 'everyday',
    q: 'Why does a paper coffee cup have a rolled rim?',
    a: 'Rigidity, and a lid needs something to grip',
    note: 'The roll turns a floppy edge into a structural ring. Same principle as a hem on cloth.',
  },
  {
    id: 'e019',
    theme: 'everyday',
    q: 'Why do power cables sag between pylons rather than being pulled tight?',
    a: 'Slack absorbs thermal expansion and contraction',
    note: 'A tight cable in summer becomes a snapped cable in winter. The sag is calculated, not sloppy.',
  },
  {
    id: 'e020',
    theme: 'everyday',
    q: 'Why is the standard shape of a milk bottle crate designed to stack when full and nest when empty?',
    a: 'Empty crates are shipped back, and stacking wastes space',
    note: 'Rotate ninety degrees and the same crate does both. It is one of the neatest bits of industrial design there is.',
  },
  {
    id: 'e021',
    theme: 'everyday',
    q: 'What is the purpose of the small loop on the back of a dress shirt?',
    a: 'To hang it up, originally on a ship or in a locker room',
    note: 'Ivy League students later used its presence and removal to signal relationship status.',
  },
  {
    id: 'e022',
    theme: 'everyday',
    q: 'Why do railway tracks have gaps between the rails, and why do modern ones often not?',
    a: 'Thermal expansion — continuous welded rail is pre-stressed instead',
    note: 'Which is why modern track buckles spectacularly in a heatwave when it is laid wrong.',
  },
  {
    id: 'e023',
    theme: 'everyday',
    q: 'Why is a standard sheet of A4 paper that particular size?',
    a: 'Halving it gives the same proportions — the ratio is one to root two',
    note: 'A0 is one square metre. Every other size is that halved repeatedly, which makes scaling trivial.',
  },
  {
    id: 'e024',
    theme: 'everyday',
    q: 'Why do bicycle pedals have a left-hand thread on one side?',
    a: 'So pedalling tightens rather than loosens them',
    note: 'Precession, not the obvious force direction. It was worked out by trial and injury.',
  },
  {
    id: 'e025',
    theme: 'everyday',
    q: 'Why do escalator steps have grooves along them?',
    a: 'They mesh with the comb plate at the ends to sweep off anything caught',
    note: 'And they warn you where the edge is. The grooves are a safety device disguised as texture.',
  },
  {
    id: 'e026',
    theme: 'everyday',
    q: 'Why is there usually a small arrow next to the fuel gauge icon in a car?',
    a: 'It shows which side the filler cap is on',
    note: 'Introduced widely in the 1980s. Millions of people have never noticed it.',
  },
  {
    id: 'e027',
    theme: 'everyday',
    q: 'Why do plug pins on many designs have insulated sleeves on part of their length?',
    a: 'So fingers cannot touch live metal while the plug is partly inserted',
    note: 'A retrofit to a design that predated the concern. The sleeve covers exactly the gap.',
  },
  {
    id: 'e028',
    theme: 'everyday',
    q: 'Why does a tea bag have a string and tag, when a bag alone would be cheaper?',
    a: 'Retrieval — and the tag doubles as branding',
    note: 'Tea bags were invented by accident: a merchant sent samples in silk pouches and customers brewed the pouch.',
  },
  {
    id: 'e029',
    theme: 'everyday',
    q: 'Why do stairs have a consistent riser height throughout a flight, by law in most countries?',
    a: 'People stop looking after two steps — an odd one causes falls',
    note: 'The most dangerous step in any building is the one that is a different height from its neighbours.',
  },
  {
    id: 'e030',
    theme: 'everyday',
    q: 'Why are road signs for warnings triangular and for prohibitions circular, in most of the world?',
    a: 'Shape carries meaning when the sign is dirty, dark or in another language',
    note: 'You can read a stop sign’s shape in a mirror at night with the paint gone.',
  },
  {
    id: 'e031',
    theme: 'everyday',
    q: 'Why is the inside of a takeaway coffee lid often domed?',
    a: 'Room for foam, and it stops the drink touching the underside',
    note: 'It also strengthens the lid so it does not flex when you press it on.',
  },
  {
    id: 'e032',
    theme: 'everyday',
    q: 'Why do zips sometimes have a small hook on the pull tab?',
    a: 'It locks the slider so it cannot creep down',
    note: 'The hook drops into the teeth when the tab lies flat. Gravity does the locking for you.',
  },
  {
    id: 'e033',
    theme: 'everyday',
    q: 'Why does a light switch in some countries go down for on and in others up?',
    a: 'Pure convention, fixed differently in different wiring standards',
    note: 'Britain down, most of continental Europe and North America up. Neither has any argument for it.',
  },
  {
    id: 'e034',
    theme: 'everyday',
    q: 'Why do many bathroom doors open inwards, and where is the exception?',
    a: 'To save corridor space — public toilets often open outwards for evacuation',
    note: 'Also so a collapsed person does not block the door, which is why some domestic ones are changing.',
  },
  {
    id: 'e035',
    theme: 'everyday',
    q: 'Why does a jam jar lid make a popping sound when first opened?',
    a: 'The vacuum from cooling breaks',
    note: 'No pop means the seal was already broken. It is a food safety indicator built out of physics.',
  },
  {
    id: 'e036',
    theme: 'everyday',
    q: 'Why do some pavements outside shops have a strip of raised bumps?',
    a: 'Tactile paving — a crossing or a hazard for people who cannot see it',
    note: 'Different patterns mean different things: blisters for crossings, bars for platform edges.',
  },
  {
    id: 'e037',
    theme: 'everyday',
    q: 'Why is a cardboard box stronger along one direction than the other?',
    a: 'The corrugations run one way',
    note: 'Stand a box on the flutes and it carries far more than laid across them.',
  },
  {
    id: 'e038',
    theme: 'everyday',
    q: 'Why do padlocks have a shackle that is thicker on one side?',
    a: 'The longer leg carries the load; the shorter one is the release',
    note: 'Attack the short side and some cheap padlocks open with a single shim.',
  },
  {
    id: 'e039',
    theme: 'everyday',
    q: 'Why do many countries put a small notch or raised dot on some banknotes?',
    a: 'So they can be told apart by touch',
    note: 'Euro notes also differ in size by denomination for the same reason.',
  },
  {
    id: 'e040',
    theme: 'everyday',
    q: 'Why does a spiral notebook have the spiral rather than a glued spine?',
    a: 'It lies flat and folds back on itself',
    note: 'You can write on a clipboard-sized surface at a table with no room, which is why field notebooks are all spiral.',
  },
  {
    id: 'e041',
    theme: 'everyday',
    q: 'Why is a shopping receipt printed on paper that fades?',
    a: 'Thermal printing has no ink — the paper darkens with heat',
    note: 'No cartridge, no ribbon, no moving parts. The fading is the price of the simplicity.',
  },
  {
    id: 'e042',
    theme: 'everyday',
    q: 'Why do washing machines have a rubber bellows around the door rather than a rigid seal?',
    a: 'The drum moves violently and the outer casing does not',
    note: 'It absorbs several centimetres of movement thousands of times per wash.',
  },
  {
    id: 'e043',
    theme: 'everyday',
    q: 'Why are the numbers on a calculator arranged with 7 at the top and on a phone with 1 at the top?',
    a: 'Calculators inherited adding machines; phones were designed after usability testing',
    note: 'Bell Labs tested layouts in the 1950s and chose the one people dialled fastest.',
  },
  {
    id: 'e044',
    theme: 'everyday',
    q: 'Why does a bag of crisps contain so much air, and what is the gas usually?',
    a: 'Cushioning — and it is nitrogen, not air',
    note: 'Oxygen would make them stale. The "air" is deliberately the part with no oxygen in it.',
  },
  {
    id: 'e045',
    theme: 'everyday',
    q: 'Why do some hotel rooms require a keycard in a slot to keep the lights on?',
    a: 'It turns everything off when you leave',
    note: 'Guests defeat it constantly with any card at all, which the industry knows and mostly tolerates.',
  },
  {
    id: 'e046',
    theme: 'everyday',
    q: 'Why does a shower curtain blow inwards when the water is running?',
    a: 'The moving water lowers the pressure inside',
    note: 'The full explanation involves a vortex and is still debated. Everybody agrees it is annoying.',
  },
  {
    id: 'e047',
    theme: 'everyday',
    q: 'Why do modern kettles switch themselves off, and what physically triggers it?',
    a: 'Steam bends a bimetallic strip',
    note: 'Two metals bonded together expanding at different rates. The whole safety feature is one strip of metal.',
  },
  {
    id: 'e048',
    theme: 'everyday',
    q: 'Why does a fridge have a light and a freezer usually not?',
    a: 'Cost and the fact that a freezer is opened less',
    note: 'The old joke about checking is answerable: fridge door switches are visible and testable.',
  },
  {
    id: 'e049',
    theme: 'everyday',
    q: 'Why are hospital and industrial floors often coved — curved up the wall rather than meeting it at a corner?',
    a: 'A corner cannot be properly cleaned',
    note: 'Dirt collects where two flat surfaces meet. Removing the corner removes the problem.',
  },
  {
    id: 'e050',
    theme: 'everyday',
    q: 'Why is there a small hole in the bottom of a padlock?',
    a: 'To drain water and to oil the mechanism',
    note: 'A padlock full of water freezes solid, which is how most outdoor ones die.',
  },
  {
    id: 'e051',
    theme: 'everyday',
    q: 'Why do trains have a distinctive two-tone horn rather than a single note?',
    a: 'A chord carries further and is harder to mistake for anything else',
    note: 'It also survives the Doppler shift: the interval stays recognisable even as the pitch drops.',
  },
  {
    id: 'e052',
    theme: 'everyday',
    q: 'Why do soft drink cans have a concave bottom?',
    a: 'It resists internal pressure — a flat one would bulge',
    note: 'The same reason a wine bottle has a punt and a gas cylinder has domed ends.',
  },
  {
    id: 'e053',
    theme: 'everyday',
    q: 'Why is the standard pencil hexagonal rather than round?',
    a: 'It does not roll off a desk, and it is cheaper to make from a square blank',
    note: 'Carpenters’ pencils are flat for the same reason, on a sloping roof.',
  },
  {
    id: 'e054',
    theme: 'everyday',
    q: 'Why do supermarkets put bakeries near the entrance?',
    a: 'The smell',
    note: 'Some pipe the extraction towards the door. It is the oldest trick in retail and it still works.',
  },
  {
    id: 'e055',
    theme: 'everyday',
    q: 'Why do laptop power supplies have a heavy block partway along the cable?',
    a: 'It converts mains AC to low-voltage DC',
    note: 'It is a transformer and rectifier in a box. Putting it in the laptop would make the laptop hot and heavy.',
  },
  {
    id: 'e056',
    theme: 'everyday',
    q: 'Why do many public buildings have doors that pull to enter and push to exit?',
    a: 'Fire escape — a crowd pushes',
    note: 'You can never pull a door open against a crowd behind you. Panic bars exist for the same reason.',
  },
  {
    id: 'e057',
    theme: 'everyday',
    q: 'Why is a wine glass shaped with a bowl and a narrower rim?',
    a: 'It concentrates the aroma and lets you swirl without spilling',
    note: 'Most of taste is smell, so a glass is mostly a device for delivering vapour to a nose.',
  },
  {
    id: 'e058',
    theme: 'everyday',
    q: 'Why do older buildings have very thick walls at the bottom and thinner ones higher up?',
    a: 'The lower walls carry everything above them',
    note: 'Before steel frames, a tall masonry building had to get fatter as it got taller.',
  },
  {
    id: 'e059',
    theme: 'everyday',
    q: 'Why do keyboards still use the QWERTY layout when faster ones exist?',
    a: 'Switching costs — everyone already knows it',
    note: 'The story that it was designed to slow typists is doubtful; it was designed to separate common pairs.',
  },
  {
    id: 'e060',
    theme: 'everyday',
    q: 'Why does a road have a slight camber even where there is no bend?',
    a: 'Drainage',
    note: 'Standing water is the difference between a road and a skating rink, and between a road and a pothole.',
  },
  {
    id: 'e061',
    theme: 'everyday',
    q: 'Why do some cameras make a shutter sound even when they have no shutter?',
    a: 'Legal requirement in some countries, and user feedback',
    note: 'Japan and South Korea mandate it. Elsewhere it survives because silence feels like failure.',
  },
  {
    id: 'e062',
    theme: 'everyday',
    q: 'Why is a standard shipping container that particular size?',
    a: 'It fits road, rail and ship, and the size was standardised in the 1960s',
    note: 'One decision about a box did more for global trade than most trade agreements.',
  },
  {
    id: 'e063',
    theme: 'everyday',
    q: 'Why do bathroom mirrors fog from the bottom up, or from the top down, depending on the room?',
    a: 'The coldest part of the glass fogs first',
    note: 'Which tells you where the draught is. A mirror is an accidental thermal camera.',
  },
  {
    id: 'e064',
    theme: 'everyday',
    q: 'Why do medicines have an expiry date when most are still chemically fine afterwards?',
    a: 'It is the date the maker guarantees full potency, not the date it becomes harmful',
    note: 'A US military study found most drugs stable for years past it. Nitroglycerine and some antibiotics are exceptions.',
  },
  {
    id: 'e065',
    theme: 'everyday',
    q: 'Why is a fire hydrant painted different colours in some countries?',
    a: 'The colour codes the available water flow',
    note: 'A firefighter needs to know at a glance whether a hydrant can supply the pump.',
  },
  {
    id: 'e066',
    theme: 'everyday',
    q: 'Why does a chair usually have a back that leans slightly rather than being vertical?',
    a: 'A vertical back pushes you forward off the seat',
    note: 'Somewhere between 100 and 110 degrees for most people. Nothing about a right angle is comfortable.',
  },
  {
    id: 'e067',
    theme: 'everyday',
    q: 'Why do many bottles of cleaning fluid have a child-resistant cap that adults also struggle with?',
    a: 'It requires two simultaneous actions',
    note: 'Push and turn. The design assumes a child cannot coordinate both, which is broadly true until about four.',
  },
  {
    id: 'e068',
    theme: 'everyday',
    q: 'Why does a supermarket freezer aisle often have no doors on the cabinets?',
    a: 'Sales — people buy more from open cases',
    note: 'The cold air sits in the well. It is enormously wasteful and slowly being reversed.',
  },
  {
    id: 'e069',
    theme: 'everyday',
    q: 'Why do wooden pencils have a hexagonal barrel but coloured pencils are often round?',
    a: 'Round is easier on the hand for long shading strokes',
    note: 'Also the leads are softer and a hexagonal barrel encourages a firmer, breakier grip.',
  },
  {
    id: 'e070',
    theme: 'everyday',
    q: 'Why do buses often have a bell cord rather than buttons at every seat, in older designs?',
    a: 'One continuous cord serves every position and cannot break individually',
    note: 'It is a single point of failure that is trivially repairable, which is often the right trade.',
  },
  {
    id: 'e071',
    theme: 'everyday',
    q: 'Why does a wet phone in rice not actually work well?',
    a: 'Rice absorbs slowly and does not reach the inside — and dust gets in',
    note: 'What matters is switching it off immediately. Corrosion happens when the power is on.',
  },
  {
    id: 'e072',
    theme: 'everyday',
    q: 'Why is a hard hat suspended inside its shell rather than resting on the head?',
    a: 'The gap absorbs the impact',
    note: 'The shell deflects; the harness decelerates. Wearing one without the harness is wearing a bowl.',
  },
  {
    id: 'e073',
    theme: 'everyday',
    q: 'Why do trainers have holes in odd places in the tongue and upper?',
    a: 'Lacing options and ventilation',
    note: 'The extra top eyelet exists for a heel-lock lacing that most owners have never used.',
  },
  {
    id: 'e074',
    theme: 'everyday',
    q: 'Why do trains and lifts have doors that reopen when something blocks them, rather than simply stopping?',
    a: 'A stopped door still traps; reopening releases',
    note: 'Failure modes are designed. The question is always "what does it do when it goes wrong", not "does it work".',
  },
  {
    id: 'e075',
    theme: 'everyday',
    q: 'Why does a duvet cover have an opening at the bottom rather than the top?',
    a: 'Gravity holds the duvet in',
    note: 'Also it is out of sight. A design decision made entirely by where the eye lands.',
  },
  {
    id: 'e076',
    theme: 'everyday',
    q: 'Why do some kitchen knives have dimples along the blade?',
    a: 'Air pockets stop food sticking',
    note: 'Called a granton edge. It works well on ham and potatoes and is largely decorative on a chef’s knife.',
  },
  {
    id: 'e077',
    theme: 'everyday',
    q: 'Why is petrol dyed different colours in some countries?',
    a: 'To identify tax status or grade',
    note: 'Red diesel for agriculture is taxed less. The dye is how an inspector proves misuse.',
  },
  {
    id: 'e078',
    theme: 'everyday',
    q: 'Why does a laptop get hotter on a bed than on a desk?',
    a: 'Soft surfaces block the vents',
    note: 'Most laptops breathe through the bottom. A duvet is an excellent insulator and a terrible desk.',
  },
  {
    id: 'e079',
    theme: 'everyday',
    q: 'Why do many taps mix hot and cold in one spout in some countries and have separate taps in others?',
    a: 'Old plumbing kept them separate for safety and pressure reasons',
    note: 'British hot water came from an open tank and was not considered drinkable. Hence two taps.',
  },
  {
    id: 'e080',
    theme: 'everyday',
    q: 'Why is a road tunnel usually brightly lit at the entrance and dimmer in the middle?',
    a: 'Eyes take time to adapt from daylight',
    note: 'The lighting is a ramp matched to human adaptation speed, not to the tunnel’s length.',
  },
  {
    id: 'e081',
    theme: 'everyday',
    q: 'Why do some clothes have a small spare button sewn inside?',
    a: 'Replacement, and it also verifies the thread and colour',
    note: 'It is stitched inside a seam so it is stored, matched and never separately lost.',
  },
  {
    id: 'e082',
    theme: 'everyday',
    q: 'Why do doorknobs in public buildings increasingly get replaced with levers?',
    a: 'A lever can be operated with an elbow, a wrist or a full hand',
    note: 'Accessibility legislation, and the fact that a knob requires a grip many people do not have.',
  },
  {
    id: 'e083',
    theme: 'everyday',
    q: 'Why does a car indicator make a clicking sound when the bulbs are silent LEDs?',
    a: 'It is synthesised — drivers need the feedback',
    note: 'The original click was a bimetallic relay. The sound outlived the mechanism that made it.',
  },
  {
    id: 'e084',
    theme: 'everyday',
    q: 'Why is a bicycle chain not a belt, when a belt would be quieter and cleaner?',
    a: 'A chain can change gear ratios by moving between sprockets',
    note: 'Belt-drive bikes exist and are excellent, provided you never want more than one gear or an internal hub.',
  },
  {
    id: 'e085',
    theme: 'everyday',
    q: 'Why do many appliances have a fuse in the plug in Britain but not elsewhere?',
    a: 'The ring main carries a high current, so each appliance protects itself',
    note: 'A radial circuit elsewhere is fused at the board. The wiring topology decides where the fuse goes.',
  },
  {
    id: 'e086',
    theme: 'everyday',
    q: 'Why does a jar sometimes open more easily after running the lid under hot water?',
    a: 'The metal expands faster than the glass',
    note: 'Different coefficients of thermal expansion, exploited in the kitchen.',
  },
  {
    id: 'e087',
    theme: 'everyday',
    q: 'Why is there a gap under most public toilet doors?',
    a: 'Cleaning, ventilation, and being able to help somebody who collapses',
    note: 'The third reason is the one nobody thinks of and the one that keeps it in the building codes.',
  },
  {
    id: 'e088',
    theme: 'everyday',
    q: 'Why do wine corks work at all, given that cork is a bark?',
    a: 'It is full of sealed gas cells and compresses without losing elasticity',
    note: 'Almost no other material compresses that far and pushes back for thirty years.',
  },
  {
    id: 'e089',
    theme: 'everyday',
    q: 'Why do office ceilings have removable tiles?',
    a: 'Everything is above them — cabling, ducts, sprinklers',
    note: 'The ceiling is a lid on a service floor. It is designed to be taken down constantly.',
  },
  {
    id: 'e090',
    theme: 'everyday',
    q: 'Why is a printed circuit board green?',
    a: 'The solder mask happens to be that colour by convention',
    note: 'They can be any colour. Green was cheapest and easiest to inspect, and then became the expectation.',
  },
  {
    id: 'e091',
    theme: 'everyday',
    q: 'Why does the tape in a cassette or a reel start with a coloured leader?',
    a: 'It is stronger and can be spliced without losing recording',
    note: 'It also protects the magnetic tape from the mechanism at the point of most stress.',
  },
  {
    id: 'e092',
    theme: 'everyday',
    q: 'Why do most stairs in old buildings have an odd number of steps in a flight?',
    a: 'Convention and superstition, and it puts you on the same foot',
    note: 'Some traditions insist on it; whether it started as ritual or ergonomics is genuinely unclear.',
  },
  {
    id: 'e093',
    theme: 'everyday',
    q: 'Why does a pressure cooker cook faster, given that water still boils?',
    a: 'Higher pressure raises the boiling point above 100°C',
    note: 'The water gets hotter without turning to steam, which is the entire trick.',
  },
  {
    id: 'e094',
    theme: 'everyday',
    q: 'Why do some pens write upside down and most do not?',
    a: 'Pressurised cartridges push the ink instead of relying on gravity',
    note: 'Developed for aviation and space. A pencil also works, which was the famous rival solution.',
  },
  {
    id: 'e095',
    theme: 'everyday',
    q: 'Why is the standard height of a kitchen worktop about 90 cm?',
    a: 'It suits the average adult’s elbow height for pushing down',
    note: 'Which is why kneading bread on a standard counter is uncomfortable for anybody tall or short.',
  },
  {
    id: 'e096',
    theme: 'everyday',
    q: 'Why do lifts in tall buildings often skip floors, with separate banks for high and low?',
    a: 'A single bank serving every floor is unbearably slow',
    note: 'Above about forty floors, lift shafts start eating the rentable area they exist to serve.',
  },
  {
    id: 'e097',
    theme: 'everyday',
    q: 'Why does a light bulb usually blow at the moment you switch it on?',
    a: 'The cold filament has low resistance, so the inrush current is highest then',
    note: 'The failure is not random; it is the one moment of maximum stress in the bulb’s life.',
  },
  {
    id: 'e098',
    theme: 'everyday',
    q: 'Why do some road markings have raised ribs?',
    a: 'Noise and vibration — a rumble strip warns a drifting driver',
    note: 'A safety device that works entirely through the ear and the seat.',
  },
  {
    id: 'e099',
    theme: 'everyday',
    q: 'Why do carpets on stairs wear out at the nose of each tread first?',
    a: 'That is where the load and the abrasion concentrate',
    note: 'Which is why good stair carpet is fitted with slack, so it can be shifted a few centimetres later.',
  },
  {
    id: 'e100',
    theme: 'everyday',
    q: 'Why is the little arrow on a road sign for a roundabout drawn as it is in different countries?',
    a: 'It shows the direction of travel, which depends on which side people drive',
    note: 'Clockwise where you drive on the left. A sign that means the opposite thing across a border.',
  },
]
