/**
 * Food and drink — cooking as chemistry, and dishes as history.
 *
 * The theme where a table full of people who cook will beat a table full of people who read,
 * which makes it a good leveller. Nearly every question is answerable by anybody who has
 * stood at a stove and paid attention.
 */
import type { Question } from '../types'

export const FOOD: readonly Question[] = [
  {
    id: 'f001',
    theme: 'food',
    q: 'Why does searing meat not "seal in the juices", and what does it actually do?',
    a: 'It browns — the Maillard reaction. Seared meat loses slightly more moisture, not less',
    note: 'The myth is nearly two centuries old and was disproved by weighing steaks.',
  },
  {
    id: 'f002',
    theme: 'food',
    q: 'Why do you add salt to pasta water, and what does it not do?',
    a: 'Seasoning — it does not meaningfully change the boiling point',
    note: 'You would need an undrinkable amount to raise it a degree. Salt the water for taste alone.',
  },
  {
    id: 'f003',
    theme: 'food',
    q: 'Why does bread need kneading, and what is happening at the molecular level?',
    a: 'Gluten strands align and link into an elastic network',
    note: 'No-knead bread does the same thing with time instead of force. Both work; one is lazier.',
  },
  {
    id: 'f004',
    theme: 'food',
    q: 'Why is a tomato botanically a fruit but legally a vegetable in the United States?',
    a: 'A Supreme Court tariff case decided by common usage',
    note: 'Nix v. Hedden, 1893. Vegetables were taxed and fruit was not, so the answer was worth money.',
  },
  {
    id: 'f005',
    theme: 'food',
    q: 'Why does chopping an onion under running water reduce crying, and what works better?',
    a: 'It washes away the volatile compound — chilling and a sharp knife work better',
    note: 'A blunt knife crushes more cells and releases more of it. Sharpness is the real fix.',
  },
  {
    id: 'f006',
    theme: 'food',
    q: 'Why does milk foam for a cappuccino, and what does the protein actually do?',
    a: 'Proteins unfold and stabilise the bubbles',
    note: 'Too hot and they denature past the point of holding. Above about 70°C the foam collapses.',
  },
  {
    id: 'f007',
    theme: 'food',
    q: 'Why is chocolate tempered, and what goes wrong if it is not?',
    a: 'To form the right crystal structure — otherwise it is soft and blooms white',
    note: 'Cocoa butter has six crystal forms. Only one of them snaps and shines.',
  },
  {
    id: 'f008',
    theme: 'food',
    q: 'Why do apples brown and lemons do not?',
    a: 'Apples have the oxidising enzyme; lemon acidity blocks it',
    note: 'Which is why lemon juice on apple slices works. It is enzyme inhibition, not a coating.',
  },
  {
    id: 'f009',
    theme: 'food',
    q: 'Why is rice washed before cooking in most of Asia, and what does it remove?',
    a: 'Surface starch, which makes it gluey',
    note: 'Unless you want it gluey — risotto rice is never washed, for exactly that reason.',
  },
  {
    id: 'f010',
    theme: 'food',
    q: 'Why did scurvy afflict sailors but rarely people on land, even eating badly?',
    a: 'Vitamin C is in fresh food, which does not survive months at sea',
    note: 'Cabbage, potatoes, even beer with hops helped. Long voyages removed every source at once.',
  },
  {
    id: 'f011',
    theme: 'food',
    q: 'Why does an egg white turn from clear to opaque white when cooked?',
    a: 'Proteins unfold and tangle, scattering light',
    note: 'Irreversible, which is why you cannot uncook an egg — though a lab has partly managed it.',
  },
  {
    id: 'f012',
    theme: 'food',
    q: 'Why is olive oil a poor choice for deep frying but excellent for dressing?',
    a: 'Lower smoke point, and the flavour compounds are destroyed by heat',
    note: 'Extra virgin especially. You are burning off the thing you paid for.',
  },
  {
    id: 'f013',
    theme: 'food',
    q: 'Why does a soufflé rise, and why does it fall?',
    a: 'Air trapped in egg white expands with heat — it falls as the air cools and contracts',
    note: 'The structure sets late. Open the oven early and it collapses before the protein has set.',
  },
  {
    id: 'f014',
    theme: 'food',
    q: 'Why is bread in a French bakery legally required to contain only four ingredients to be called by a certain name?',
    a: 'Flour, water, salt and yeast — for a traditional baguette',
    note: 'The 1993 Décret Pain. A law about bread, taken seriously enough to be a decree.',
  },
  {
    id: 'f015',
    theme: 'food',
    q: 'Why does resting meat after cooking matter?',
    a: 'The juices redistribute instead of running out when cut',
    note: 'The muscle fibres relax as they cool. Cut immediately and the board takes what the plate wanted.',
  },
  {
    id: 'f016',
    theme: 'food',
    q: 'Why does a cast iron pan need seasoning, and what is the seasoning made of?',
    a: 'Polymerised oil bonded to the metal',
    note: 'It is not oil sitting on the surface. It is a plastic-like layer chemically bound to the iron.',
  },
  {
    id: 'f017',
    theme: 'food',
    q: 'Why is a potato that has turned green dangerous?',
    a: 'Green indicates light exposure, which correlates with solanine',
    note: 'The chlorophyll is harmless. It is the alkaloid produced alongside it that is not.',
  },
  {
    id: 'f018',
    theme: 'food',
    q: 'Why did the potato transform northern European diets more than any other New World crop?',
    a: 'It yields far more calories per acre than grain in cool wet climates',
    note: 'It also grows underground, which makes it much harder for an army to burn.',
  },
  {
    id: 'f019',
    theme: 'food',
    q: 'Why does pasta water go cloudy, and why do cooks save it?',
    a: 'Released starch — it emulsifies and thickens a sauce',
    note: 'The single most useful thing most home cooks are not doing.',
  },
  {
    id: 'f020',
    theme: 'food',
    q: 'Why does honey never spoil?',
    a: 'Very low water content and acidity — bacteria cannot grow',
    note: 'Edible honey has been found in Egyptian tombs. It is essentially a preserved sugar syrup.',
  },
  {
    id: 'f021',
    theme: 'food',
    q: 'Why is it hard to make good coffee with boiling water?',
    a: 'It extracts bitter compounds — around 92–96°C is better',
    note: 'Bitterness is over-extraction. The variable people usually blame is the beans; often it is the kettle.',
  },
  {
    id: 'f022',
    theme: 'food',
    q: 'Why do recipes say to add eggs to a hot mixture slowly, and what is the technique called?',
    a: 'Tempering — to stop them scrambling',
    note: 'You raise the eggs to the sauce’s temperature rather than the reverse. Order of operations, in a saucepan.',
  },
  {
    id: 'f023',
    theme: 'food',
    q: 'Why is sushi rice seasoned with vinegar, historically?',
    a: 'It began as a preservation method — fermented rice preserved the fish',
    note: 'The rice was originally thrown away. Modern sushi keeps the flavour and drops the fermentation.',
  },
  {
    id: 'f024',
    theme: 'food',
    q: 'Why does cheese melt smoothly in some cases and turn into oil and rubber in others?',
    a: 'Age and moisture — aged cheese has less water and more free fat',
    note: 'Young cheeses melt; very old ones separate. Sodium citrate is the chemist’s cheat.',
  },
  {
    id: 'f025',
    theme: 'food',
    q: 'Why is a chilli hot, and why does milk help more than water?',
    a: 'Capsaicin triggers heat receptors — it is fat-soluble, and milk has fat and casein',
    note: 'Water spreads it around. Beer does not help either, for the same reason.',
  },
  {
    id: 'f026',
    theme: 'food',
    q: 'Why do bananas ripen faster in a paper bag?',
    a: 'They emit ethylene, and the bag concentrates it',
    note: 'Which is also why one ripe banana ruins a whole bowl of fruit.',
  },
  {
    id: 'f027',
    theme: 'food',
    q: 'Why is a stock simmered and never boiled?',
    a: 'Boiling emulsifies fat and breaks up solids, making it cloudy',
    note: 'Clarity is the whole difference between stock and dishwater. It is a temperature decision.',
  },
  {
    id: 'f028',
    theme: 'food',
    q: 'Why did the Columbian exchange make Italian food unrecognisable to a Roman?',
    a: 'Tomatoes came from the Americas',
    note: 'So did chilli for Indian and Thai food, and potatoes for Ireland. Every "traditional" cuisine is younger than it looks.',
  },
  {
    id: 'f029',
    theme: 'food',
    q: 'Why does adding sugar to a tomato sauce work, and what is it correcting?',
    a: 'Acidity',
    note: 'A pinch of sugar or a piece of carrot. You are balancing pH, not sweetening.',
  },
  {
    id: 'f030',
    theme: 'food',
    q: 'Why is bread stale-tasting bread still good for some dishes but not for a sandwich?',
    a: 'Staling is starch recrystallising, which reverses with heat and absorbs liquid well',
    note: 'Which is why French toast, panzanella and bread pudding all exist. Staling was a problem somebody solved deliciously.',
  },
  {
    id: 'f031',
    theme: 'food',
    q: 'Why is champagne opened by twisting the bottle rather than the cork?',
    a: 'More control, and the cork does not shear',
    note: 'The pressure inside is about three times a car tyre. A cork can leave at 50 km/h.',
  },
  {
    id: 'f032',
    theme: 'food',
    q: 'Why does whipping cream work, and why does over-whipping give you butter?',
    a: 'Fat globules trap air; pushed further they clump and the water separates',
    note: 'Butter is over-whipped cream. Every accident in the kitchen is a different product.',
  },
  {
    id: 'f033',
    theme: 'food',
    q: 'Why is salt used to preserve food, in one sentence?',
    a: 'It draws water out, and microbes cannot grow without it',
    note: 'Sugar does the same. Both preserve by making the food an unliveable place.',
  },
  {
    id: 'f034',
    theme: 'food',
    q: 'Why does a knife go through an onion more easily along the grain than across?',
    a: 'The cell structure runs in one direction',
    note: 'And cutting with the grain releases less of the compound that makes you cry.',
  },
  {
    id: 'f035',
    theme: 'food',
    q: 'Why do professional kitchens plate food so much hotter than home cooks manage?',
    a: 'They heat the plates',
    note: 'A cold plate takes a significant fraction of the food’s heat before it reaches the table.',
  },
  {
    id: 'f036',
    theme: 'food',
    q: 'Why is a "dry-aged" steak more expensive, and what is actually happening?',
    a: 'Moisture loss and enzymatic breakdown — and a lot of the meat is trimmed away',
    note: 'You pay for what evaporated and what was cut off, plus weeks of refrigerated space.',
  },
  {
    id: 'f037',
    theme: 'food',
    q: 'Why is beer bottled in brown glass?',
    a: 'It blocks the light that degrades hop compounds',
    note: 'Green and clear glass let it through, which is why some beers taste "skunked" in sunlight.',
  },
  {
    id: 'f038',
    theme: 'food',
    q: 'Why does yeast need sugar, and where does the sugar in bread dough come from?',
    a: 'Enzymes break flour starch into sugar',
    note: 'You do not need to add any. Adding some just gets it started faster.',
  },
  {
    id: 'f039',
    theme: 'food',
    q: 'Why is coffee decaffeinated with water, carbon dioxide or solvents, and which method is named after a place?',
    a: 'The Swiss Water Process',
    note: 'It uses saturated coffee extract so the flavour has nowhere to go, and only the caffeine leaves.',
  },
  {
    id: 'f040',
    theme: 'food',
    q: 'Why does a cake need both baking powder and, sometimes, an acid like buttermilk?',
    a: 'Bicarbonate needs an acid to react — powder contains its own, soda does not',
    note: 'Which is why substituting one for the other without adjusting the acid ruins a cake.',
  },
  {
    id: 'f041',
    theme: 'food',
    q: 'Why do restaurants put butter under the skin of a chicken rather than on it?',
    a: 'It bastes the meat and crisps the skin from beneath',
    note: 'Butter on top mostly runs off. Under the skin it is trapped exactly where it is useful.',
  },
  {
    id: 'f042',
    theme: 'food',
    q: 'Why is wine served at different temperatures, and what does cold do to a red?',
    a: 'Cold suppresses aroma and emphasises tannin',
    note: 'Most reds are served too warm and most whites too cold. Room temperature meant a colder room.',
  },
  {
    id: 'f043',
    theme: 'food',
    q: 'Why does bread baked in a very hot oven with steam have a better crust?',
    a: 'Steam delays the crust forming so the loaf can rise, then it crisps',
    note: 'Professional ovens inject it. At home a tray of water or a covered pot does the same job.',
  },
  {
    id: 'f044',
    theme: 'food',
    q: 'Why is monosodium glutamate not the villain it was made out to be?',
    a: 'The scare rested on a single anecdotal letter and studies never replicated it',
    note: 'Glutamate occurs naturally in tomatoes, parmesan and seaweed. Umami was named before it was explained.',
  },
  {
    id: 'f045',
    theme: 'food',
    q: 'Why does a pan need to be hot before food goes in?',
    a: 'To brown rather than steam',
    note: 'Cold pan means the food releases water before it can sear, and then it boils in it.',
  },
  {
    id: 'f046',
    theme: 'food',
    q: 'Why is bread in most of the world made with wheat rather than any other grain?',
    a: 'Gluten — no other common grain traps gas as well',
    note: 'Rye manages some. Everything else needs a different technique entirely.',
  },
  {
    id: 'f047',
    theme: 'food',
    q: 'Why is a tagine shaped with a tall conical lid?',
    a: 'Steam condenses and runs back down — cooking with very little water',
    note: 'A closed-loop cooking vessel designed for somewhere water is precious.',
  },
  {
    id: 'f048',
    theme: 'food',
    q: 'Why does fish cook so much faster than meat?',
    a: 'Much less connective tissue',
    note: 'Fish muscle is built for short bursts in a supportive medium. It falls apart at a much lower temperature.',
  },
  {
    id: 'f049',
    theme: 'food',
    q: 'Why is a proper mayonnaise an emulsion, and what does the egg yolk do?',
    a: 'It stabilises oil suspended in water — lecithin is the emulsifier',
    note: 'A teaspoon of yolk holds an astonishing amount of oil. It splits when you add oil faster than it can be dispersed.',
  },
  {
    id: 'f050',
    theme: 'food',
    q: 'Why does salting an aubergine before cooking help, and what is the modern view?',
    a: 'It draws out water and bitterness — modern varieties are much less bitter, so it mostly helps texture',
    note: 'It also means it absorbs less oil, which is the reason worth keeping.',
  },
  {
    id: 'f051',
    theme: 'food',
    q: 'Why is bread sometimes scored before baking?',
    a: 'To control where it expands',
    note: 'Uncut, it splits wherever the crust is weakest. The baker’s signature is also a structural decision.',
  },
  {
    id: 'f052',
    theme: 'food',
    q: 'Why did margarine originally have to be sold uncoloured in some places?',
    a: 'Dairy lobbies got laws banning it from looking like butter',
    note: 'Some sold a yellow dye capsule separately for the customer to mix in at home.',
  },
  {
    id: 'f053',
    theme: 'food',
    q: 'Why is a "cold brew" coffee less bitter than the same coffee brewed hot?',
    a: 'Cold water extracts fewer of the bitter compounds',
    note: 'It takes twelve hours instead of four minutes. Chemistry traded for time.',
  },
  {
    id: 'f054',
    theme: 'food',
    q: 'Why is a lobster’s shell blue-black alive and red cooked?',
    a: 'Heat releases a red pigment bound to a protein',
    note: 'Astaxanthin is red all along. The protein wrapping it is what changes colour.',
  },
  {
    id: 'f055',
    theme: 'food',
    q: 'Why is a sourdough starter alive, and what two organisms is it?',
    a: 'Wild yeast and lactic acid bacteria',
    note: 'The bacteria make the sour, the yeast makes the rise. They are a stable partnership, not a contamination.',
  },
  {
    id: 'f056',
    theme: 'food',
    q: 'Why does a copper bowl help when whisking egg whites?',
    a: 'Copper ions stabilise the protein',
    note: 'A pinch of cream of tartar does the same thing much more cheaply.',
  },
  {
    id: 'f057',
    theme: 'food',
    q: 'Why is a carrot sweeter after frost?',
    a: 'The plant converts starch to sugar as antifreeze',
    note: 'Parsnips and sprouts do the same. The vegetable is protecting itself and you get the benefit.',
  },
  {
    id: 'f058',
    theme: 'food',
    q: 'Why is a wok shaped with a round bottom and used over a very high flame?',
    a: 'A temperature gradient — very hot at the base, cooler up the sides',
    note: 'You cook and park in the same vessel. Domestic hobs cannot really deliver the heat it wants.',
  },
  {
    id: 'f059',
    theme: 'food',
    q: 'Why does pineapple prevent jelly from setting?',
    a: 'It contains an enzyme that digests gelatine',
    note: 'Bromelain. Cooking destroys it, which is why tinned pineapple works and fresh does not.',
  },
  {
    id: 'f060',
    theme: 'food',
    q: 'Why is bread dough allowed to rise twice in most recipes?',
    a: 'The second rise develops flavour and a finer crumb',
    note: 'One rise gives you bread. Two gives you good bread. Three is where diminishing returns start.',
  },
  {
    id: 'f061',
    theme: 'food',
    q: 'Why does a barbecue give a different flavour from an oven at the same temperature?',
    a: 'Fat dripping onto heat vaporises and condenses back onto the food',
    note: 'The smoke is made of the food itself. That is why the drip tray matters more than the wood.',
  },
  {
    id: 'f062',
    theme: 'food',
    q: 'Why did tea become the British national drink rather than coffee, when both arrived together?',
    a: 'The East India Company’s trade routes and tax policy',
    note: 'Coffee houses came first. Empire decided which one won.',
  },
  {
    id: 'f063',
    theme: 'food',
    q: 'Why is a pressure cooker good for tough cuts and bad for green vegetables?',
    a: 'Collagen needs long hot cooking; delicate cell walls collapse',
    note: 'Same tool, opposite result. It is a machine for one specific chemical change.',
  },
  {
    id: 'f064',
    theme: 'food',
    q: 'Why does a knife cut a tomato badly when it is blunt and well when it is sharp, more dramatically than with other foods?',
    a: 'The skin is tough and the inside is soft — a blunt blade crushes before it cuts',
    note: 'A tomato is the standard test for a kitchen knife for exactly this reason.',
  },
  {
    id: 'f065',
    theme: 'food',
    q: 'Why is caviar traditionally served with a mother-of-pearl spoon?',
    a: 'Metal reacts and taints the flavour',
    note: 'Bone and horn also work. Silver is the worst offender.',
  },
  {
    id: 'f066',
    theme: 'food',
    q: 'Why does bread dough need salt beyond flavour?',
    a: 'It strengthens gluten and slows fermentation',
    note: 'Leave it out and the dough is slack, fast and tastes of nothing. Tuscan bread does it deliberately.',
  },
  {
    id: 'f067',
    theme: 'food',
    q: 'Why is a "flat white" different from a latte, technically?',
    a: 'Less foam, more finely textured milk',
    note: 'The argument about who invented it is fought between Australia and New Zealand and will not be settled.',
  },
  {
    id: 'f068',
    theme: 'food',
    q: 'Why does an avocado go brown so fast when cut, faster than an apple?',
    a: 'Very high concentration of the oxidising enzyme',
    note: 'Keeping the stone in does nothing except cover the part it touches.',
  },
  {
    id: 'f069',
    theme: 'food',
    q: 'Why is vanilla so expensive?',
    a: 'Every flower is pollinated by hand and the pods are cured for months',
    note: 'The natural pollinator is a Mexican bee. Outside Mexico, every pod is a human’s work.',
  },
  {
    id: 'f070',
    theme: 'food',
    q: 'Why does a stew taste better the next day?',
    a: 'Flavours diffuse and starches and fats redistribute',
    note: 'Some compounds also continue reacting slowly in the fridge. Time is an ingredient.',
  },
  {
    id: 'f071',
    theme: 'food',
    q: 'Why is a "confit" preserved in fat, and how does that work?',
    a: 'Fat excludes air and the salt cure draws out water',
    note: 'Cooked slowly, then sealed under its own fat. Refrigeration for a world without it.',
  },
  {
    id: 'f072',
    theme: 'food',
    q: 'Why does adding oil to pasta water not stop pasta sticking?',
    a: 'The oil floats — it never touches the pasta',
    note: 'Stirring in the first two minutes is what works. Oil only helps the pot boil over less.',
  },
  {
    id: 'f073',
    theme: 'food',
    q: 'Why do so many cuisines pair a fatty food with an acidic one?',
    a: 'Acid cuts richness and resets the palate',
    note: 'Lemon on fish, vinegar on chips, pickles with pork. It is the most universal rule in cooking.',
  },
  {
    id: 'f074',
    theme: 'food',
    q: 'Why is a "sell by" date different from a "use by" date, and which is about safety?',
    a: 'Use by is safety; sell by is stock rotation',
    note: 'Best before is quality. Three different dates, and shoppers treat them all the same way.',
  },
  {
    id: 'f075',
    theme: 'food',
    q: 'Why does a bay leaf go into a stew whole and come out whole?',
    a: 'It releases flavour slowly and is unpleasant to eat',
    note: 'Also mildly hazardous to swallow — the leaf stays stiff and sharp-edged after hours of cooking.',
  },
  {
    id: 'f076',
    theme: 'food',
    q: 'Why is bread made in high-altitude kitchens with less yeast or less rising time?',
    a: 'Lower pressure means gas expands more, so it over-proves',
    note: 'Baking at altitude is a different craft. Most published recipes silently assume sea level.',
  },
  {
    id: 'f077',
    theme: 'food',
    q: 'Why does a hard-boiled egg sometimes have a green ring around the yolk?',
    a: 'Overcooking — iron and sulphur react',
    note: 'Harmless, and entirely a matter of time and temperature. Ice water stops it immediately.',
  },
  {
    id: 'f078',
    theme: 'food',
    q: 'Why is a Parmesan wheel that shape and size?',
    a: 'It suits ageing — surface to volume, and it can be turned by one person',
    note: 'Around 40 kg. Italian banks accept wheels as loan collateral and store them in vaults.',
  },
  {
    id: 'f079',
    theme: 'food',
    q: 'Why does searing a scallop require an almost dry surface?',
    a: 'Water must boil off before browning can start',
    note: 'A wet scallop steams itself grey. The pat with kitchen paper is not fussiness.',
  },
  {
    id: 'f080',
    theme: 'food',
    q: 'Why is a "72-hour" pizza dough better, and what happened in that time?',
    a: 'Slow cold fermentation develops flavour without over-rising',
    note: 'The yeast works slowly at fridge temperature while the enzymes keep going. Flavour is mostly patience.',
  },
  {
    id: 'f081',
    theme: 'food',
    q: 'Why is soy sauce brewed rather than mixed?',
    a: 'It is fermented with mould and bacteria over months',
    note: 'Chemically hydrolysed versions exist, are much faster, and taste like it.',
  },
  {
    id: 'f082',
    theme: 'food',
    q: 'Why does an oyster taste different depending on where it grew, even within the same species?',
    a: 'It filters the local water — salinity and minerals',
    note: 'The French call it merroir, by analogy with terroir. It is measurable, not marketing.',
  },
  {
    id: 'f083',
    theme: 'food',
    q: 'Why does a good hollandaise split if it gets too hot, and how is it rescued?',
    a: 'The egg scrambles — whisk it into a fresh yolk or a spoon of water',
    note: 'It is an emulsion held together by a protein you can destroy in ten seconds.',
  },
  {
    id: 'f084',
    theme: 'food',
    q: 'Why is white chocolate arguably not chocolate?',
    a: 'It contains cocoa butter but no cocoa solids',
    note: 'Legally it is chocolate in most places. Purists have never accepted it and never will.',
  },
  {
    id: 'f085',
    theme: 'food',
    q: 'Why is the crust of a loaf a different colour from the crumb?',
    a: 'It gets hot enough for browning; the inside never exceeds 100°C',
    note: 'The inside is steam-cooked. Two entirely different cooking processes in one object.',
  },
  {
    id: 'f086',
    theme: 'food',
    q: 'Why does a mushroom brown rather than steam if the pan is not crowded?',
    a: 'Mushrooms are mostly water — too many at once and they boil in it',
    note: 'The instruction to cook them in batches is the difference between a mushroom and a grey mushroom.',
  },
  {
    id: 'f087',
    theme: 'food',
    q: 'Why is a "double boiler" used for delicate sauces and melting chocolate?',
    a: 'The temperature cannot exceed boiling water',
    note: 'You are using physics as a thermostat, which is much more reliable than a hob dial.',
  },
  {
    id: 'f088',
    theme: 'food',
    q: 'Why did sugar transform European diets so violently in the eighteenth century?',
    a: 'Plantation slavery made it cheap',
    note: 'Consumption in Britain rose roughly twentyfold in a century. The economics were the whole story.',
  },
  {
    id: 'f089',
    theme: 'food',
    q: 'Why does a knife stay sharper if it is not put in a dishwasher?',
    a: 'Heat, detergent and knocking against other items',
    note: 'The detergent is abrasive and alkaline. Most kitchen knife damage is dishwasher damage.',
  },
  {
    id: 'f090',
    theme: 'food',
    q: 'Why is a "kilocalorie" what people mean when they say "calorie" on food packaging?',
    a: 'The food calorie is a thousand of the physics one',
    note: 'A single physics calorie heats one gram of water by one degree. Nobody wanted six-figure numbers on a label.',
  },
  {
    id: 'f091',
    theme: 'food',
    q: 'Why does gelatine set, and why is agar different?',
    a: 'Gelatine is collagen that gels when cooled; agar is a plant polysaccharide that sets firmer and higher',
    note: 'Agar sets at room temperature and does not melt in the mouth, which is why it feels different.',
  },
  {
    id: 'f092',
    theme: 'food',
    q: 'Why is bread from a bakery often better than the same recipe at home?',
    a: 'A deck oven with steam and enormous thermal mass',
    note: 'A domestic oven loses most of its heat when the door opens. The recipe is rarely the limiting factor.',
  },
  {
    id: 'f093',
    theme: 'food',
    q: 'Why is a "brine" used on a turkey, and what does it do beyond salt?',
    a: 'It changes protein structure so the meat holds more water',
    note: 'Which is why a brined bird survives being overcooked, and an unbrined one does not.',
  },
  {
    id: 'f094',
    theme: 'food',
    q: 'Why do so many spirits legally have to be aged in oak?',
    a: 'The wood supplies colour, flavour and slow oxidation',
    note: 'Bourbon must use new charred oak. Scotch usually reuses barrels bourbon has finished with.',
  },
  {
    id: 'f095',
    theme: 'food',
    q: 'Why does a lemon meringue pie sometimes weep?',
    a: 'Undercooked meringue over a hot filling releases syrup',
    note: 'Put the meringue on while the filling is hot and bake it properly. Half of pastry is temperature management.',
  },
  {
    id: 'f096',
    theme: 'food',
    q: 'Why do supermarket tomatoes taste of less than garden ones, in one specific breeding decision?',
    a: 'They were bred to ripen uniformly, which disabled a gene that also made sugar',
    note: 'A 2012 paper identified it. The even red colour and the flavour were the same gene.',
  },
  {
    id: 'f097',
    theme: 'food',
    q: 'Why is a "Maillard reaction" not the same as caramelisation?',
    a: 'Maillard needs protein and sugar; caramelisation is sugar alone',
    note: 'A steak browns by Maillard, an onion does both, a crème brûlée top is caramelisation.',
  },
  {
    id: 'f098',
    theme: 'food',
    q: 'Why does adding cream to a sauce stop it splitting when you add acid?',
    a: 'The higher fat and stabilisers hold the emulsion',
    note: 'Low-fat cream curdles readily. Fat is doing structural work, not just carrying flavour.',
  },
  {
    id: 'f099',
    theme: 'food',
    q: 'Why is a fresh egg harder to peel when boiled than an older one?',
    a: 'The pH rises with age and the membrane separates more easily',
    note: 'Which is the one case where the fresher ingredient is worse for the job.',
  },
  {
    id: 'f100',
    theme: 'food',
    q: 'Why is the phrase "you eat with your eyes first" more literally true than it sounds?',
    a: 'Colour and presentation measurably change reported taste',
    note: 'Studies have changed people’s judgement of identical wine by dyeing it. Perception is not a metaphor here.',
  },
]
