/**
 * Places — why the map looks the way it does.
 *
 * "What is the capital of X" is a flashcard. Everything here asks why a border bends, why a
 * city is where it is, or what a place name is admitting about itself — all of which can be
 * reasoned about by anybody who has looked at a map and wondered.
 */
import type { Question } from '../types'

export const GEOGRAPHY: readonly Question[] = [
  {
    id: 'g001',
    theme: 'geography',
    q: 'Many African borders are perfectly straight lines. What does that tell you about how they were drawn?',
    a: 'By Europeans with rulers, without reference to the ground or the people',
    note: 'Largely at the Berlin Conference of 1884–85. Around a third of Africa’s borders are geometric.',
  },
  {
    id: 'g002',
    theme: 'geography',
    q: 'Why is almost every major inland city on a river, and specifically at a particular point on it?',
    a: 'The lowest bridging point, or the highest navigable one',
    note: 'London, Paris, Cologne. A city forms where the road crossing meets the boat traffic.',
  },
  {
    id: 'g003',
    theme: 'geography',
    q: 'What is unusual about Lesotho, and which other two countries share the same distinction?',
    a: 'Entirely surrounded by one country — with San Marino and Vatican City',
    note: 'Lesotho is also the only country entirely above 1,000 metres.',
  },
  {
    id: 'g004',
    theme: 'geography',
    q: 'Why does the Nile flow north, and why do people find that surprising?',
    a: 'Because the land is higher in the south — people wrongly assume rivers flow "down" the map',
    note: 'North is up only by convention. Rivers have no opinion about cartography.',
  },
  {
    id: 'g005',
    theme: 'geography',
    q: 'What single geographic feature explains why Chile is the shape it is?',
    a: 'The Andes',
    note: 'A country defined entirely by a mountain range on one side and an ocean on the other.',
  },
  {
    id: 'g006',
    theme: 'geography',
    q: 'Why are there so many cities called some version of "new" a place in the old world, and what does the pattern say about the namers?',
    a: 'Settlers named places after home — homesickness as cartography',
    note: 'New York, New Orleans, Nova Scotia, Nieuw Amsterdam. Almost never named for what was already there.',
  },
  {
    id: 'g007',
    theme: 'geography',
    q: 'Why is the Mercator projection still used for navigation despite badly distorting area?',
    a: 'It preserves angles — a straight line on it is a constant compass bearing',
    note: 'Exactly the wrong map for comparing countries and exactly the right one for sailing to them.',
  },
  {
    id: 'g008',
    theme: 'geography',
    q: 'What is the reason the Sahara is where it is, in terms of atmospheric circulation?',
    a: 'The descending limb of the Hadley cell around 30° latitude',
    note: 'Which is why most of the world’s deserts sit in two bands at roughly the same latitudes north and south.',
  },
  {
    id: 'g009',
    theme: 'geography',
    q: 'Why does Russia have eleven time zones while China, which is almost as wide, has one?',
    a: 'A political decision — China standardised on Beijing time',
    note: 'In Kashgar the sun rises around ten. People keep an unofficial local time alongside it.',
  },
  {
    id: 'g010',
    theme: 'geography',
    q: 'What do the Netherlands, Bangladesh and the Nile Delta have in common that makes them all nervous?',
    a: 'Very large populations on land at or below sea level',
    note: 'All three are deltas. Deltas are fertile because they flood, which is the problem.',
  },
  {
    id: 'g011',
    theme: 'geography',
    q: 'Why is Istanbul’s position considered one of the most valuable in the world?',
    a: 'It controls the only sea route between the Black Sea and the Mediterranean',
    note: 'And sits on the land route between Europe and Asia. Two chokepoints crossing at one city.',
  },
  {
    id: 'g012',
    theme: 'geography',
    q: 'What is remarkable about the fact that Reykjavik heats almost all its buildings without burning anything?',
    a: 'Geothermal water, straight from the ground',
    note: 'Iceland sits on a spreading ridge. The pavements are heated too, which solves snow clearing.',
  },
  {
    id: 'g013',
    theme: 'geography',
    q: 'Why does Britain drive on the left when most of Europe drives on the right, according to the usual explanation?',
    a: 'Riders kept their sword arm towards oncoming traffic; Napoleon standardised the other way',
    note: 'Wagon teams in America were driven from the left rear horse, favouring the right. Both stories are partly true.',
  },
  {
    id: 'g014',
    theme: 'geography',
    q: 'What is the highest mountain in the world measured from its own base rather than from sea level?',
    a: 'Mauna Kea',
    note: 'Over 10,000 metres from the seabed. Everest wins only because it starts on a plateau.',
  },
  {
    id: 'g015',
    theme: 'geography',
    q: 'Why do so many US state borders in the west run along lines of latitude and longitude, while eastern ones follow rivers?',
    a: 'The west was surveyed before it was settled',
    note: 'Rivers are what you use when people are already there. Grids are what you use when they are not.',
  },
  {
    id: 'g016',
    theme: 'geography',
    q: 'What is the Coriolis effect actually responsible for, and what is it famously not responsible for?',
    a: 'Large-scale wind and current rotation — not the direction water drains from a sink',
    note: 'The effect is far too weak at that scale. The basin’s shape decides.',
  },
  {
    id: 'g017',
    theme: 'geography',
    q: 'Why is Venice sinking, and what has made it worse in the last century?',
    a: 'Natural subsidence plus groundwater extraction',
    note: 'The pumping was stopped in the 1960s. The sinking slowed but the sea kept rising.',
  },
  {
    id: 'g018',
    theme: 'geography',
    q: 'What single fact explains why the Amazon carries about a fifth of all river water on earth?',
    a: 'It drains an enormous basin in the wettest part of the tropics',
    note: 'Its outflow is greater than the next seven largest rivers combined.',
  },
  {
    id: 'g019',
    theme: 'geography',
    q: 'Why are there no permanent human settlements in Antarctica, only stations?',
    a: 'The treaty forbids territorial claims being pursued, and nothing supports a permanent population',
    note: 'Two Argentinian and Chilean settlements have families and schools, which is as close as it gets.',
  },
  {
    id: 'g020',
    theme: 'geography',
    q: 'What is the reason Singapore imports sand, and what is it doing with it?',
    a: 'Reclaiming land — it has grown by about a quarter',
    note: 'Several neighbours have banned sand exports to it. Sand is now a strategic commodity.',
  },
  {
    id: 'g021',
    theme: 'geography',
    q: 'Why is the Dead Sea shrinking, and what is the main cause?',
    a: 'The Jordan is diverted for agriculture and drinking water',
    note: 'It has dropped over thirty metres since 1930, and sinkholes now open along the old shore.',
  },
  {
    id: 'g022',
    theme: 'geography',
    q: 'What do Gibraltar, the Bosphorus, Hormuz and Malacca have in common, and why does it matter economically?',
    a: 'All are narrow chokepoints controlling enormous shipping volumes',
    note: 'A fifth of the world’s oil passes Hormuz. Geography is still most of geopolitics.',
  },
  {
    id: 'g023',
    theme: 'geography',
    q: 'Why does Australia have such unusual wildlife?',
    a: 'It separated early and stayed isolated',
    note: 'Marsupials elsewhere had to compete with placental mammals. In Australia they did not.',
  },
  {
    id: 'g024',
    theme: 'geography',
    q: 'What is a "rain shadow", and name a famous desert created by one.',
    a: 'Dry land behind a mountain range — the Atacama, the Gobi, Nevada',
    note: 'Air drops its moisture climbing one side and arrives dry on the other.',
  },
  {
    id: 'g025',
    theme: 'geography',
    q: 'Why is Canada’s population concentrated within a couple of hundred kilometres of one border?',
    a: 'That is where the climate and the arable land are',
    note: 'About 90% within 160 km of the United States. It is a long thin country, not a wide one.',
  },
  {
    id: 'g026',
    theme: 'geography',
    q: 'What is unusual about the Caspian Sea’s legal status, and why does it matter?',
    a: 'Whether it is a sea or a lake changes how its oil is divided',
    note: 'Five countries argued about the definition for decades because the answer was worth billions.',
  },
  {
    id: 'g027',
    theme: 'geography',
    q: 'Why does the Gulf Stream make Britain warmer than places at the same latitude, and which places are those?',
    a: 'It carries tropical water north — Labrador, and parts of Siberia',
    note: 'London and Calgary are at almost the same latitude. One has palm trees in Cornwall.',
  },
  {
    id: 'g028',
    theme: 'geography',
    q: 'What happened to the Aral Sea, and what is now growing where it was?',
    a: 'It was drained for cotton irrigation — there is a desert with ships in it',
    note: 'It was the world’s fourth-largest lake. Its loss is visible from orbit in a single human lifetime.',
  },
  {
    id: 'g029',
    theme: 'geography',
    q: 'Why do hurricanes never form at the equator?',
    a: 'The Coriolis effect is zero there, so nothing makes them spin',
    note: 'They need about five degrees of latitude to get started.',
  },
  {
    id: 'g030',
    theme: 'geography',
    q: 'What single decision explains why Brasília exists?',
    a: 'To move the capital inland and develop the interior',
    note: 'Built from nothing in about four years, and laid out in the shape of an aeroplane.',
  },
  {
    id: 'g031',
    theme: 'geography',
    q: 'Why is the Vatican the world’s smallest country, and what is the second smallest?',
    a: 'It was what remained of the Papal States — Monaco',
    note: 'Vatican City is about 0.49 km². You can walk round the whole country in half an hour.',
  },
  {
    id: 'g032',
    theme: 'geography',
    q: 'What geological event created the Mediterranean as we know it, and how long did the refill take?',
    a: 'The Zanclean flood through Gibraltar — possibly as little as a couple of years',
    note: 'The basin had dried out almost entirely. The refill may have been the largest flood in earth’s history.',
  },
  {
    id: 'g033',
    theme: 'geography',
    q: 'Why does Japan have so many earthquakes and volcanoes, in one phrase?',
    a: 'It sits where several plates meet — the Ring of Fire',
    note: 'Four plates converge near Japan, which is an unusually crowded piece of crust.',
  },
  {
    id: 'g034',
    theme: 'geography',
    q: 'What is the practical reason so many capital cities were built inland from a country’s main port?',
    a: 'Safety from naval attack and raiding',
    note: 'Madrid, Moscow, Beijing. A capital on the coast is a capital that can be shelled.',
  },
  {
    id: 'g035',
    theme: 'geography',
    q: 'Why is Alaska separated from the rest of the United States, and how did it become American?',
    a: 'It was bought from Russia',
    note: '1867, about two cents an acre. It was called Seward’s Folly until gold was found.',
  },
  {
    id: 'g036',
    theme: 'geography',
    q: 'What do the names Sahara, Gobi and Kalahari have in common?',
    a: 'Each simply means "desert" in a local language',
    note: 'So "the Sahara Desert" is "the desert desert". The same happens with rivers all over the world.',
  },
  {
    id: 'g037',
    theme: 'geography',
    q: 'Why does the Panama Canal run roughly north-west to south-east, when people assume it runs east-west?',
    a: 'The isthmus curves — you exit the Pacific end east of the Atlantic end',
    note: 'The sun rises over the Pacific from the canal, which sounds impossible and is not.',
  },
  {
    id: 'g038',
    theme: 'geography',
    q: 'What is permafrost, and why is its thawing a problem beyond the buildings on it?',
    a: 'Permanently frozen ground — it releases stored carbon and methane',
    note: 'It also holds ancient organic matter and, occasionally, viable microbes.',
  },
  {
    id: 'g039',
    theme: 'geography',
    q: 'Why do so many European cities have a district called some version of "the new town"?',
    a: 'Planned eighteenth or nineteenth-century expansion outside the medieval walls',
    note: 'Edinburgh’s is the famous one. The "old town" only became old when something newer appeared.',
  },
  {
    id: 'g040',
    theme: 'geography',
    q: 'What single fact about Bolivia and Paraguay makes their trade unusually expensive?',
    a: 'Both are landlocked in South America',
    note: 'Bolivia lost its coast in a war and still maintains a navy on Lake Titicaca.',
  },
  {
    id: 'g041',
    theme: 'geography',
    q: 'Why is the Atacama the driest place on earth, and what is used there because of it?',
    a: 'A rain shadow plus a cold current — it hosts major observatories',
    note: 'Some weather stations there have never recorded rain. Clear skies year round.',
  },
  {
    id: 'g042',
    theme: 'geography',
    q: 'What are the "Blue Banana" and the "Sun Belt", and what do both describe?',
    a: 'Corridors of dense economic activity — in Europe and the United States',
    note: 'Economies clump. Naming the clump is most of what economic geography does.',
  },
  {
    id: 'g043',
    theme: 'geography',
    q: 'Why does Norway have such an enormous coastline for its size?',
    a: 'Fjords — glacially carved inlets',
    note: 'Over 100,000 km including islands. Coastline length depends entirely on the ruler you measure with.',
  },
  {
    id: 'g044',
    theme: 'geography',
    q: 'What is the "coastline paradox"?',
    a: 'The measured length grows without limit as the measuring unit shrinks',
    note: 'Mandelbrot’s question, "How long is the coast of Britain?", is where fractals came from.',
  },
  {
    id: 'g045',
    theme: 'geography',
    q: 'Why are there two countries on the island of Hispaniola with such different fortunes?',
    a: 'Different colonial powers, different economies, and severe deforestation on one side',
    note: 'The border is visible from the air as a line between forest and bare hillside.',
  },
  {
    id: 'g046',
    theme: 'geography',
    q: 'What makes the Great Rift Valley significant to human history as well as geology?',
    a: 'Much of the earliest hominid fossil record comes from it',
    note: 'Rifting exposes old layers. Geology decides where palaeontology can look.',
  },
  {
    id: 'g047',
    theme: 'geography',
    q: 'Why does Greenland look so enormous on most world maps?',
    a: 'Mercator distortion at high latitudes',
    note: 'It looks the size of Africa and is about a fourteenth of it.',
  },
  {
    id: 'g048',
    theme: 'geography',
    q: 'What is a "monsoon", and why is calling it "the rainy season" only half right?',
    a: 'A seasonal reversal of wind direction — the rain is a consequence',
    note: 'The word is from Arabic for season. There is a dry monsoon too, which nobody mentions.',
  },
  {
    id: 'g049',
    theme: 'geography',
    q: 'Why is Mount Everest still growing, and by roughly how much?',
    a: 'India is still colliding with Asia — a few millimetres a year',
    note: 'Partly offset by erosion. Earthquakes can change the height in either direction overnight.',
  },
  {
    id: 'g050',
    theme: 'geography',
    q: 'What do Switzerland, Bolivia and Nepal have in common that shapes their entire economies?',
    a: 'Mountainous and landlocked',
    note: 'Switzerland turned it into an advantage: defensible, neutral, and expensive to invade.',
  },
  {
    id: 'g051',
    theme: 'geography',
    q: 'Why do the Great Lakes not freeze completely in winter, despite the temperatures?',
    a: 'They are deep, and the volume of water stores enormous heat',
    note: 'They also generate their own snow: cold air over warm water is a lake-effect blizzard machine.',
  },
  {
    id: 'g052',
    theme: 'geography',
    q: 'What is the International Date Line’s most obvious feature, and why is it not straight?',
    a: 'It zigzags — to keep island groups and countries on one date',
    note: 'Kiribati moved it east in 1995 so the whole country shared a day.',
  },
  {
    id: 'g053',
    theme: 'geography',
    q: 'Why is Iceland growing wider every year?',
    a: 'It straddles a spreading ridge — the plates are pulling apart',
    note: 'About 2 cm a year. You can walk between two continents in Þingvellir.',
  },
  {
    id: 'g054',
    theme: 'geography',
    q: 'What single crop explains the location of most large cities in the Nile valley for four thousand years?',
    a: 'Grain — grown on the annual flood silt',
    note: 'The Aswan Dam ended the flood, and Egypt now imports fertiliser to replace it.',
  },
  {
    id: 'g055',
    theme: 'geography',
    q: 'Why does the Mississippi keep trying to change course, and what is stopping it?',
    a: 'A shorter route to the sea exists — enormous engineering holds it',
    note: 'The Old River Control Structure. If it ever fails, New Orleans loses its river.',
  },
  {
    id: 'g056',
    theme: 'geography',
    q: 'What is the reason so many Pacific island nations are extremely vulnerable to sea level rise beyond the obvious?',
    a: 'Salt water contaminates their fresh groundwater long before land is lost',
    note: 'They become uninhabitable well above the waterline.',
  },
  {
    id: 'g057',
    theme: 'geography',
    q: 'Why is Antarctica a desert?',
    a: 'It has extremely low precipitation',
    note: 'The interior gets less than the Sahara. A desert is about rainfall, not temperature.',
  },
  {
    id: 'g058',
    theme: 'geography',
    q: 'What is the "Wallace Line", and what does it separate?',
    a: 'A faunal boundary in Indonesia between Asian and Australian species',
    note: 'The islands either side look identical and the animals are entirely different. Deep water kept them apart.',
  },
  {
    id: 'g059',
    theme: 'geography',
    q: 'Why do most of the world’s largest cities sit within a few hundred kilometres of a coast?',
    a: 'Shipping is by far the cheapest way to move goods',
    note: 'Still true. A container ship moves a tonne a thousand kilometres for pennies.',
  },
  {
    id: 'g060',
    theme: 'geography',
    q: 'What happened to the Zuiderzee, and what does the Netherlands call it now?',
    a: 'It was dammed and became the freshwater IJsselmeer',
    note: 'A sea turned into a lake by decision. Some of it was then turned into a province.',
  },
  {
    id: 'g061',
    theme: 'geography',
    q: 'Why are Norway, Sweden and Finland shaped as they are relative to the Baltic?',
    a: 'Glacial scouring and land still rebounding after the ice',
    note: 'Parts of the Gulf of Bothnia rise nearly a centimetre a year. New land appears without reclamation.',
  },
  {
    id: 'g062',
    theme: 'geography',
    q: 'What is unusual about the border between Belgium and the Netherlands at Baarle?',
    a: 'Dozens of enclaves and counter-enclaves, some running through houses',
    note: 'The front door decides which country you live in. Some houses have two.',
  },
  {
    id: 'g063',
    theme: 'geography',
    q: 'Why is the Strait of Malacca so significant, and what has been built partly to bypass it?',
    a: 'A quarter of world trade passes it — pipelines and ports across Myanmar and Pakistan',
    note: 'A chokepoint that narrow is a strategic problem for anybody dependent on it.',
  },
  {
    id: 'g064',
    theme: 'geography',
    q: 'What single feature of the Great Barrier Reef makes it visible from orbit?',
    a: 'Its length — over 2,300 km',
    note: 'It is not one reef but nearly three thousand, built by animals over thousands of years.',
  },
  {
    id: 'g065',
    theme: 'geography',
    q: 'Why does Egypt have essentially all of its population in about 5% of its area?',
    a: 'Everything else is desert — they live along the Nile',
    note: 'At night from orbit Egypt is a bright line with a delta on the end and nothing else.',
  },
  {
    id: 'g066',
    theme: 'geography',
    q: 'What is a "fall line", and why did so many American cities grow along one?',
    a: 'Where rivers drop off a plateau — the head of navigation and a source of water power',
    note: 'Richmond, Raleigh, Philadelphia, Trenton. A line of cities drawn by geology.',
  },
  {
    id: 'g067',
    theme: 'geography',
    q: 'Why is the Bering Strait significant to human prehistory?',
    a: 'Lower sea levels made it dry land — the route into the Americas',
    note: 'Beringia was not a bridge but a wide subcontinent, inhabited for thousands of years.',
  },
  {
    id: 'g068',
    theme: 'geography',
    q: 'What does the existence of coal in Antarctica tell you?',
    a: 'It was once forested, and much closer to the equator',
    note: 'Continental drift. The fossils were among the earliest evidence for it.',
  },
  {
    id: 'g069',
    theme: 'geography',
    q: 'Why is Lake Baikal so important to fresh water, and what makes it unusual?',
    a: 'It holds about a fifth of the world’s unfrozen fresh water — it is extremely deep and very old',
    note: 'Over 1,600 metres deep and around 25 million years old, with species found nowhere else.',
  },
  {
    id: 'g070',
    theme: 'geography',
    q: 'What is the reason a great many national borders in South America follow watersheds?',
    a: 'Ridges were the easiest thing to agree on and to identify',
    note: 'Rivers move; mountain ridges do not. Border treaties prefer things that stay put.',
  },
  {
    id: 'g071',
    theme: 'geography',
    q: 'Why did the Suez Canal’s opening in 1869 hurt some ports badly?',
    a: 'It made the Cape route obsolete for Europe–Asia trade',
    note: 'Cape Town’s traffic collapsed. Infrastructure elsewhere can be the thing that ruins you.',
  },
  {
    id: 'g072',
    theme: 'geography',
    q: 'What is the "Anthropocene", and what is the argument against declaring it?',
    a: 'A proposed epoch defined by human impact — geologists disagree on a start marker',
    note: 'Candidates include nuclear fallout in 1945 and the Columbian exchange. The stratigraphic committee declined it.',
  },
  {
    id: 'g073',
    theme: 'geography',
    q: 'Why is there a large sand dune field in the middle of Brazil that fills with lagoons?',
    a: 'Rain falls on impermeable rock beneath the dunes',
    note: 'The Lençóis Maranhenses. A desert-shaped landscape that gets 1,600 mm of rain a year.',
  },
  {
    id: 'g074',
    theme: 'geography',
    q: 'What geographic accident made Britain’s Industrial Revolution possible in the way it happened?',
    a: 'Coal and iron close together, near water transport',
    note: 'Coal that has to be carried far is coal that is not worth burning. Proximity decided which country went first.',
  },
  {
    id: 'g075',
    theme: 'geography',
    q: 'Why is Tokyo the largest metropolitan area in the world despite Japan’s shrinking population?',
    a: 'Internal migration keeps concentrating there',
    note: 'Rural Japan is emptying into one bay. National decline and metropolitan growth at the same time.',
  },
  {
    id: 'g076',
    theme: 'geography',
    q: 'What is the Ogallala Aquifer, and why is it a slow-motion crisis?',
    a: 'A vast fossil aquifer under the US plains — it is being drawn down far faster than it recharges',
    note: 'Recharge takes millennia. It is mining water, not harvesting it.',
  },
  {
    id: 'g077',
    theme: 'geography',
    q: 'Why does Chile administer Easter Island, thousands of kilometres away?',
    a: 'It annexed it in 1888',
    note: 'The island is one of the most isolated inhabited places on earth — nearest neighbour over 2,000 km away.',
  },
  {
    id: 'g078',
    theme: 'geography',
    q: 'What is unusual about the Danube among European rivers, politically?',
    a: 'It flows through or borders ten countries',
    note: 'More than any other river in the world. It has needed international commissions since 1856.',
  },
  {
    id: 'g079',
    theme: 'geography',
    q: 'Why is the Mediterranean so salty compared to the Atlantic?',
    a: 'High evaporation and a narrow connection',
    note: 'Water flows in at the surface and out below, saltier. The exchange is slow.',
  },
  {
    id: 'g080',
    theme: 'geography',
    q: 'What makes a city "primate" in geography, and give an example?',
    a: 'It dominates its country disproportionately — Paris, Bangkok, Buenos Aires',
    note: 'Often a legacy of centralised administration or colonial ports.',
  },
  {
    id: 'g081',
    theme: 'geography',
    q: 'Why did New York overtake Boston and Philadelphia in the nineteenth century?',
    a: 'The Erie Canal gave it the interior',
    note: 'A ditch to the Great Lakes made a harbour into a continental gateway.',
  },
  {
    id: 'g082',
    theme: 'geography',
    q: 'What single feature makes the Bay of Fundy famous, and why is it so extreme there?',
    a: 'The tidal range — the bay’s shape resonates with the tide',
    note: 'Up to sixteen metres. It is a bathtub sloshing at exactly the right frequency.',
  },
  {
    id: 'g083',
    theme: 'geography',
    q: 'Why do so many place names in England end in "-chester" or "-caster"?',
    a: 'From Latin "castrum" — a Roman fort was there',
    note: 'A map of them is a map of Roman military occupation, still legible.',
  },
  {
    id: 'g084',
    theme: 'geography',
    q: 'What is the reason volcanic soils are so fertile?',
    a: 'They are rich in minerals and weather quickly',
    note: 'Which is why people farm the slopes of active volcanoes, knowing exactly what they are doing.',
  },
  {
    id: 'g085',
    theme: 'geography',
    q: 'Why is Kaliningrad an exclave of Russia, and what was it before?',
    a: 'It was East Prussia — annexed in 1945',
    note: 'Königsberg, and Kant’s city. It is now separated from Russia by two EU members.',
  },
  {
    id: 'g086',
    theme: 'geography',
    q: 'What does the phrase "the Roof of the World" refer to, and why the name?',
    a: 'The Pamir plateau (and by extension Tibet) — extreme average altitude',
    note: 'Tibet averages over 4,500 metres. Not a peak but an entire region above most mountains.',
  },
  {
    id: 'g087',
    theme: 'geography',
    q: 'Why do rivers in the northern hemisphere often erode their right banks more?',
    a: 'The Coriolis effect, slightly — though channel shape dominates',
    note: 'Baer’s law. Real, measurable, and much smaller than most textbooks imply.',
  },
  {
    id: 'g088',
    theme: 'geography',
    q: 'What is a "megacity", and roughly how many are there now?',
    a: 'Over ten million people — around thirty and rising',
    note: 'In 1950 there were two: New York and Tokyo.',
  },
  {
    id: 'g089',
    theme: 'geography',
    q: 'Why is the Congo river’s mouth unusual among great rivers?',
    a: 'It has no delta — a deep submarine canyon carries the sediment away',
    note: 'The canyon extends hundreds of kilometres out to sea. The river cut it during lower sea levels.',
  },
  {
    id: 'g090',
    theme: 'geography',
    q: 'What is the reason there is a country called Guinea, another called Equatorial Guinea, another called Guinea-Bissau and a Papua New Guinea?',
    a: 'European sailors reused a vague regional name repeatedly',
    note: 'And the currency, the guinea, was named after the gold that came from the first one.',
  },
  {
    id: 'g091',
    theme: 'geography',
    q: 'Why can two places on the same latitude have completely different climates?',
    a: 'Ocean currents, altitude, and continentality',
    note: 'Coastal places have mild ranges; the middle of a continent swings enormously.',
  },
  {
    id: 'g092',
    theme: 'geography',
    q: 'What single geographical fact made Constantinople defensible for a thousand years?',
    a: 'Water on three sides, with land walls across the fourth',
    note: 'It fell when artillery finally outmatched the walls, not when anyone outflanked them.',
  },
  {
    id: 'g093',
    theme: 'geography',
    q: 'Why is Bhutan’s measure of national success unusual?',
    a: 'It uses Gross National Happiness alongside economic output',
    note: 'It is a real index with survey instruments, not a slogan, though it is often quoted as one.',
  },
  {
    id: 'g094',
    theme: 'geography',
    q: 'What does the existence of Mount Kilimanjaro’s glaciers, so close to the equator, depend on?',
    a: 'Altitude alone',
    note: 'They have lost most of their volume in a century and are expected to go entirely.',
  },
  {
    id: 'g095',
    theme: 'geography',
    q: 'Why is the North Sea so shallow, and what was it during the last ice age?',
    a: 'It is flooded continental shelf — it was dry land, Doggerland',
    note: 'Fishing boats still bring up mammoth bones and Mesolithic tools.',
  },
  {
    id: 'g096',
    theme: 'geography',
    q: 'What makes an "oxbow lake", and what does its existence tell you about the river beside it?',
    a: 'A cut-off meander — the river has moved',
    note: 'Rivers leave their own history lying beside them, which is unusual among landscape features.',
  },
  {
    id: 'g097',
    theme: 'geography',
    q: 'Why do the Faroe Islands, Iceland and parts of Norway share so much place-name vocabulary?',
    a: 'All were settled by Norse speakers',
    note: '"-fjord", "-vik", "-ey". Language is the most durable colonial artefact there is.',
  },
  {
    id: 'g098',
    theme: 'geography',
    q: 'What is the practical consequence of the fact that a degree of longitude shrinks towards the poles while a degree of latitude does not?',
    a: 'Grid squares are not square, and navigation must account for it',
    note: 'At 60° north, a degree of longitude is half its equatorial width.',
  },
  {
    id: 'g099',
    theme: 'geography',
    q: 'Why is the Salar de Uyuni used to calibrate satellites?',
    a: 'It is enormous, extremely flat and highly reflective',
    note: 'Flat to within a metre over 10,000 km². When wet it becomes the largest mirror on earth.',
  },
  {
    id: 'g100',
    theme: 'geography',
    q: 'What single question is hardest to answer about how many countries there are in the world, and why?',
    a: 'Which entities count — recognition is political, not geographic',
    note: 'The UN has 193 members. Depending on your criteria the answer is anywhere from 193 to over 200.',
  },
]
