/**
 * History — the shape of an event rather than its date.
 *
 * Dates are the worst possible question: you know one or you do not, and knowing one proves
 * nothing. Everything here is a *why* or a *what happened next*, answerable by somebody who
 * has never opened a history book but is prepared to think about what people would plausibly
 * have done.
 */
import type { Question } from '../types'

export const HISTORY: readonly Question[] = [
  {
    id: 'h001',
    theme: 'history',
    q: 'Roman roads were built with a pronounced hump along the middle. What was it for?',
    a: 'Drainage',
    note: 'Water is what destroys a road. Two thousand years later we still camber them for the same reason.',
  },
  {
    id: 'h002',
    theme: 'history',
    q: 'Medieval castle spiral staircases almost always turn the same way going up. Which way, and why?',
    a: 'Clockwise — it favours a right-handed defender above',
    note: 'The defender’s sword arm is free; the attacker’s is against the newel post. Left-handed families sometimes built theirs the other way.',
  },
  {
    id: 'h003',
    theme: 'history',
    q: 'Why did so many early modern European cities have a law about the width of a street relative to building height?',
    a: 'Fire — and light',
    note: 'A street narrower than the buildings were tall would carry a fire across it. London learned this in 1666.',
  },
  {
    id: 'h004',
    theme: 'history',
    q: 'The Rosetta Stone was useful because it carried the same text three times. What made the Greek version the key?',
    a: 'Scholars could already read Greek',
    note: 'It was a fairly dull tax decree. Its content mattered far less than its redundancy.',
  },
  {
    id: 'h005',
    theme: 'history',
    q: 'Why were the first passenger lifts fitted with a device whose main purpose was to be demonstrated publicly rather than used?',
    a: 'The safety brake — people would not ride without seeing it work',
    note: 'Elisha Otis cut the rope himself at the 1854 World’s Fair. He sold the fear, then the lift.',
  },
  {
    id: 'h006',
    theme: 'history',
    q: 'What did the Great Fire of London do to the city’s rat population, and what did that arguably do to the plague?',
    a: 'Destroyed much of the habitat — plague did not return on the same scale',
    note: 'Historians argue about causation. The rebuilding in brick rather than timber probably mattered more.',
  },
  {
    id: 'h007',
    theme: 'history',
    q: 'Why did nineteenth-century British sailors get a nickname from a fruit, and what were they actually issued?',
    a: 'Limes — for scurvy',
    note: 'Lemons worked better and were dropped for cost. Lime juice has less vitamin C, and scurvy quietly returned.',
  },
  {
    id: 'h008',
    theme: 'history',
    q: 'The Berlin Wall went up almost overnight in 1961. What had been happening in the preceding months that made it urgent?',
    a: 'Mass emigration west, especially of skilled workers',
    note: 'Around 3.5 million had left. The state was losing precisely the people it could least replace.',
  },
  {
    id: 'h009',
    theme: 'history',
    q: 'What was the practical reason Roman legionaries carried a spade as standard equipment?',
    a: 'They built a fortified camp every night',
    note: 'Ditch, rampart, palisade, every evening on the march. The army was an engineering corps that also fought.',
  },
  {
    id: 'h010',
    theme: 'history',
    q: 'Why is the Bayeux Tapestry not a tapestry?',
    a: 'It is embroidery — stitched onto cloth, not woven',
    note: 'Seventy metres of it. The name has been wrong for nine hundred years and is not going to change.',
  },
  {
    id: 'h011',
    theme: 'history',
    q: 'What did the invention of canning precede by nearly fifty years, causing considerable difficulty?',
    a: 'The can opener',
    note: 'Early cans said "cut round the top with a chisel and hammer". They were for the army, which had both.',
  },
  {
    id: 'h012',
    theme: 'history',
    q: 'Why did the Dutch tulip market of the 1630s collapse so completely, in terms of what was actually being traded by the end?',
    a: 'Contracts for future bulbs, not bulbs',
    note: 'You could not deliver in winter, so people traded the promise. When the promises stopped being honoured there was nothing underneath.',
  },
  {
    id: 'h013',
    theme: 'history',
    q: 'The Titanic carried lifeboats for about half those aboard, and was within the law. Why did the law allow it?',
    a: 'Lifeboat requirements were set by tonnage, and capped',
    note: 'The rules assumed boats would ferry people to a nearby rescuing ship, not evacuate everyone at once.',
  },
  {
    id: 'h014',
    theme: 'history',
    q: 'What did medieval European guilds control that made them enormously powerful, beyond simply setting prices?',
    a: 'Who was allowed to be trained',
    note: 'Control the apprenticeships and you control the supply of everybody who can ever do the job.',
  },
  {
    id: 'h015',
    theme: 'history',
    q: 'Why did the Pony Express last only eighteen months?',
    a: 'The transcontinental telegraph reached the coast',
    note: 'It is remembered as an institution. It was a start-up that got disrupted before its second birthday.',
  },
  {
    id: 'h016',
    theme: 'history',
    q: 'What single change to the design of a plough transformed agriculture in northern Europe, and why did the Mediterranean not need it?',
    a: 'A heavy mouldboard that turned the soil — southern soils were lighter',
    note: 'Wet clay defeats a scratch plough. The heavy plough opened land nobody could previously farm.',
  },
  {
    id: 'h017',
    theme: 'history',
    q: 'The Statue of Liberty is a particular colour that its designer never saw. Why?',
    a: 'The copper oxidised over about thirty years',
    note: 'It arrived the colour of a new penny. Proposals to clean it in the 1900s were rejected after public objection.',
  },
  {
    id: 'h018',
    theme: 'history',
    q: 'Why did so many ancient civilisations independently arrive at a base-60 number system for time and angles?',
    a: 'Sixty divides evenly by a great many numbers',
    note: '2, 3, 4, 5, 6, 10, 12, 15, 20, 30. Before fractions were easy, divisibility was everything.',
  },
  {
    id: 'h019',
    theme: 'history',
    q: 'What did the Spanish Armada mostly lose to, according to modern historians?',
    a: 'Weather and logistics rather than battle',
    note: 'The fighting was inconclusive. The journey home round Scotland and Ireland destroyed the fleet.',
  },
  {
    id: 'h020',
    theme: 'history',
    q: 'Why were early photographic portraits taken with a hidden metal stand behind the sitter?',
    a: 'Exposures were long — it held the head still',
    note: 'It is also why nobody smiles: holding a grin for thirty seconds looks worse than holding a neutral face.',
  },
  {
    id: 'h021',
    theme: 'history',
    q: 'The Suez Canal has no locks. What geographical fact makes that possible, and what did engineers wrongly believe beforehand?',
    a: 'The two seas are at effectively the same level — they believed there was a large difference',
    note: 'A bad survey under Napoleon reported a ten-metre difference and delayed the project by decades.',
  },
  {
    id: 'h022',
    theme: 'history',
    q: 'What was the practical purpose of the enormous wigs worn by seventeenth-century European men?',
    a: 'Covering hair loss, largely from disease',
    note: 'Louis XIV started going bald at seventeen. The court copied him, and then everybody copied the court.',
  },
  {
    id: 'h023',
    theme: 'history',
    q: 'Why did the introduction of the mechanical clock change the working day more than it changed the measurement of time?',
    a: 'Hours became equal — they had varied with the seasons',
    note: 'A "daylight hour" in June was much longer than one in December. The clock abolished that and made shifts possible.',
  },
  {
    id: 'h024',
    theme: 'history',
    q: 'What did Gutenberg’s press borrow from an existing industry, and which one?',
    a: 'The screw press — from winemaking (or papermaking)',
    note: 'His real invention was movable metal type and the alloy for casting it, not the press itself.',
  },
  {
    id: 'h025',
    theme: 'history',
    q: 'Why did the Roman empire’s roads outlast its aqueducts in most places?',
    a: 'A damaged road is still a road; a damaged aqueduct delivers nothing',
    note: 'Networks that degrade gracefully survive. Ones that need every link intact do not.',
  },
  {
    id: 'h026',
    theme: 'history',
    q: 'What was unusual about the way the Vikings navigated open ocean without a compass, according to one much-debated theory?',
    a: 'A crystal that polarises light, to find the sun through cloud',
    note: 'The "sunstone", probably Iceland spar. Mentioned in the sagas and demonstrated to work; never found on a ship.',
  },
  {
    id: 'h027',
    theme: 'history',
    q: 'Why were early banknotes issued by goldsmiths rather than by governments?',
    a: 'They already held people’s gold and issued receipts for it',
    note: 'The receipt started circulating instead of the gold, and banking was invented by accident.',
  },
  {
    id: 'h028',
    theme: 'history',
    q: 'The Marshall Plan gave money to countries including former enemies. What was the condition attached that mattered most economically?',
    a: 'They had to cooperate with each other on how to spend it',
    note: 'Forcing joint planning is arguably the seed of the European Union. The money was the lever, not the point.',
  },
  {
    id: 'h029',
    theme: 'history',
    q: 'What did the Domesday Book actually record, and why did it earn a name meaning "day of judgement"?',
    a: 'Who owned what, for tax — its findings were final and could not be appealed',
    note: 'Contemporaries named it after the last judgement because there was no arguing with it either.',
  },
  {
    id: 'h030',
    theme: 'history',
    q: 'Why did the Panama Canal succeed after the French attempt failed, in terms of medicine rather than engineering?',
    a: 'Mosquito control — yellow fever and malaria',
    note: 'The French lost more than twenty thousand workers. The Americans arrived knowing what carried the disease.',
  },
  {
    id: 'h031',
    theme: 'history',
    q: 'What was the point of a medieval "murder hole" in a castle gatehouse, besides the obvious?',
    a: 'Pouring water to put out fires set against the gate',
    note: 'The gate was the weak point and burning it was the standard attack. Boiling oil is mostly cinema.',
  },
  {
    id: 'h032',
    theme: 'history',
    q: 'Why did the Chinese invention of paper money precede Europe’s by six hundred years and then be abandoned?',
    a: 'Runaway inflation from over-issue',
    note: 'The Ming eventually banned it. Nothing about the lesson has changed since.',
  },
  {
    id: 'h033',
    theme: 'history',
    q: 'What single innovation allowed Gothic cathedrals to have such large windows?',
    a: 'The flying buttress — taking the roof’s outward thrust outside the walls',
    note: 'Once the wall is not holding the roof up, it can be mostly glass.',
  },
  {
    id: 'h034',
    theme: 'history',
    q: 'The 1919 Treaty of Versailles included a clause that Germany objected to more than the money. What was it?',
    a: 'The war guilt clause',
    note: 'Article 231. Legally it was the basis for reparations; politically it was the humiliation people remembered.',
  },
  {
    id: 'h035',
    theme: 'history',
    q: 'Why were early railway timetables the reason Britain adopted a single national time?',
    a: 'Local solar time varied by town and made schedules impossible',
    note: 'Bristol was ten minutes behind London. Railways imposed "railway time" and the country followed.',
  },
  {
    id: 'h036',
    theme: 'history',
    q: 'What did the Ottoman Empire do with the sons of conquered Christian families that made its army unusual?',
    a: 'Recruited and trained them as an elite corps loyal only to the sultan',
    note: 'The devşirme, and the Janissaries. Loyalty by isolation: no family, no faction, no land.',
  },
  {
    id: 'h037',
    theme: 'history',
    q: 'Why did nineteenth-century hat makers become a byword for madness?',
    a: 'Mercury was used to treat felt',
    note: 'Chronic mercury poisoning causes tremor and irritability. The Hatter is a medical observation.',
  },
  {
    id: 'h038',
    theme: 'history',
    q: 'What was the "Columbian Exchange", and which direction did the potato travel?',
    a: 'The transfer of crops, animals and disease across the Atlantic — potato went east',
    note: 'Potatoes and maize probably did more to grow Europe’s population than anything else in three centuries.',
  },
  {
    id: 'h039',
    theme: 'history',
    q: 'Why did the Library of Alexandria’s destruction take centuries rather than one famous fire?',
    a: 'It declined through repeated damage, funding loss and neglect',
    note: 'The single dramatic burning is a story. Institutions usually die of budget cuts.',
  },
  {
    id: 'h040',
    theme: 'history',
    q: 'What did the introduction of the stirrup change about warfare, according to the classic argument?',
    a: 'It made the mounted lance charge possible — and with it a warrior aristocracy',
    note: 'Lynn White’s thesis. Much disputed, still the most interesting claim about a piece of leather ever made.',
  },
  {
    id: 'h041',
    theme: 'history',
    q: 'Why is the Magna Carta’s importance mostly retrospective?',
    a: 'It was annulled within weeks and was about baronial privilege, not general liberty',
    note: 'Its afterlife in the seventeenth century made it a charter of rights. Its authors would be baffled.',
  },
  {
    id: 'h042',
    theme: 'history',
    q: 'What made the Antikythera mechanism so startling when it was understood?',
    a: 'Gearing of a complexity not seen again for over a thousand years',
    note: 'A Greek astronomical calculator from about 100 BC, found in a shipwreck by sponge divers.',
  },
  {
    id: 'h043',
    theme: 'history',
    q: 'Why did the Black Death arguably improve the position of surviving European peasants?',
    a: 'Labour became scarce, so wages rose and obligations weakened',
    note: 'Governments passed laws freezing wages. They were widely ignored, which tells you who had the leverage.',
  },
  {
    id: 'h044',
    theme: 'history',
    q: 'The Wright brothers ran a business before aviation. Which, and how did it help?',
    a: 'A bicycle shop — balance, light structures, and machining',
    note: 'They understood that an aircraft, like a bicycle, must be actively controlled rather than inherently stable.',
  },
  {
    id: 'h045',
    theme: 'history',
    q: 'Why did the Republic of Venice keep its glassmakers on a single island?',
    a: 'To contain fire risk and to stop the secrets leaving',
    note: 'Murano. Leaving without permission could be treated as a capital offence.',
  },
  {
    id: 'h046',
    theme: 'history',
    q: 'What was the practical effect of the Enclosure Acts on rural England, in one sentence?',
    a: 'Common land became private, and the people who used it moved to the towns',
    note: 'It supplied the labour for the factories. One policy sits underneath the whole Industrial Revolution.',
  },
  {
    id: 'h047',
    theme: 'history',
    q: 'Why did Napoleon’s army fail in Russia, and what killed most of the soldiers?',
    a: 'Disease, hunger and cold rather than combat',
    note: 'Typhus especially. Minard’s famous chart of the retreat is a graph of an army evaporating.',
  },
  {
    id: 'h048',
    theme: 'history',
    q: 'What did the Code of Hammurabi do that was genuinely new, beyond listing punishments?',
    a: 'It was published, so people could know the law in advance',
    note: 'Carved on a stele in a public place. Predictability is arguably the whole invention of law.',
  },
  {
    id: 'h049',
    theme: 'history',
    q: 'Why did the Great Wall of China fail repeatedly as a defence, and what was it actually good at?',
    a: 'It was breached or bypassed; it worked as a control on trade and movement',
    note: 'Walls rarely stop armies. They are extremely good at taxing everybody who crosses.',
  },
  {
    id: 'h050',
    theme: 'history',
    q: 'What was unusual about the crew of Magellan’s expedition by the time it returned?',
    a: 'Eighteen of about 270 came back, and Magellan was not among them',
    note: 'Elcano completed it. The first circumnavigation is named after a man who died two-thirds of the way round.',
  },
  {
    id: 'h051',
    theme: 'history',
    q: 'Why did the invention of barbed wire matter so much to the American West?',
    a: 'It made fencing treeless plains affordable, ending open-range ranching',
    note: 'A few strands of cheap steel redrew the map of a continent within twenty years.',
  },
  {
    id: 'h052',
    theme: 'history',
    q: 'What did the Rosetta-like breakthrough in reading Linear B reveal that shocked scholars?',
    a: 'It was Greek — much older Greek than anyone expected',
    note: 'Ventris was an architect, not a classicist, and had assumed it would be Etruscan.',
  },
  {
    id: 'h053',
    theme: 'history',
    q: 'Why were nineteenth-century lighthouse keepers often required to be married couples?',
    a: 'It provided a second keeper cheaply, and stability',
    note: 'Several famous rescues were by the keeper’s daughter or wife, because they were the other half of the staff.',
  },
  {
    id: 'h054',
    theme: 'history',
    q: 'The Hundred Years’ War lasted 116 years. What does that tell you about how it was actually fought?',
    a: 'It was a series of campaigns with long truces, not continuous war',
    note: 'Named centuries later. Contemporaries did not know they were in one war.',
  },
  {
    id: 'h055',
    theme: 'history',
    q: 'Why did the Aztec capital need an aqueduct when it stood in the middle of a lake?',
    a: 'The lake was salty',
    note: 'Tenochtitlan was an island in a saline lake. Fresh water came from springs on the mainland.',
  },
  {
    id: 'h056',
    theme: 'history',
    q: 'What was the "Defenestration of Prague", and why is it notable that it happened more than once?',
    a: 'Officials thrown out of a window — Bohemian politics did it at least twice',
    note: 'The 1618 one started the Thirty Years’ War. The victims survived, landing in a dung heap.',
  },
  {
    id: 'h057',
    theme: 'history',
    q: 'Why did European monarchs so often marry their cousins, and what was the eventual medical consequence?',
    a: 'To consolidate alliances and claims — inherited disease became common',
    note: 'The Habsburg jaw, and haemophilia through Victoria’s descendants across three royal houses.',
  },
  {
    id: 'h058',
    theme: 'history',
    q: 'What did the printing press do to the price of a book, roughly, in its first fifty years?',
    a: 'Cut it by something like an order of magnitude',
    note: 'A manuscript Bible cost a year’s wages. By 1500 there were perhaps twenty million printed books in Europe.',
  },
  {
    id: 'h059',
    theme: 'history',
    q: 'Why is 1492 significant twice over in Spanish history?',
    a: 'Columbus sailed, and Granada fell — ending the Reconquista',
    note: 'Also the expulsion of the Jews. It was an extraordinarily consequential twelve months.',
  },
  {
    id: 'h060',
    theme: 'history',
    q: 'What was the practical function of a Roman "triumph", beyond celebration?',
    a: 'Political theatre that also distributed loot and legitimised the general',
    note: 'A slave was said to ride behind whispering that he was mortal. Probably later invention, but a good detail.',
  },
  {
    id: 'h061',
    theme: 'history',
    q: 'Why did the discovery of longitude take so much longer than latitude?',
    a: 'Latitude comes from the sun’s angle; longitude needs an accurate clock',
    note: 'You must know the time somewhere else. Harrison spent forty years building a clock that worked at sea.',
  },
  {
    id: 'h062',
    theme: 'history',
    q: 'What did the Irish Famine reveal about the danger of relying on a single crop variety?',
    a: 'A monoculture has no genetic resistance — one blight took everything',
    note: 'Most Irish potatoes were one variety, the lumper. Diversity is insurance, and there was none.',
  },
  {
    id: 'h063',
    theme: 'history',
    q: 'Why did the Roman calendar need Julius Caesar to fix it, and what had gone wrong?',
    a: 'Priests inserted extra months politically, and it had drifted by months',
    note: '46 BC was 445 days long, to reset it. They called it the year of confusion.',
  },
  {
    id: 'h064',
    theme: 'history',
    q: 'What was the main reason the Concorde was retired, and why is it not simply the crash?',
    a: 'It was never economic — the crash finished a business already failing',
    note: 'Fuel, noise restrictions and a market of about a hundred people who could afford it.',
  },
  {
    id: 'h065',
    theme: 'history',
    q: 'Why did medieval Europe’s universities teach in Latin, and what did that make possible?',
    a: 'A scholar could study anywhere in Europe',
    note: 'A single working language across a continent. The loss of it is why footnotes are still in it.',
  },
  {
    id: 'h066',
    theme: 'history',
    q: 'What did the Zimmermann Telegram propose, and why did its interception matter so much?',
    a: 'A German alliance with Mexico — it helped bring the United States into the war',
    note: 'Britain had broken the code and had to disguise how it knew, which is a whole second story.',
  },
  {
    id: 'h067',
    theme: 'history',
    q: 'Why were the Nuremberg trials legally unprecedented, and what principle did they establish?',
    a: 'Individuals could be tried for state acts — orders are not a defence',
    note: 'Before this, states were responsible and individuals were not. That inversion is the whole of modern international law.',
  },
  {
    id: 'h068',
    theme: 'history',
    q: 'What was so significant about the fact that the Inca had no writing but ran an empire of ten million people?',
    a: 'They administered it with knotted cords — the quipu',
    note: 'Numbers certainly, and possibly more. Much of it remains undeciphered.',
  },
  {
    id: 'h069',
    theme: 'history',
    q: 'Why did the sinking of the Lusitania matter more diplomatically than militarily?',
    a: 'It killed American civilians and shifted public opinion',
    note: 'It also carried munitions, which Germany argued and Britain denied for decades.',
  },
  {
    id: 'h070',
    theme: 'history',
    q: 'What did the Bretton Woods conference fix, and what broke it in 1971?',
    a: 'Currencies to the dollar and the dollar to gold — Nixon ended convertibility',
    note: 'Every floating exchange rate in the world today dates from that announcement.',
  },
  {
    id: 'h071',
    theme: 'history',
    q: 'Why did the Byzantine Empire call itself Roman until 1453?',
    a: 'Because it was — the eastern half never fell',
    note: '"Byzantine" is a name given by later historians. They called themselves Romaioi throughout.',
  },
  {
    id: 'h072',
    theme: 'history',
    q: 'What made the Dutch East India Company different from earlier trading ventures, in a way still with us?',
    a: 'Permanent tradable shares — the first modern joint-stock company',
    note: 'And with it the first stock exchange, and the first speculative bubble in shares.',
  },
  {
    id: 'h073',
    theme: 'history',
    q: 'Why did the Great Depression spread internationally so fast?',
    a: 'The gold standard transmitted deflation, and tariffs collapsed trade',
    note: 'Countries that left gold earliest recovered earliest. That correlation is one of the cleanest in economic history.',
  },
  {
    id: 'h074',
    theme: 'history',
    q: 'What was the point of the Roman "grain dole", politically?',
    a: 'It bought stability in a city that could riot',
    note: 'Bread and circuses is a sneer, but a hungry capital had overthrown governments before.',
  },
  {
    id: 'h075',
    theme: 'history',
    q: 'Why is the Tomb of Tutankhamun so famous when he was a minor pharaoh?',
    a: 'It was the only royal tomb found nearly intact',
    note: 'The great pharaohs’ tombs were all robbed in antiquity. Fame here is a function of luck.',
  },
  {
    id: 'h076',
    theme: 'history',
    q: 'What did the Treaty of Tordesillas divide, and using what?',
    a: 'The non-European world between Spain and Portugal, along a line of longitude',
    note: 'Which is why Brazil speaks Portuguese: the line happened to clip South America.',
  },
  {
    id: 'h077',
    theme: 'history',
    q: 'Why did nineteenth-century Britain build so many follies and ornamental ruins?',
    a: 'Fashion, landscape design, and often to employ labourers during hard times',
    note: 'Several are documented famine relief projects. A useless building that feeds a village is not useless.',
  },
  {
    id: 'h078',
    theme: 'history',
    q: 'What was the significance of the Rosetta of the Americas — the Maya glyphs — being read only in the twentieth century?',
    a: 'It was long assumed they were not real writing',
    note: 'A dominant scholar insisted they were symbolic, and the field lost decades to his authority.',
  },
  {
    id: 'h079',
    theme: 'history',
    q: 'Why did the Soviet Union and the United States both recruit the same German engineers after 1945?',
    a: 'Rocketry — both space programmes were built on captured expertise',
    note: 'Operation Paperclip on one side, and a parallel Soviet effort on the other.',
  },
  {
    id: 'h080',
    theme: 'history',
    q: 'What made the longbow effective, and why did it not survive the arrival of the musket despite being faster to shoot?',
    a: 'Training — a musketeer could be trained in weeks, an archer took years',
    note: 'The bow was better in almost every way except the one that mattered to an army raising conscripts.',
  },
  {
    id: 'h081',
    theme: 'history',
    q: 'Why did the Hanseatic League have no capital, no army and enormous power?',
    a: 'It was a trading network that could collectively boycott a port',
    note: 'Economic sanction as a foreign policy, five hundred years early, run by merchants.',
  },
  {
    id: 'h082',
    theme: 'history',
    q: 'What did the 1854 Broad Street cholera outbreak establish, and what did John Snow do to prove it?',
    a: 'That cholera was waterborne — he mapped the deaths around a pump',
    note: 'He had the handle removed. The map is the founding document of epidemiology.',
  },
  {
    id: 'h083',
    theme: 'history',
    q: 'Why were the pyramids built with a workforce that was probably not enslaved, according to current evidence?',
    a: 'Workers’ villages show good food, medical care and burial with honours',
    note: 'Seasonal labour during the flood, when farming was impossible. Paid in bread and beer.',
  },
  {
    id: 'h084',
    theme: 'history',
    q: 'What was the "Little Ice Age", and name one historical consequence usually attributed to it.',
    a: 'A cold period roughly 1300–1850 — famines, Norse Greenland’s collapse, frost fairs',
    note: 'The Thames froze solid often enough that fairs were held on it.',
  },
  {
    id: 'h085',
    theme: 'history',
    q: 'Why did the Roman use of concrete get forgotten, and what was special about theirs?',
    a: 'It used volcanic ash and got stronger in seawater',
    note: 'Recipes were lost with the western empire. Roman harbour concrete has outlasted modern equivalents.',
  },
  {
    id: 'h086',
    theme: 'history',
    q: 'What did the Rosetta of the sea — the discovery of the Mary Rose — provide that documents could not?',
    a: 'The ordinary equipment and bodies of ordinary sailors',
    note: 'Longbows, shoes, a dog. Written history records decisions; wrecks record everything else.',
  },
  {
    id: 'h087',
    theme: 'history',
    q: 'Why did the introduction of tea in Britain require an entire second industry to make it viable?',
    a: 'Sugar — and with it the plantation economy',
    note: 'Two Asian and Caribbean commodities became the defining British domestic ritual.',
  },
  {
    id: 'h088',
    theme: 'history',
    q: 'What was the practical reason Roman roads were built so straight, and what did they sacrifice for it?',
    a: 'Speed of march and simple surveying — they went over hills rather than round',
    note: 'Terrible for wheeled traffic, excellent for infantry. The design served the army, not the farmer.',
  },
  {
    id: 'h089',
    theme: 'history',
    q: 'Why is the "Renaissance" a contested term among historians?',
    a: 'It implies a dark age before it that the evidence does not support',
    note: 'Coined in the nineteenth century. Medieval Europe was doing rather more than the name allows.',
  },
  {
    id: 'h090',
    theme: 'history',
    q: 'What did the Apollo programme’s guidance computer have less of than a modern washing machine, and how did it manage?',
    a: 'Memory and speed — the software was extraordinarily disciplined',
    note: 'It had a priority scheduler that shed low-priority tasks, which is exactly what saved the first landing.',
  },
  {
    id: 'h091',
    theme: 'history',
    q: 'Why did Prohibition in the United States increase the strength of the alcohol people drank?',
    a: 'Smuggling favours value per volume',
    note: 'The same logic applies to any banned good. It is sometimes called the iron law of prohibition.',
  },
  {
    id: 'h092',
    theme: 'history',
    q: 'What made the Silk Road a road that almost nobody travelled end to end?',
    a: 'Goods were relayed between many traders, not carried the whole way',
    note: 'Which is why Rome had silk and no clear idea where China was.',
  },
  {
    id: 'h093',
    theme: 'history',
    q: 'Why did the Salem witch trials stop when they did?',
    a: 'The accusations reached people too prominent to convict',
    note: 'Including the governor’s wife. Spectral evidence was then excluded and the whole thing collapsed.',
  },
  {
    id: 'h094',
    theme: 'history',
    q: 'What was the "Doomsday Clock" originally measuring, and who set it?',
    a: 'Nuclear risk — atomic scientists from the Manhattan Project',
    note: 'Started in 1947 at seven minutes to midnight. Climate was added to its terms in 2007.',
  },
  {
    id: 'h095',
    theme: 'history',
    q: 'Why was the discovery of the Terracotta Army in 1974 made by farmers rather than archaeologists?',
    a: 'They were digging a well',
    note: 'Around eight thousand figures, no two faces alike, and nobody had recorded that it existed.',
  },
  {
    id: 'h096',
    theme: 'history',
    q: 'What did the Norman conquest do to the English language that is still visible in every formal document?',
    a: 'Doubled the vocabulary — pairs of plain and formal words',
    note: 'Ask/enquire, buy/purchase, freedom/liberty. The Saxon word is nearly always the shorter one.',
  },
  {
    id: 'h097',
    theme: 'history',
    q: 'Why did nineteenth-century cities build sewers before they understood germ theory?',
    a: 'They believed bad smells caused disease — and the sewers worked anyway',
    note: 'Miasma theory was wrong and produced exactly the right public works. Being right for the wrong reason still counts.',
  },
  {
    id: 'h098',
    theme: 'history',
    q: 'What was the significance of the first photograph of the earth from space for the environmental movement?',
    a: 'It showed a single finite object with no borders',
    note: '"Earthrise", 1968. Stewart Brand had been campaigning for NASA to release such a picture for years.',
  },
  {
    id: 'h099',
    theme: 'history',
    q: 'Why did the Rosetta stone end up in London rather than Paris, given that the French found it?',
    a: 'It was surrendered under the terms of a military defeat',
    note: 'The Capitulation of Alexandria, 1801. The French scholars kept their notes, which is how Champollion still won.',
  },
  {
    id: 'h100',
    theme: 'history',
    q: 'What single decision by a Soviet officer in 1983 is credited with preventing a nuclear exchange?',
    a: 'Reporting a satellite warning as a false alarm',
    note: 'Stanislav Petrov. The system showed five missiles; he reasoned that a real attack would not be five.',
  },
]
