/**
 * The natural world — what animals and plants are solving.
 *
 * Every organism is an argument about its environment, so every question here is answerable
 * by asking "what problem would that solve". A table that reasons from the constraint gets
 * there without knowing a single species name.
 */
import type { Question } from '../types'

export const NATURE: readonly Question[] = [
  {
    id: 'n001',
    theme: 'nature',
    q: 'Why are flamingos pink, and what happens to one fed the wrong diet?',
    a: 'Carotenoids from their food — they turn white',
    note: 'Zoos supplement it deliberately. The bird is the colour of what it eats.',
  },
  {
    id: 'n002',
    theme: 'nature',
    q: 'Why do trees lose their leaves in winter, when sunlight is still available?',
    a: 'Water is locked as ice — leaves would lose it faster than roots could replace it',
    note: 'Winter is a drought, not a cold snap, as far as a tree is concerned.',
  },
  {
    id: 'n003',
    theme: 'nature',
    q: 'Why do so many desert animals have very large ears?',
    a: 'To radiate heat',
    note: 'Fennec foxes and jackrabbits. The ear is a radiator with a hearing function attached.',
  },
  {
    id: 'n004',
    theme: 'nature',
    q: 'Why is a polar bear’s fur not white, and what colour is its skin?',
    a: 'The hairs are translucent; the skin is black',
    note: 'It scatters light like snow. The black skin underneath absorbs whatever gets through.',
  },
  {
    id: 'n005',
    theme: 'nature',
    q: 'Why do birds sing most loudly at dawn?',
    a: 'Sound carries best in cool still air, and it is too dark to forage',
    note: 'The dawn chorus is a use of the least productive hour of the day.',
  },
  {
    id: 'n006',
    theme: 'nature',
    q: 'Why do bees make hexagonal cells rather than circles or squares?',
    a: 'Hexagons tile with the least wax for the most volume',
    note: 'They may build round cells that settle into hexagons. Either way, the maths wins.',
  },
  {
    id: 'n007',
    theme: 'nature',
    q: 'Why are there almost no green mammals, when green is the commonest background?',
    a: 'Mammals cannot make green pigment — the sloth cheats with algae',
    note: 'Birds and reptiles do it structurally or chemically. Mammal fur simply cannot.',
  },
  {
    id: 'n008',
    theme: 'nature',
    q: 'Why do leaves turn red and yellow in autumn?',
    a: 'Chlorophyll breaks down and reveals pigments that were there — reds are often newly made',
    note: 'Yellow was always present. Red is usually manufactured on the way out, and nobody is certain why.',
  },
  {
    id: 'n009',
    theme: 'nature',
    q: 'Why can a cat always land on its feet, and what does it need that a person does not have?',
    a: 'A flexible spine and no fixed angular momentum requirement — it twists in two halves',
    note: 'It conserves angular momentum by counter-rotating front and back. It needs no external push at all.',
  },
  {
    id: 'n010',
    theme: 'nature',
    q: 'Why do fish in a shoal all turn at once, without a leader?',
    a: 'Each follows simple local rules about its neighbours',
    note: 'Three rules — separation, alignment, cohesion — reproduce it in simulation exactly.',
  },
  {
    id: 'n011',
    theme: 'nature',
    q: 'Why do so many poisonous animals advertise with bright colours?',
    a: 'A predator must survive to learn — being memorable is the point',
    note: 'Aposematism. It only works if the predator lives, which is why many are unpleasant rather than lethal.',
  },
  {
    id: 'n012',
    theme: 'nature',
    q: 'Why is a tree ring wide in some years and narrow in others, and what does it let us do?',
    a: 'Growth conditions — it gives a datable climate record',
    note: 'Dendrochronology can date a beam to the year, and sometimes to the season it was felled.',
  },
  {
    id: 'n013',
    theme: 'nature',
    q: 'Why do penguins huddle, and what is remarkable about how they take turns?',
    a: 'Heat conservation — they rotate so everyone spends time inside',
    note: 'The huddle moves as a slow wave. Nobody organises it; it emerges from each bird edging inward.',
  },
  {
    id: 'n014',
    theme: 'nature',
    q: 'Why are there no large land predators on most islands?',
    a: 'Not enough prey to support them',
    note: 'Island populations shrink large animals and grow small ones. Both are the same energy argument.',
  },
  {
    id: 'n015',
    theme: 'nature',
    q: 'Why does a chameleon change colour, and what is the usual misconception?',
    a: 'Mood, temperature and signalling — not camouflage, mostly',
    note: 'They do it by moving crystals in their skin, not by pigment. It is structural colour.',
  },
  {
    id: 'n016',
    theme: 'nature',
    q: 'Why do migratory birds fly in a V?',
    a: 'Each bird rides the upwash from the one ahead',
    note: 'They also synchronise wingbeats to catch it. Measured energy savings are substantial.',
  },
  {
    id: 'n017',
    theme: 'nature',
    q: 'Why are cave animals so often blind and colourless?',
    a: 'Eyes and pigment cost energy and give no benefit in the dark',
    note: 'Evolution removes what is not paid for. Loss is as much an adaptation as gain.',
  },
  {
    id: 'n018',
    theme: 'nature',
    q: 'Why does a woodpecker not get concussion?',
    a: 'A small brain tightly packed, short beak, and the forces are mostly linear',
    note: 'Recent work suggests the head acts as a stiff hammer rather than a shock absorber.',
  },
  {
    id: 'n019',
    theme: 'nature',
    q: 'Why do some plants eat insects?',
    a: 'They grow in soil with no nitrogen',
    note: 'They still photosynthesise. The insect is fertiliser, not food.',
  },
  {
    id: 'n020',
    theme: 'nature',
    q: 'Why do elephants have such large ears in Africa and smaller ones in Asia?',
    a: 'Heat — African elephants live in hotter, more open country',
    note: 'The ear is laced with blood vessels. Flapping them can drop the blood temperature by several degrees.',
  },
  {
    id: 'n021',
    theme: 'nature',
    q: 'Why is a hummingbird’s heart rate and metabolism so extreme, and what does it do at night?',
    a: 'Hovering is enormously expensive — it enters torpor',
    note: 'Body temperature drops close to ambient. It effectively hibernates every night.',
  },
  {
    id: 'n022',
    theme: 'nature',
    q: 'Why do so many flowers have ultraviolet patterns invisible to us?',
    a: 'They are landing guides for insects that see UV',
    note: 'Photographed in UV, plain yellow flowers turn out to have bullseyes.',
  },
  {
    id: 'n023',
    theme: 'nature',
    q: 'Why do deciduous trees in a forest all change colour at slightly different times?',
    a: 'Species, age, position and stress all differ',
    note: 'A stressed tree colours early. Autumn colour is partly a map of which trees are struggling.',
  },
  {
    id: 'n024',
    theme: 'nature',
    q: 'Why is a mule sterile, and what does that tell you about horses and donkeys?',
    a: 'Different chromosome numbers — meiosis cannot pair them',
    note: '64 and 62 gives 63. An odd number cannot divide evenly, which ends the line in one generation.',
  },
  {
    id: 'n025',
    theme: 'nature',
    q: 'Why do coral reefs bleach, and what is actually leaving?',
    a: 'The symbiotic algae — expelled under heat stress',
    note: 'The coral is not dead when it bleaches. It is starving, and can recover if the stress ends.',
  },
  {
    id: 'n026',
    theme: 'nature',
    q: 'Why can a gecko walk on glass?',
    a: 'Millions of tiny hairs using van der Waals forces',
    note: 'Not suction, not glue. Molecular attraction, multiplied by an enormous amount of contact area.',
  },
  {
    id: 'n027',
    theme: 'nature',
    q: 'Why do some trees drop branches in drought, apparently damaging themselves?',
    a: 'To reduce water demand',
    note: 'Called cladoptosis or summer branch drop. The tree is amputating to survive.',
  },
  {
    id: 'n028',
    theme: 'nature',
    q: 'Why is a queen bee a queen, genetically speaking?',
    a: 'She is not — she was fed differently as a larva',
    note: 'Royal jelly. Any female larva could have been the queen; the difference is entirely diet.',
  },
  {
    id: 'n029',
    theme: 'nature',
    q: 'Why do owls fly silently, and what is the cost?',
    a: 'Fringed feathers break up turbulence — they are slower and less efficient',
    note: 'Fishing owls, which do not need silence, have lost the fringes entirely.',
  },
  {
    id: 'n030',
    theme: 'nature',
    q: 'Why do so many animals have eyes on the front, and others on the sides?',
    a: 'Front for depth perception when hunting; sides for a wide field when hunted',
    note: '"Eyes in front, born to hunt. Eyes on the side, born to hide." Crude, and mostly right.',
  },
  {
    id: 'n031',
    theme: 'nature',
    q: 'Why is a banana plant not a tree, and what is a banana botanically?',
    a: 'It is a giant herb, and the banana is a berry',
    note: 'The "trunk" is tightly rolled leaf bases. It has no wood at all.',
  },
  {
    id: 'n032',
    theme: 'nature',
    q: 'Why do some seeds only germinate after a fire?',
    a: 'Fire clears competition and the heat or smoke breaks their dormancy',
    note: 'Some cones are sealed with resin that only melts in a fire. The plant is waiting for one.',
  },
  {
    id: 'n033',
    theme: 'nature',
    q: 'Why do most mammals live for roughly the same number of heartbeats?',
    a: 'Metabolic rate scales with size — small animals live fast',
    note: 'Around a billion, very roughly. Humans are a notable outlier, at about three times that.',
  },
  {
    id: 'n034',
    theme: 'nature',
    q: 'Why can a camel go so long without drinking, and what is the fat hump actually for?',
    a: 'Tolerance of dehydration and body temperature swings — the hump is energy storage',
    note: 'Not water. Metabolising fat produces some water but costs oxygen and therefore breath.',
  },
  {
    id: 'n035',
    theme: 'nature',
    q: 'Why do mosquitoes prefer some people to others?',
    a: 'Carbon dioxide, body odour chemistry and skin bacteria',
    note: 'Blood type may matter slightly. What you ate matters much less than folklore suggests.',
  },
  {
    id: 'n036',
    theme: 'nature',
    q: 'Why is a mushroom not a plant?',
    a: 'Fungi do not photosynthesise, and are more closely related to animals',
    note: 'They absorb nutrients from outside. The visible mushroom is the fruit of something much larger underground.',
  },
  {
    id: 'n037',
    theme: 'nature',
    q: 'Why do salmon return to the river they were born in, and how do they find it?',
    a: 'Magnetic navigation at sea, then smell in fresh water',
    note: 'They imprint on the chemical signature of their natal stream as juveniles.',
  },
  {
    id: 'n038',
    theme: 'nature',
    q: 'Why do trees in a windy place grow shorter and thicker?',
    a: 'Mechanical stress triggers thicker growth',
    note: 'Trees in biosphere experiments without wind grew tall and fell over. They need the stress.',
  },
  {
    id: 'n039',
    theme: 'nature',
    q: 'Why is a starfish able to regrow an arm, and what can some do that is more surprising?',
    a: 'They have distributed nervous systems — some regrow the whole animal from one arm',
    note: 'Provided a piece of the central disc goes with it, usually.',
  },
  {
    id: 'n040',
    theme: 'nature',
    q: 'Why do animals in colder climates tend to be larger, within a species?',
    a: 'Lower surface-to-volume ratio conserves heat',
    note: 'Bergmann’s rule. Allen’s rule adds that their extremities get shorter for the same reason.',
  },
  {
    id: 'n041',
    theme: 'nature',
    q: 'Why does a plant grow towards light, mechanically?',
    a: 'A hormone accumulates on the shaded side and elongates those cells',
    note: 'Auxin. The plant does not pull towards the light; the dark side pushes it round.',
  },
  {
    id: 'n042',
    theme: 'nature',
    q: 'Why do so many baby animals have proportionally huge eyes and heads?',
    a: 'It triggers caregiving — and the brain grows before the body',
    note: 'Lorenz called it the baby schema. Cartoon design has exploited it for a century.',
  },
  {
    id: 'n043',
    theme: 'nature',
    q: 'Why can some birds sleep with half their brain at a time?',
    a: 'To keep watch, or to keep flying',
    note: 'Frigatebirds do it in flight. Dolphins do it to keep breathing.',
  },
  {
    id: 'n044',
    theme: 'nature',
    q: 'Why is the giant sequoia’s bark so thick?',
    a: 'Fire protection',
    note: 'Up to 60 cm, and full of tannin rather than resin. The tree is built to survive the fire it needs.',
  },
  {
    id: 'n045',
    theme: 'nature',
    q: 'Why do wolves howl, and what does the chorus achieve?',
    a: 'Territory and cohesion — and it makes a pack sound larger',
    note: 'They deliberately avoid harmonising, which makes counting the voices harder.',
  },
  {
    id: 'n046',
    theme: 'nature',
    q: 'Why is a seahorse unusual among vertebrates in reproduction?',
    a: 'The male carries and gives birth',
    note: 'He has a true pouch and provides nutrients. It is pregnancy by any reasonable definition.',
  },
  {
    id: 'n047',
    theme: 'nature',
    q: 'Why do plants in a rainforest understorey have such large leaves?',
    a: 'Very little light gets through — they need the area',
    note: 'The same species higher in the canopy grows much smaller leaves. The plant reads the light.',
  },
  {
    id: 'n048',
    theme: 'nature',
    q: 'Why is an octopus considered so intelligent, and what is odd about where its neurons are?',
    a: 'Most of them are in its arms',
    note: 'About two-thirds. An arm can solve a problem after being separated from the body.',
  },
  {
    id: 'n049',
    theme: 'nature',
    q: 'Why do cicadas emerge on 13 and 17 year cycles specifically?',
    a: 'Prime numbers make it hard for predators to synchronise',
    note: 'A predator on a two or three year cycle can never lock onto a prime.',
  },
  {
    id: 'n050',
    theme: 'nature',
    q: 'Why does a snake flick its tongue?',
    a: 'It samples chemicals and delivers them to a sensory organ in the mouth',
    note: 'The fork gives it a left and right sample, so it can smell in stereo and follow a trail.',
  },
  {
    id: 'n051',
    theme: 'nature',
    q: 'Why do many trees produce enormous seed crops in some years and almost none in others?',
    a: 'Masting — it overwhelms seed predators periodically',
    note: 'Trees across a whole region synchronise. How they do it is still not fully explained.',
  },
  {
    id: 'n052',
    theme: 'nature',
    q: 'Why does a peacock have such an absurd tail, given that it makes flying harder?',
    a: 'Sexual selection — the cost is the signal',
    note: 'Only a genuinely fit bird can carry a handicap that large. Zahavi’s handicap principle.',
  },
  {
    id: 'n053',
    theme: 'nature',
    q: 'Why can lichens grow on bare rock where nothing else can?',
    a: 'They are a fungus and an alga together — one anchors, the other feeds',
    note: 'They are also the first colonisers after a glacier or a lava flow, and they make soil.',
  },
  {
    id: 'n054',
    theme: 'nature',
    q: 'Why do bats navigate by sound rather than sight?',
    a: 'It works in complete darkness and gives range as well as direction',
    note: 'Some can detect a wire thinner than a human hair. Sight cannot do that at night at any price.',
  },
  {
    id: 'n055',
    theme: 'nature',
    q: 'Why does a plant wilt, and why does it recover when watered?',
    a: 'Cells lose turgor pressure — water refills the vacuoles',
    note: 'Plants stand up by hydraulics, not by structure. A wilted plant is a deflated one.',
  },
  {
    id: 'n056',
    theme: 'nature',
    q: 'Why are there so many more species near the equator?',
    a: 'More energy, more stable climate, longer undisturbed time',
    note: 'The latitudinal diversity gradient. One of the oldest observations in ecology and still argued about.',
  },
  {
    id: 'n057',
    theme: 'nature',
    q: 'Why do some animals play dead, and why does it work?',
    a: 'Many predators trigger on movement and avoid carrion',
    note: 'Opossums do it involuntarily. It is a seizure, not a decision.',
  },
  {
    id: 'n058',
    theme: 'nature',
    q: 'Why do bees dance, and what does the dance encode?',
    a: 'Direction and distance to food',
    note: 'The angle relative to vertical is the angle relative to the sun. Von Frisch got a Nobel for decoding it.',
  },
  {
    id: 'n059',
    theme: 'nature',
    q: 'Why is a Venus flytrap fussy about closing, and how does it count?',
    a: 'It requires two touches within about twenty seconds',
    note: 'Closing on a raindrop would waste enormous energy. The plant is filtering false positives.',
  },
  {
    id: 'n060',
    theme: 'nature',
    q: 'Why do desert plants often have spines instead of leaves?',
    a: 'Less surface area for water loss, and defence',
    note: 'A cactus photosynthesises in its stem. The spines also shade it and collect dew.',
  },
  {
    id: 'n061',
    theme: 'nature',
    q: 'Why do dogs have such a better sense of smell than humans, in numbers?',
    a: 'Vastly more receptors and far more brain devoted to it',
    note: 'Roughly 300 million receptors to our 6 million, and a proportionally much larger olfactory bulb.',
  },
  {
    id: 'n062',
    theme: 'nature',
    q: 'Why is grass able to survive being grazed and mown, when most plants cannot?',
    a: 'It grows from the base, not the tip',
    note: 'Which is why lawns exist and why grasslands can support enormous herds.',
  },
  {
    id: 'n063',
    theme: 'nature',
    q: 'Why do so many seabirds have a gland above the eye?',
    a: 'To excrete salt',
    note: 'They can drink seawater. The gland does what our kidneys cannot manage at that concentration.',
  },
  {
    id: 'n064',
    theme: 'nature',
    q: 'Why does a tree’s heartwood die while the tree lives?',
    a: 'Only the outer layers transport water — the centre becomes structural',
    note: 'A hollow tree can be perfectly healthy. Everything alive is a few centimetres under the bark.',
  },
  {
    id: 'n065',
    theme: 'nature',
    q: 'Why do ants follow each other in lines?',
    a: 'Pheromone trails, reinforced by success',
    note: 'A shorter route gets walked more often, so it gets stronger. The colony optimises without anybody deciding.',
  },
  {
    id: 'n066',
    theme: 'nature',
    q: 'Why can a tardigrade survive vacuum, radiation and near absolute zero?',
    a: 'It dehydrates into a state with almost no metabolism',
    note: 'Cryptobiosis. It is not tough while active — it is tough while switched off.',
  },
  {
    id: 'n067',
    theme: 'nature',
    q: 'Why do some flowers open at night?',
    a: 'They are pollinated by moths or bats',
    note: 'Night flowers are usually white and strongly scented, because colour is useless in the dark.',
  },
  {
    id: 'n068',
    theme: 'nature',
    q: 'Why do reindeer eyes change colour between summer and winter?',
    a: 'The reflective layer shifts to gather more light in the dark months',
    note: 'Gold in summer, deep blue in winter. Discovered only in 2013.',
  },
  {
    id: 'n069',
    theme: 'nature',
    q: 'Why is a fig not quite a fruit, and what is usually inside one?',
    a: 'It is an inverted flower cluster — pollinated by a wasp that often dies inside',
    note: 'An enzyme digests the wasp. Commercial figs are usually a variety that needs no wasp at all.',
  },
  {
    id: 'n070',
    theme: 'nature',
    q: 'Why do birds have hollow bones, and what else is unusual about their breathing?',
    a: 'Weight — and their lungs use a one-way flow through air sacs',
    note: 'They extract oxygen on inhale and exhale. It is why they can fly over the Himalayas.',
  },
  {
    id: 'n071',
    theme: 'nature',
    q: 'Why do plants make caffeine, nicotine and capsaicin?',
    a: 'They are pesticides',
    note: 'Every stimulant in your kitchen is a plant trying to poison an insect.',
  },
  {
    id: 'n072',
    theme: 'nature',
    q: 'Why is a whale’s blowhole on top of its head?',
    a: 'It surfaces to breathe without stopping',
    note: 'It is the nostril, migrated. Embryos show it starting at the front and moving back.',
  },
  {
    id: 'n073',
    theme: 'nature',
    q: 'Why do rivers support more life at their edges than in the middle?',
    a: 'Shallow, slower water with light reaching the bottom',
    note: 'Edges everywhere are richer. Ecologists call it the edge effect and it holds in almost every habitat.',
  },
  {
    id: 'n074',
    theme: 'nature',
    q: 'Why is a shark’s skin rough, and what did it inspire?',
    a: 'Tooth-like scales that reduce drag — copied for swimsuits and aircraft',
    note: 'Denticles. Run your hand the wrong way and it is like sandpaper.',
  },
  {
    id: 'n075',
    theme: 'nature',
    q: 'Why do some plants close their leaves at night?',
    a: 'Water conservation and protection — driven by an internal clock',
    note: 'They keep doing it in constant darkness, which is how circadian rhythms were first demonstrated.',
  },
  {
    id: 'n076',
    theme: 'nature',
    q: 'Why do herds of animals stampede in a coordinated direction rather than scattering?',
    a: 'Predators pick off individuals — staying together is safer',
    note: 'The selfish herd: each animal is trying to put another between itself and the danger.',
  },
  {
    id: 'n077',
    theme: 'nature',
    q: 'Why can a cockroach live for a while without its head?',
    a: 'It breathes through its body and has a distributed nervous system',
    note: 'It dies of thirst, not of decapitation. Which is a horrible sentence to have written.',
  },
  {
    id: 'n078',
    theme: 'nature',
    q: 'Why do some trees have buttress roots?',
    a: 'Shallow soil — the buttress braces a tall tree that cannot root deep',
    note: 'Common in rainforests, where the nutrients are all in the top few centimetres.',
  },
  {
    id: 'n079',
    theme: 'nature',
    q: 'Why is it hard to tame a zebra when horses were domesticated thousands of years ago?',
    a: 'Temperament — zebras panic and do not accept hierarchy',
    note: 'Jared Diamond’s point: most large animals fail at least one of the several tests for domestication.',
  },
  {
    id: 'n080',
    theme: 'nature',
    q: 'Why does an earthworm come to the surface when it rains?',
    a: 'Probably to move safely, not to avoid drowning',
    note: 'They can survive submerged for a long time. The wet surface is a chance to travel without drying out.',
  },
  {
    id: 'n081',
    theme: 'nature',
    q: 'Why do most flowers have petals in numbers from the Fibonacci sequence?',
    a: 'Spiral growth patterns produce those numbers naturally',
    note: 'It falls out of the packing geometry. The plant is not counting.',
  },
  {
    id: 'n082',
    theme: 'nature',
    q: 'Why can a hummingbird hover when almost no other bird can?',
    a: 'Its wing generates lift on both the forward and the backward stroke',
    note: 'A figure-of-eight motion. Structurally the shoulder joint is closer to an insect’s than a bird’s.',
  },
  {
    id: 'n083',
    theme: 'nature',
    q: 'Why do fungi form rings in grass?',
    a: 'The mycelium grows outward evenly from a centre',
    note: 'The fairy ring is the leading edge of a single organism, sometimes centuries old.',
  },
  {
    id: 'n084',
    theme: 'nature',
    q: 'Why do birds not get electrocuted but squirrels sometimes do?',
    a: 'Squirrels bridge a line and an earthed structure',
    note: 'They cause a startling number of power outages. Utilities design against them specifically.',
  },
  {
    id: 'n085',
    theme: 'nature',
    q: 'Why is there such a thing as an "invasive" species, when every species arrived somewhere once?',
    a: 'Speed — it arrives without the predators and diseases that held it in check',
    note: 'Given long enough the ecosystem adjusts. "Invasive" is a statement about rate, not about origin.',
  },
  {
    id: 'n086',
    theme: 'nature',
    q: 'Why do some animals hibernate and others migrate, when both solve winter?',
    a: 'It depends on whether moving is cheaper than waiting',
    note: 'A bird can outrun winter; a hedgehog cannot. Body size and mobility decide.',
  },
  {
    id: 'n087',
    theme: 'nature',
    q: 'Why does a cut plant stem sometimes root and sometimes not?',
    a: 'It depends whether the tissue retains cells that can become roots',
    note: 'Willows root almost anywhere, and their water contains a hormone that helps other cuttings root too.',
  },
  {
    id: 'n088',
    theme: 'nature',
    q: 'Why is a koala’s diet so restrictive, and what does it cost them?',
    a: 'Eucalyptus is toxic and low in energy — they sleep about twenty hours a day',
    note: 'Their gut flora detoxifies it. Joeys eat their mother’s droppings to acquire the bacteria.',
  },
  {
    id: 'n089',
    theme: 'nature',
    q: 'Why do trees in a forest often share resources through their roots?',
    a: 'Fungal networks connect them',
    note: 'Carbon and nutrients move between trees, including different species. How deliberate it is remains contested.',
  },
  {
    id: 'n090',
    theme: 'nature',
    q: 'Why is a whale shark not a whale, and how does it feed?',
    a: 'It is a fish — it filter feeds',
    note: 'The largest fish alive, eating some of the smallest things in the sea.',
  },
  {
    id: 'n091',
    theme: 'nature',
    q: 'Why do so many animals have a symmetrical body plan?',
    a: 'Directed movement favours it',
    note: 'Animals that do not move much — sponges, corals — frequently abandon symmetry entirely.',
  },
  {
    id: 'n092',
    theme: 'nature',
    q: 'Why can a plant be a weed in one field and a crop in another?',
    a: '"Weed" is a statement about where it is, not what it is',
    note: 'Oats began as a weed in wheat fields and were domesticated because they kept winning.',
  },
  {
    id: 'n093',
    theme: 'nature',
    q: 'Why do frogs need to stay damp?',
    a: 'They breathe partly through their skin',
    note: 'Which also makes them extremely sensitive to pollution, and useful as an environmental indicator.',
  },
  {
    id: 'n094',
    theme: 'nature',
    q: 'Why does a deer’s antler differ from a horn?',
    a: 'Antlers are bone, shed and regrown yearly; horns are permanent keratin over bone',
    note: 'Antler is the fastest-growing mammalian tissue known.',
  },
  {
    id: 'n095',
    theme: 'nature',
    q: 'Why do plants produce nectar, which they cannot use themselves?',
    a: 'To pay pollinators',
    note: 'It is a transaction. Some orchids cheat and pay nothing, mimicking a female insect instead.',
  },
  {
    id: 'n096',
    theme: 'nature',
    q: 'Why do ravens and crows do so well in cities?',
    a: 'Generalist diet, problem solving, and tolerance of people',
    note: 'They recognise individual human faces and hold grudges, which has been demonstrated experimentally.',
  },
  {
    id: 'n097',
    theme: 'nature',
    q: 'Why do the leaves of many plants have serrated edges?',
    a: 'Probably to shed water and to start photosynthesis earlier in spring',
    note: 'Serration correlates strongly with cold climates, which is used to read palaeoclimate from fossil leaves.',
  },
  {
    id: 'n098',
    theme: 'nature',
    q: 'Why is a jellyfish able to function with no brain, heart or blood?',
    a: 'It is thin enough for diffusion to do the job',
    note: 'A nerve net rather than a brain. Nothing in it is more than a couple of cells from the water.',
  },
  {
    id: 'n099',
    theme: 'nature',
    q: 'Why do seeds in a fruit usually survive being eaten?',
    a: 'That is the point — the animal disperses them',
    note: 'Which is why chillies are hot to mammals and not to birds: birds are the intended courier.',
  },
  {
    id: 'n100',
    theme: 'nature',
    q: 'Why is the phrase "survival of the fittest" misleading?',
    a: '"Fittest" means best-fitting the environment, not strongest',
    note: 'Spencer coined it; Darwin adopted it reluctantly. It has caused a century and a half of confusion.',
  },
]
