/**
 * Numbers — puzzles, paradoxes and the arithmetic of everyday life.
 *
 * Not a maths exam. These are the questions where a table argues for a minute, someone says
 * something that sounds wrong, and it turns out to be right. Almost all of them are
 * answerable with no formula at all — only with care about what is actually being asked.
 */
import type { Question } from '../types'

export const NUMBERS: readonly Question[] = [
  {
    id: 'm001',
    theme: 'numbers',
    q: 'A bat and a ball cost £1.10 together. The bat costs £1 more than the ball. What does the ball cost?',
    a: '5p',
    note: 'Almost everybody says 10p first. The bat would then be £1.10 and the total £1.20.',
  },
  {
    id: 'm002',
    theme: 'numbers',
    q: 'In a room of 23 people, what is roughly the chance that two share a birthday?',
    a: 'About 50%',
    note: 'There are 253 pairs, not 23 people. Counting the pairs is the whole trick.',
  },
  {
    id: 'm003',
    theme: 'numbers',
    q: 'You are on a game show with three doors, pick one, and the host opens a different door showing a goat. Should you switch?',
    a: 'Yes — switching wins two times in three',
    note: 'The host’s choice is not random; he knows where the car is, and that is the information you gain.',
  },
  {
    id: 'm004',
    theme: 'numbers',
    q: 'A shop raises a price by 10% then cuts it by 10%. Is the final price higher, lower or the same as the start?',
    a: 'Lower — by 1%',
    note: 'The cut applies to a bigger number than the rise did. Percentages do not commute the way people expect.',
  },
  {
    id: 'm005',
    theme: 'numbers',
    q: 'Why can a piece of paper folded 42 times theoretically reach the Moon?',
    a: 'Doubling 42 times is about 4 trillion times the thickness',
    note: 'Exponential growth is the thing human intuition is worst at, by a wide margin.',
  },
  {
    id: 'm006',
    theme: 'numbers',
    q: 'You drive one mile at 30 mph and one mile at 60 mph. What is your average speed?',
    a: '40 mph, not 45',
    note: 'You spend twice as long at the slow speed. Averaging rates requires the harmonic mean.',
  },
  {
    id: 'm007',
    theme: 'numbers',
    q: 'A rope tied tightly around the earth’s equator is lengthened by one metre and lifted evenly. Roughly how high off the ground is it?',
    a: 'About 16 cm',
    note: 'It does not depend on the size of the sphere at all. The same metre gives the same gap on a tennis ball.',
  },
  {
    id: 'm008',
    theme: 'numbers',
    q: 'Why is a "one in a million" event not rare in a city of eight million?',
    a: 'You would expect about eight of them',
    note: 'Littlewood’s law: at one event per second, a person meets a million-to-one event roughly monthly.',
  },
  {
    id: 'm009',
    theme: 'numbers',
    q: 'A test for a disease is 99% accurate. The disease affects 1 in 10,000. You test positive. Roughly what is the chance you have it?',
    a: 'About 1%',
    note: 'The false positives vastly outnumber the true ones. This is the single most consequential misunderstanding in medicine.',
  },
  {
    id: 'm010',
    theme: 'numbers',
    q: 'Why does a chessboard with two opposite corners removed refuse to be covered by dominoes?',
    a: 'The removed squares are the same colour — each domino must cover one of each',
    note: 'No amount of trying will work, and one sentence proves it. The best kind of proof.',
  },
  {
    id: 'm011',
    theme: 'numbers',
    q: 'Why do so many real-world datasets start with the digit 1 far more often than with 9?',
    a: 'Benford’s law',
    note: 'It arises from scale invariance. Tax authorities use it to detect fabricated figures.',
  },
  {
    id: 'm012',
    theme: 'numbers',
    q: 'Why is it impossible to have a map of the world with no distortion?',
    a: 'A sphere cannot be flattened without stretching',
    note: 'Gauss proved it. Every projection chooses which lie to tell.',
  },
  {
    id: 'm013',
    theme: 'numbers',
    q: 'What is the smallest number of colours needed to colour any flat map so no two neighbours match?',
    a: 'Four',
    note: 'Proved in 1976 with a computer, which caused a philosophical row about what a proof is.',
  },
  {
    id: 'm014',
    theme: 'numbers',
    q: 'If you shuffle a deck of cards well, what is the chance that ordering has occurred before in history?',
    a: 'Essentially zero',
    note: '52 factorial is about 8×10^67. Every proper shuffle is almost certainly a first.',
  },
  {
    id: 'm015',
    theme: 'numbers',
    q: 'Why is 0.999… exactly equal to 1, rather than very slightly less?',
    a: 'There is no number between them',
    note: 'A third is 0.333…; multiply both sides by three. The resistance to this is emotional, not mathematical.',
  },
  {
    id: 'm016',
    theme: 'numbers',
    q: 'Why does compound interest at 7% roughly double money in ten years?',
    a: 'The rule of 72 — 72 divided by the rate',
    note: 'It works because of logarithms, and it is accurate enough to do in your head at a dinner table.',
  },
  {
    id: 'm017',
    theme: 'numbers',
    q: 'A hundred people board a plane; the first sits randomly and everyone else takes their own seat or a random one if taken. What is the chance the last person gets their own seat?',
    a: 'Exactly one half',
    note: 'It comes down to whether seat 1 or seat 100 is taken first, and those are equally likely.',
  },
  {
    id: 'm018',
    theme: 'numbers',
    q: 'Why can you not win at roulette by doubling your bet after every loss?',
    a: 'Table limits and finite money — the rare long run bankrupts you',
    note: 'The martingale has a very high chance of a small win and a small chance of total ruin.',
  },
  {
    id: 'm019',
    theme: 'numbers',
    q: 'Why are there more real numbers between 0 and 1 than there are whole numbers in total?',
    a: 'You cannot list them — Cantor’s diagonal argument',
    note: 'Given any list, you can construct a number missing from it. Some infinities are larger than others.',
  },
  {
    id: 'm020',
    theme: 'numbers',
    q: 'Why does a group of 30 people almost certainly contain two who share a birthday, but you probably need 253 to find someone sharing yours?',
    a: 'Any pair versus a specific pair',
    note: 'The question people think they are answering is not the one the maths is answering.',
  },
  {
    id: 'm021',
    theme: 'numbers',
    q: 'Why is the number 1 not considered prime?',
    a: 'Unique factorisation would break',
    note: 'It was called prime historically. It was excluded because keeping it made every theorem need an exception.',
  },
  {
    id: 'm022',
    theme: 'numbers',
    q: 'What is remarkable about the fact that pi appears in a formula about a needle dropped on lined paper?',
    a: 'You can estimate pi by dropping needles',
    note: 'Buffon’s needle. Pi turns up because the calculation involves an angle.',
  },
  {
    id: 'm023',
    theme: 'numbers',
    q: 'Why do queues at supermarkets always seem slower than the one next to you?',
    a: 'There are more other queues than yours — you are usually right',
    note: 'With three queues, yours is the fastest only a third of the time. It is not paranoia.',
  },
  {
    id: 'm024',
    theme: 'numbers',
    q: 'Why does adding one lane to a congested road sometimes make traffic worse?',
    a: 'Braess’s paradox — drivers reroute to a now-worse equilibrium',
    note: 'Closing roads has improved traffic in real cities, which sounds like nonsense and is documented.',
  },
  {
    id: 'm025',
    theme: 'numbers',
    q: 'Why does a coin that has come up heads ten times in a row have exactly the same chance of heads next?',
    a: 'The coin has no memory',
    note: 'The gambler’s fallacy. Unless you now suspect the coin is biased, in which case bet on heads.',
  },
  {
    id: 'm026',
    theme: 'numbers',
    q: 'What is the "birthday attack" in cryptography, and which everyday puzzle is it named after?',
    a: 'Finding any collision is far easier than a specific one — the birthday problem',
    note: 'It is why hash functions need twice the bits you would naively expect.',
  },
  {
    id: 'm027',
    theme: 'numbers',
    q: 'Why is it easier to multiply two large primes than to work out which primes a large number is made of?',
    a: 'Multiplication is fast; factoring is not',
    note: 'That asymmetry is the whole of public-key cryptography, and therefore of internet commerce.',
  },
  {
    id: 'm028',
    theme: 'numbers',
    q: 'A rich man leaves 17 camels: half to one son, a third to another, a ninth to the third. How is it resolved?',
    a: 'Borrow a camel, divide 18, and give it back',
    note: '9 + 6 + 2 = 17. The fractions never added to one in the first place, which is the joke.',
  },
  {
    id: 'm029',
    theme: 'numbers',
    q: 'Why does an aeroplane’s "average" passenger not exist, and what famous design failure came from assuming it did?',
    a: 'No one is average on every dimension — the US Air Force cockpit',
    note: 'Of 4,000 pilots, none was average on all ten measurements. Adjustable seats came from that finding.',
  },
  {
    id: 'm030',
    theme: 'numbers',
    q: 'Why is the median usually a better summary of income than the mean?',
    a: 'A few enormous values drag the mean upward',
    note: 'If Bill Gates walks into a bar, the mean wealth of the room is meaningless and the median barely moves.',
  },
  {
    id: 'm031',
    theme: 'numbers',
    q: 'What is Simpson’s paradox?',
    a: 'A trend in every group can reverse when the groups are combined',
    note: 'A famous Berkeley admissions case appeared to show bias overall and none in any department.',
  },
  {
    id: 'm032',
    theme: 'numbers',
    q: 'Why can you not fairly cut a cake into three by two straight vertical cuts?',
    a: 'You can — but only if the cuts are not through the centre',
    note: 'The classic puzzle usually intends "three equal pieces with three cuts", where a horizontal one is allowed.',
  },
  {
    id: 'm033',
    theme: 'numbers',
    q: 'Why does a Mercator map make Africa look about the same size as Greenland?',
    a: 'Area distortion grows towards the poles',
    note: 'Africa is about fourteen times larger. It is a projection problem, not a printing error.',
  },
  {
    id: 'm034',
    theme: 'numbers',
    q: 'A drawer holds 10 black and 10 blue socks in the dark. How many must you take to guarantee a matching pair?',
    a: 'Three',
    note: 'The pigeonhole principle. With two colours, three socks force a repeat.',
  },
  {
    id: 'm035',
    theme: 'numbers',
    q: 'Why is a "hundred-year flood" not something that happens once a century?',
    a: 'It is a 1% chance each year, independently',
    note: 'Two in consecutive years is unremarkable. The name is one of the worst in public communication.',
  },
  {
    id: 'm036',
    theme: 'numbers',
    q: 'Why does the second hand of a clock pass the minute hand a different number of times per hour than you would guess?',
    a: 'They coincide 59 times in an hour, not 60',
    note: 'The minute hand is moving too. The same reasoning explains the hour and minute hands overlapping 11 times in 12 hours.',
  },
  {
    id: 'm037',
    theme: 'numbers',
    q: 'Why is it impossible to trisect an arbitrary angle with compass and straightedge?',
    a: 'It requires solving a cubic that those tools cannot construct',
    note: 'Proved in 1837. People still send universities purported solutions every year.',
  },
  {
    id: 'm038',
    theme: 'numbers',
    q: 'What does it mean that a lottery with a positive expected value can still be a bad bet?',
    a: 'Variance — and the marginal value of money is not linear',
    note: 'A rollover can push the expectation above the ticket price and still not be worth playing.',
  },
  {
    id: 'm039',
    theme: 'numbers',
    q: 'Why do binary and decimal disagree about whether 0.1 is a simple number?',
    a: 'A tenth is not a finite binary fraction',
    note: 'Which is why 0.1 + 0.2 does not equal 0.3 in most programming languages.',
  },
  {
    id: 'm040',
    theme: 'numbers',
    q: 'Why is Zeno’s arrow paradox resolved by calculus rather than by argument?',
    a: 'An infinite sum can converge to a finite total',
    note: 'The Greeks lacked the idea of a limit. The paradox is a hole in the mathematics, not in reality.',
  },
  {
    id: 'm041',
    theme: 'numbers',
    q: 'Why does a randomly chosen number have a 50% chance of containing at least one 3, if it is six digits long?',
    a: 'Roughly — 1 minus 0.9 to the sixth is about 47%',
    note: 'People consistently underestimate this. Absence is much rarer than it feels.',
  },
  {
    id: 'm042',
    theme: 'numbers',
    q: 'What is a "prisoner’s dilemma", and what makes it a dilemma rather than a puzzle?',
    a: 'Both do better cooperating, but each individually does better defecting',
    note: 'The rational move produces the worse outcome for both. That is the whole shape of the problem.',
  },
  {
    id: 'm043',
    theme: 'numbers',
    q: 'Why can you not average percentages of different-sized groups by adding them up and dividing?',
    a: 'They must be weighted by group size',
    note: 'The commonest statistical error in journalism, and one of the easiest to check.',
  },
  {
    id: 'm044',
    theme: 'numbers',
    q: 'Why is the Fibonacci sequence so common in nature?',
    a: 'It arises from growth where each new part is added at a constant angle',
    note: 'The golden angle packs seeds most efficiently. The sequence is a consequence, not a cause.',
  },
  {
    id: 'm045',
    theme: 'numbers',
    q: 'Why does a lottery syndicate of 20 people not multiply anyone’s chance of a life-changing sum?',
    a: 'Twenty times the chance of a twentieth of the prize',
    note: 'The expected value is identical. Only the variance changes, which is arguably the point.',
  },
  {
    id: 'm046',
    theme: 'numbers',
    q: 'Why did ancient civilisations struggle without a symbol for zero?',
    a: 'Positional notation needs a placeholder',
    note: 'Roman numerals need no zero because they are not positional — and are hopeless for arithmetic.',
  },
  {
    id: 'm047',
    theme: 'numbers',
    q: 'What is remarkable about the number of ways to shuffle a Rubik’s cube versus the number of moves needed to solve it?',
    a: '43 quintillion positions, and never more than 20 moves',
    note: 'Called God’s number. Proved by exhaustive computer search in 2010.',
  },
  {
    id: 'm048',
    theme: 'numbers',
    q: 'Why is a "significant" result in a study not necessarily an important one?',
    a: 'Significance is about probability of chance, not size of effect',
    note: 'With a big enough sample, a trivial difference becomes significant. It is a badly chosen word.',
  },
  {
    id: 'm049',
    theme: 'numbers',
    q: 'Why do casinos not need to cheat?',
    a: 'A small edge over enough repetitions is certain',
    note: 'The law of large numbers works for the house. Individual nights are noise.',
  },
  {
    id: 'm050',
    theme: 'numbers',
    q: 'What is a "black swan" in the sense Taleb meant?',
    a: 'A rare, high-impact event that is rationalised afterwards as predictable',
    note: 'The third part matters most: the hindsight narrative is what stops anyone learning.',
  },
  {
    id: 'm051',
    theme: 'numbers',
    q: 'Why can two people flip a fair coin over a telephone without trusting each other?',
    a: 'Commitment schemes — you commit to a value you cannot change but have not revealed',
    note: 'Blum’s protocol. The whole of digital trust is variations on this idea.',
  },
  {
    id: 'm052',
    theme: 'numbers',
    q: 'Why is it a bad idea to compare "cases" between two countries without adjusting?',
    a: 'Population, testing rate and definitions all differ',
    note: 'A country that tests more finds more. The measurement changes what is being measured.',
  },
  {
    id: 'm053',
    theme: 'numbers',
    q: 'Why does a 90% confidence interval get narrower than a 99% one?',
    a: 'Less certainty demands less room',
    note: 'You can make any interval as narrow as you like by being willing to be wrong more often.',
  },
  {
    id: 'm054',
    theme: 'numbers',
    q: 'What is the "law of truly large numbers"?',
    a: 'With a big enough sample, absurd coincidences are expected',
    note: 'Somebody wins the lottery twice somewhere. It would be surprising if nobody did.',
  },
  {
    id: 'm055',
    theme: 'numbers',
    q: 'Why is a "random" playlist that never repeats an artist not actually random?',
    a: 'True randomness clusters — users complain, so it is deliberately spread out',
    note: 'Spotify changed its shuffle to be less random precisely because people thought it was broken.',
  },
  {
    id: 'm056',
    theme: 'numbers',
    q: 'Why can a knight on a chessboard never move to a square of the same colour?',
    a: 'Its move always changes colour',
    note: 'One square one way and two the other always flips the parity. Which is why a knight’s tour has structure.',
  },
  {
    id: 'm057',
    theme: 'numbers',
    q: 'Why does doubling the linear size of an object multiply its weight by eight?',
    a: 'Volume scales with the cube',
    note: 'And the strength of its legs only by four. This is why giants do not work.',
  },
  {
    id: 'm058',
    theme: 'numbers',
    q: 'What is Goodhart’s law?',
    a: 'When a measure becomes a target, it stops being a good measure',
    note: 'Every metric in every organisation eventually demonstrates it.',
  },
  {
    id: 'm059',
    theme: 'numbers',
    q: 'Why is the sum of the first n odd numbers always a perfect square?',
    a: 'Each odd number adds an L-shaped border to a square',
    note: '1, 4, 9, 16. Draw it once and the proof is obvious for ever.',
  },
  {
    id: 'm060',
    theme: 'numbers',
    q: 'Why is an insurance company happy to take a bet it expects to lose on any single policy?',
    a: 'It is not betting once — it is betting a million times',
    note: 'It sells certainty and buys variance. The customer is doing the reverse and both are rational.',
  },
  {
    id: 'm061',
    theme: 'numbers',
    q: 'Why does the "wisdom of crowds" work for guessing the weight of an ox but not for a technical question?',
    a: 'Independent errors cancel; correlated ignorance does not',
    note: 'Galton’s ox. Once people can hear each other, the effect largely disappears.',
  },
  {
    id: 'm062',
    theme: 'numbers',
    q: 'Why is the harmonic series divergent, even though its terms go to zero?',
    a: 'The partial sums grow without limit, just very slowly',
    note: 'You need about 10^43 terms to reach 100. It gets there eventually.',
  },
  {
    id: 'm063',
    theme: 'numbers',
    q: 'Why can you always find two antipodal points on earth with the same temperature and pressure?',
    a: 'The Borsuk–Ulam theorem',
    note: 'It is a topological fact, not a meteorological one. It would be true on any planet.',
  },
  {
    id: 'm064',
    theme: 'numbers',
    q: 'Why is a 1% daily gain not a 365% annual gain?',
    a: 'Compounding — it is about 3,700%',
    note: 'And a 1% daily loss leaves you with about 2.5% of your money. The asymmetry is brutal.',
  },
  {
    id: 'm065',
    theme: 'numbers',
    q: 'What is the "St Petersburg paradox"?',
    a: 'A game with infinite expected value that nobody will pay much to play',
    note: 'It broke expected-value reasoning and led to the idea of diminishing marginal utility.',
  },
  {
    id: 'm066',
    theme: 'numbers',
    q: 'Why is it that if everybody in a stadium stands to see better, nobody sees better?',
    a: 'The advantage is relative, and it cancels',
    note: 'A positional good. Much of economics is arguments about which goods are like this.',
  },
  {
    id: 'm067',
    theme: 'numbers',
    q: 'Why can a number be divisible by 3 if its digits add to a multiple of 3, and why does the same trick not work for 7?',
    a: 'Because 10 leaves remainder 1 when divided by 3 — it does not for 7',
    note: 'The same reason works for 9. Divisibility rules are facts about the base you write in.',
  },
  {
    id: 'm068',
    theme: 'numbers',
    q: 'Why do two people meeting in a large city seem like a miracle, statistically speaking?',
    a: 'They usually share a reason to be there — the coincidence is conditioned',
    note: 'You do not bump into strangers; you bump into people whose lives overlap yours.',
  },
  {
    id: 'm069',
    theme: 'numbers',
    q: 'Why is it impossible for a computer to generate a truly random number by itself?',
    a: 'It is deterministic — it needs an external physical source',
    note: 'Which is why some systems use radioactive decay, atmospheric noise, or a wall of lava lamps.',
  },
  {
    id: 'm070',
    theme: 'numbers',
    q: 'Why does a "regression to the mean" make bad management look effective?',
    a: 'Extreme performances are followed by ordinary ones regardless of intervention',
    note: 'Punish a bad day and things improve; praise a good one and they worsen. Both are illusions.',
  },
  {
    id: 'm071',
    theme: 'numbers',
    q: 'Why is the perimeter of a fractal coastline infinite while its area is not?',
    a: 'Detail adds length at every scale but encloses no more space',
    note: 'Which is why "how long is a coastline" has no answer without stating the ruler.',
  },
  {
    id: 'm072',
    theme: 'numbers',
    q: 'Why does a knockout tournament of 64 players need exactly 63 matches?',
    a: 'Every match eliminates exactly one player',
    note: 'You do not need to think about rounds at all. One sentence answers any tournament size.',
  },
  {
    id: 'm073',
    theme: 'numbers',
    q: 'Why is a "p-value" of 0.05 an arbitrary threshold?',
    a: 'Fisher chose it as a convenience and said so',
    note: 'He explicitly called it a matter of taste. It has been treated as a law of nature ever since.',
  },
  {
    id: 'm074',
    theme: 'numbers',
    q: 'Why does a rumour spread through a network faster than through a crowd of the same size?',
    a: 'A few highly connected nodes shortcut the distance',
    note: 'Small-world networks. Six degrees of separation is a property of the shortcuts, not of the average.',
  },
  {
    id: 'm075',
    theme: 'numbers',
    q: 'Why do you need only about 60 random people to be nearly certain two share a birthday?',
    a: 'The pair count grows with the square of the group',
    note: 'At 60 people there are 1,770 pairs. The chance of no match is under 1%.',
  },
  {
    id: 'm076',
    theme: 'numbers',
    q: 'What is a "false positive paradox" and where does it matter most?',
    a: 'When a condition is rare, most positives are false — screening and security',
    note: 'A face recognition system that is 99.9% accurate on a million people produces a thousand false hits.',
  },
  {
    id: 'm077',
    theme: 'numbers',
    q: 'Why is it a mistake to say a result is "twice as likely" without saying twice what?',
    a: 'Relative risk without absolute risk is meaningless',
    note: 'Doubling a one-in-a-million risk is still a one-in-five-hundred-thousand risk.',
  },
  {
    id: 'm078',
    theme: 'numbers',
    q: 'Why can a graph with an unlabelled or truncated axis be technically accurate and deeply misleading?',
    a: 'It changes the perceived size of a difference',
    note: 'Starting the axis at 98 rather than 0 turns a rounding error into a cliff.',
  },
  {
    id: 'm079',
    theme: 'numbers',
    q: 'Why is the Collatz conjecture famous despite being simple enough to explain to a child?',
    a: 'Nobody can prove it',
    note: 'Halve if even, triple and add one if odd. Verified past 10^20 and still unproven.',
  },
  {
    id: 'm080',
    theme: 'numbers',
    q: 'Why does an exponential process feel slow and then sudden?',
    a: 'Most of the total arrives in the last few doublings',
    note: 'A pond half covered in lily pads is one day from being fully covered.',
  },
  {
    id: 'm081',
    theme: 'numbers',
    q: 'Why is it easier to check a solution to a Sudoku than to find one?',
    a: 'Verification is fast, search is not — it is NP-complete in general',
    note: 'That gap is the P versus NP question, and a million dollars is on offer for settling it.',
  },
  {
    id: 'm082',
    theme: 'numbers',
    q: 'Why does a mile-long train take longer to pass a point than its length suggests?',
    a: 'The whole length must clear it, not just the front',
    note: 'The same reasoning trips people up on bridges, tunnels and level crossings constantly.',
  },
  {
    id: 'm083',
    theme: 'numbers',
    q: 'Why is the average number of legs per human slightly under two?',
    a: 'A few people have fewer, and nobody has more',
    note: 'Which means almost everybody has an above-average number of legs. A joke that is also a lesson.',
  },
  {
    id: 'm084',
    theme: 'numbers',
    q: 'Why did the metric system’s definition of the metre change from a physical bar to a fraction of a light-second?',
    a: 'A bar can be damaged or drift; the speed of light cannot',
    note: 'The metre is now defined by fixing c. The unit is derived from a constant, not from an object.',
  },
  {
    id: 'm085',
    theme: 'numbers',
    q: 'Why can a two-dimensional shape have an infinite perimeter and fit on a page?',
    a: 'Convergent area, divergent length',
    note: 'The Koch snowflake. Its perimeter grows by a third at every step and never stops.',
  },
  {
    id: 'm086',
    theme: 'numbers',
    q: 'Why is a "survivorship bias" dangerous when studying success?',
    a: 'The failures are not in the sample',
    note: 'Wald’s aircraft: armour where the returning planes were not hit, because those hits killed the ones that never came back.',
  },
  {
    id: 'm087',
    theme: 'numbers',
    q: 'Why does an exponential decay never reach zero, and how is a half-life still useful?',
    a: 'It halves indefinitely — but after ten half-lives less than 0.1% remains',
    note: '"Never zero" is mathematically true and practically irrelevant, which is the useful distinction.',
  },
  {
    id: 'm088',
    theme: 'numbers',
    q: 'Why is a lottery jackpot advertised as much larger than what a winner receives?',
    a: 'It is an annuity total before tax',
    note: 'The lump sum is often around half. The advertised number is the sum of thirty future payments.',
  },
  {
    id: 'm089',
    theme: 'numbers',
    q: 'Why does a group of people splitting a bill evenly tend to order more expensive food?',
    a: 'Each person bears only a fraction of their own cost',
    note: 'The unscrupulous diner’s dilemma. It has been tested experimentally and it happens.',
  },
  {
    id: 'm090',
    theme: 'numbers',
    q: 'Why can seventeen camels be divided into halves, thirds and ninths only by borrowing?',
    a: 'The fractions sum to 17/18, not to 1',
    note: 'The borrowed camel is never used. It is a fixed point that lets the rounding work.',
  },
  {
    id: 'm091',
    theme: 'numbers',
    q: 'Why do we use base ten, and what would base twelve be better at?',
    a: 'Fingers — twelve divides by 2, 3, 4 and 6',
    note: 'Which is why eggs, hours and inches all come in twelves. Trade preferred divisibility over anatomy.',
  },
  {
    id: 'm092',
    theme: 'numbers',
    q: 'Why is it usually wrong to say a coincidence "cannot be chance"?',
    a: 'You are looking backwards at one outcome out of an enormous number',
    note: 'The probability of that exact thing is tiny; the probability of something like it is near certain.',
  },
  {
    id: 'm093',
    theme: 'numbers',
    q: 'Why does a chessboard with a grain of rice doubled on each square bankrupt a kingdom?',
    a: '2^64 minus 1 grains — more than all the rice ever grown',
    note: 'About 460 billion tonnes. The story ends with the inventor being executed in some versions.',
  },
  {
    id: 'm094',
    theme: 'numbers',
    q: 'Why is a "margin of error" of ±3% not the whole story in a poll?',
    a: 'It only covers sampling error, not bias in who answered',
    note: 'Non-response bias is usually larger and is never quoted, because it cannot be calculated.',
  },
  {
    id: 'm095',
    theme: 'numbers',
    q: 'Why do you need only about 23 people for a 50% birthday match but 253 for a specific date?',
    a: 'One compares all pairs, the other compares each person to one fixed value',
    note: 'The clearest demonstration that the question you ask determines the answer you get.',
  },
  {
    id: 'm096',
    theme: 'numbers',
    q: 'Why is it impossible to write a program that determines whether any given program will finish?',
    a: 'The halting problem — a contradiction arises if you assume one exists',
    note: 'Turing, 1936. It is the same self-reference that powers Gödel’s theorems.',
  },
  {
    id: 'm097',
    theme: 'numbers',
    q: 'Why does a rope hanging between two poles form a curve that is not a parabola?',
    a: 'It is a catenary — the weight is distributed along the rope, not horizontally',
    note: 'A suspension bridge cable, loaded by the deck, genuinely is a parabola. The difference is where the weight is.',
  },
  {
    id: 'm098',
    theme: 'numbers',
    q: 'Why do voting systems all have flaws, according to a famous theorem?',
    a: 'Arrow’s theorem — no ranked system can satisfy a short list of reasonable conditions',
    note: 'Every method is a choice about which fairness criterion to give up.',
  },
  {
    id: 'm099',
    theme: 'numbers',
    q: 'Why is the number of possible chess games larger than the number of atoms in the observable universe?',
    a: 'The branching factor compounds over dozens of moves',
    note: 'The Shannon number is about 10^120; atoms are about 10^80. Which is why chess cannot be brute-forced.',
  },
  {
    id: 'm100',
    theme: 'numbers',
    q: 'Why is "correlation is not causation" only half the useful lesson?',
    a: 'The other half is that causation does produce correlation — so it is evidence, just not proof',
    note: 'Dismissing every correlation is as lazy as accepting every one. The work is in the mechanism.',
  },
]
