/**
 * Science — reachable by reasoning, not by having done the degree.
 *
 * The trap in this theme is asking for a fact from a textbook. Every question here instead
 * describes a situation and asks what must be true of it, so a table with no scientist can
 * still get there by arguing. Where a name is wanted it is a name most people have heard.
 */
import type { Question } from '../types'

export const SCIENCE: readonly Question[] = [
  {
    id: 's001',
    theme: 'science',
    q: 'A helium balloon released inside a car will do something surprising when the car accelerates forward. What, and why?',
    a: 'It moves forward, not back',
    note: 'The dense air piles up at the back, so the pressure gradient pushes the light balloon the other way. Everything heavy goes backwards; the balloon goes with the low pressure.',
  },
  {
    id: 's002',
    theme: 'science',
    q: 'Why can you not simply keep folding a sheet of paper in half indefinitely, even with unlimited strength?',
    a: 'The thickness doubles each time while the length halves',
    note: 'After about seven folds the stack is thicker than the strip is long, and there is nothing left to bend around.',
  },
  {
    id: 's003',
    theme: 'science',
    q: 'Two identical glasses, one with hot water and one with cold, are put in a freezer. Under some conditions the hot one freezes first. What is this effect called?',
    a: 'The Mpemba effect',
    note: 'Named after a Tanzanian schoolboy who insisted on it against his teacher. Still argued about.',
  },
  {
    id: 's004',
    theme: 'science',
    q: 'Why does a mirror appear to reverse left and right, but not up and down?',
    a: 'It reverses front and back; you do the left-right swap yourself by turning around',
    note: 'Lie on your side and the mirror will happily "reverse" up and down instead.',
  },
  {
    id: 's005',
    theme: 'science',
    q: 'The Sun converts about four million tonnes of mass into energy every second. What happens to the Sun’s mass over its lifetime as a result?',
    a: 'It loses a tiny fraction — well under a hundredth of one per cent',
    note: 'Four million tonnes a second sounds enormous and is nothing next to two thousand trillion trillion tonnes.',
  },
  {
    id: 's006',
    theme: 'science',
    q: 'Why is the sky blue, and why is the setting sun red — in one explanation that covers both?',
    a: 'Short wavelengths scatter more; at sunset the light travels further so only the long ones survive',
    note: 'Rayleigh scattering. The blue you see overhead is the blue that has been taken *out* of the sunset.',
  },
  {
    id: 's007',
    theme: 'science',
    q: 'A cat falling from the seventh floor is statistically more likely to survive than one falling from the fifth. Give the accepted explanation.',
    a: 'Past terminal velocity it relaxes and spreads out, and it has time to right itself',
    note: 'Vets called it high-rise syndrome. The sampling is also biased: cats that die on impact are not brought in.',
  },
  {
    id: 's008',
    theme: 'science',
    q: 'What single property of water explains both why ice floats and why lakes do not freeze solid from the bottom?',
    a: 'It is less dense as a solid than as a liquid',
    note: 'Almost nothing else does this. If water behaved normally, every lake on earth would be a block of ice.',
  },
  {
    id: 's009',
    theme: 'science',
    q: 'A ship’s hull is painted with a horizontal line and a set of marks. What do they tell the crew, and why does the safe level differ between the North Atlantic in winter and the tropics?',
    a: 'How deep it may be loaded — water density varies with temperature and salinity',
    note: 'The Plimsoll line. Warm fresh water gives less buoyancy, so the ship may carry less.',
  },
  {
    id: 's010',
    theme: 'science',
    q: 'Why does a struck tuning fork get louder when its base is pressed against a table?',
    a: 'The table is a much larger surface moving the air',
    note: 'It does not add energy — it spends it faster. The fork also stops sounding sooner.',
  },
  {
    id: 's011',
    theme: 'science',
    q: 'Astronauts on the International Space Station are often said to be weightless because there is no gravity. What is actually true?',
    a: 'Gravity there is about 90% of that at the surface — they are in free fall',
    note: 'They are falling around the earth and missing. Weightlessness is falling, not the absence of weight.',
  },
  {
    id: 's012',
    theme: 'science',
    q: 'What do a bicycle wheel, a spinning skater and a helicopter tail rotor all demonstrate about the same conserved quantity?',
    a: 'Angular momentum',
    note: 'The tail rotor exists purely to stop the helicopter body spinning the other way.',
  },
  {
    id: 's013',
    theme: 'science',
    q: 'Why does a hot drink cool faster if you add the cold milk at the start rather than at the end?',
    a: 'It does not — adding it late keeps the drink hotter, because a hotter drink loses heat faster',
    note: 'Newton’s law of cooling. Keeping the drink cooler for longer means it radiates away less.',
  },
  {
    id: 's014',
    theme: 'science',
    q: 'A diamond and the graphite in a pencil are made of exactly the same element. What single word explains the difference?',
    a: 'Arrangement (allotropes)',
    note: 'Diamond is a lattice in three dimensions; graphite is sheets that slide. That is the entire difference.',
  },
  {
    id: 's015',
    theme: 'science',
    q: 'Why do we not fall off the earth at the equator, given that it is spinning at over 1,600 km/h?',
    a: 'Gravity vastly exceeds the centrifugal effect — which does exist and makes you slightly lighter',
    note: 'You weigh about half a per cent less at the equator than at the pole, partly for this reason.',
  },
  {
    id: 's016',
    theme: 'science',
    q: 'A radio telescope and a kitchen microwave both work with the same part of the spectrum. Why can you not cook anything with a radio telescope?',
    a: 'It receives rather than transmits, and the signals are unimaginably faint',
    note: 'The total energy collected by all radio telescopes in history would not warm a cup of tea.',
  },
  {
    id: 's017',
    theme: 'science',
    q: 'Why is it colder at the top of a mountain when you are closer to the Sun?',
    a: 'Air warms from the ground up and thins with height',
    note: 'The extra few kilometres towards the Sun is nothing against 150 million. The atmosphere is the whole story.',
  },
  {
    id: 's018',
    theme: 'science',
    q: 'A fly inside a sealed, closed jar on a scale takes off and hovers. What happens to the reading?',
    a: 'Nothing — it stays the same',
    note: 'The downwash pushes on the jar exactly as much as the fly weighs. Sealed systems do not get lighter.',
  },
  {
    id: 's019',
    theme: 'science',
    q: 'The human body contains more of these than it does human cells, by count. What are they?',
    a: 'Bacteria (microbial cells)',
    note: 'The old "ten to one" figure is out of date; the current estimate is closer to one to one, but still more.',
  },
  {
    id: 's020',
    theme: 'science',
    q: 'Why does helium make a voice sound higher, and what does that tell you about what your voice actually is?',
    a: 'Sound travels faster in helium, raising the resonant frequencies of the vocal tract',
    note: 'Your pitch does not change — the filter does. Sulphur hexafluoride does the opposite.',
  },
  {
    id: 's021',
    theme: 'science',
    q: 'What do the Moon always showing us the same face and a figure skater pulling in her arms have in common?',
    a: 'Both are about rotation being locked to something else — tidal locking, angular momentum',
    note: 'Accept "tidal locking". The Earth slowed the Moon’s spin until it matched its orbit.',
  },
  {
    id: 's022',
    theme: 'science',
    q: 'A candle burning in a sealed jar goes out long before the oxygen runs out. Why?',
    a: 'Carbon dioxide builds up and the flame cannot sustain itself below about 16% oxygen',
    note: 'The old parlour trick "proving" air is one-fifth oxygen actually measures the flame’s failure point.',
  },
  {
    id: 's023',
    theme: 'science',
    q: 'Why do you see lightning before you hear thunder, and what simple arithmetic turns the gap into a distance?',
    a: 'Light is far faster; roughly three seconds per kilometre',
    note: 'Five seconds a mile. Sound covers about 343 metres a second at room temperature.',
  },
  {
    id: 's024',
    theme: 'science',
    q: 'What is the connection between a bruise turning yellow and the whites of the eyes turning yellow in liver disease?',
    a: 'Both are bilirubin, the breakdown product of haemoglobin',
    note: 'A bruise is a small local jaundice. The colour sequence is the pigment being processed.',
  },
  {
    id: 's025',
    theme: 'science',
    q: 'Two objects of very different mass are dropped in a vacuum. Galileo said they land together. What does Newton’s second law say about why the heavier one is not faster?',
    a: 'It has more force pulling it but proportionally more inertia',
    note: 'F = ma with F proportional to m means a cancels out. The mass appears on both sides.',
  },
  {
    id: 's026',
    theme: 'science',
    q: 'Why can a small child on a swing get higher by moving their body, without anyone pushing?',
    a: 'They change the effective length of the pendulum in time with it — parametric resonance',
    note: 'Standing up at the bottom and crouching at the top. Pumping is physics, not effort.',
  },
  {
    id: 's027',
    theme: 'science',
    q: 'What is measured in pascals, in bar, in atmospheres and in millimetres of mercury — and why is one of those units a length?',
    a: 'Pressure; mercury is measured as the height of a column it supports',
    note: 'A barometer literally is a column of mercury. The unit is the measurement apparatus.',
  },
  {
    id: 's028',
    theme: 'science',
    q: 'Why does a wet cloth feel colder than a dry one at the same temperature?',
    a: 'Evaporation takes heat from your skin',
    note: 'The same reason sweating works, and why a fan cools you without cooling the room.',
  },
  {
    id: 's029',
    theme: 'science',
    q: 'What single change to the atmosphere would make the sky appear black in daytime while the Sun still shone?',
    a: 'Removing the air — no scattering',
    note: 'This is exactly what astronauts see, and why lunar photographs have a black sky at noon.',
  },
  {
    id: 's030',
    theme: 'science',
    q: 'Why is a red traffic light red rather than any other colour, in terms of physics rather than convention?',
    a: 'Red scatters least, so it stays visible furthest in fog and rain',
    note: 'The same reason for red on ships and aircraft. Convention followed the physics.',
  },
  {
    id: 's031',
    theme: 'science',
    q: 'A tree is mostly made of a substance it did not take from the soil. Where did most of the mass come from?',
    a: 'The air — carbon dioxide',
    note: 'Van Helmont weighed the soil before and after growing a willow and found it almost unchanged. He concluded water; he was half right.',
  },
  {
    id: 's032',
    theme: 'science',
    q: 'Why does a bicycle stay up when moving but not when still, and what is wrong with the popular gyroscope explanation?',
    a: 'Mostly steering geometry — bikes with counter-rotating wheels still balance',
    note: 'A 2011 experiment built a bike with cancelled gyroscopic effect and no trail. It still rode.',
  },
  {
    id: 's033',
    theme: 'science',
    q: 'What do a rainbow, an oil slick and a soap bubble have in common, and what is different about the rainbow?',
    a: 'All show a spectrum; the rainbow is refraction, the others are interference',
    note: 'Which is why a bubble’s colours shift as it thins and a rainbow’s do not.',
  },
  {
    id: 's034',
    theme: 'science',
    q: 'A person in a lift feels heavier at one moment and lighter at another. When exactly, and what does a bathroom scale actually measure?',
    a: 'Heavier accelerating up, lighter accelerating down; a scale measures the force it pushes back with',
    note: 'It never measures mass. In free fall it reads zero and you have not lost any.',
  },
  {
    id: 's035',
    theme: 'science',
    q: 'Why does the Moon look enormous near the horizon and small overhead, when it is measurably the same size?',
    a: 'It is an illusion of the brain, not of the atmosphere',
    note: 'Photograph both and measure. Nobody fully agrees on the mechanism, which is remarkable for something so common.',
  },
  {
    id: 's036',
    theme: 'science',
    q: 'What is the same about a microwave oven, a radio and visible light — and what number distinguishes them?',
    a: 'All are electromagnetic radiation; frequency (or wavelength)',
    note: 'One continuous spectrum. The names are a historical accident of which instrument found which part.',
  },
  {
    id: 's037',
    theme: 'science',
    q: 'Why does salt melt ice, given that dissolving it is an endothermic process that makes the mixture colder?',
    a: 'It lowers the freezing point below the ambient temperature',
    note: 'It does get colder — that is how ice cream was made before freezers.',
  },
  {
    id: 's038',
    theme: 'science',
    q: 'A single human breath contains roughly 10^22 molecules. What famous conclusion follows about the air Julius Caesar exhaled?',
    a: 'You probably breathe some of it in every breath',
    note: 'The atmosphere has about 10^44 molecules. The numbers are large enough that the improbable becomes certain.',
  },
  {
    id: 's039',
    theme: 'science',
    q: 'Why is there a maximum height for a tree, and what physical limit sets it?',
    a: 'Water cannot be pulled up beyond about 120–130 metres before the column breaks',
    note: 'Trees do not pump water; they pull it, and a column of water under tension eventually cavitates.',
  },
  {
    id: 's040',
    theme: 'science',
    q: 'What do the terms "supersonic", "hypersonic" and "sonic boom" all depend on that is not a fixed speed?',
    a: 'The local speed of sound, which varies with temperature',
    note: 'Mach 1 at sea level is about 1,225 km/h; in the stratosphere it is roughly 1,060.',
  },
  {
    id: 's041',
    theme: 'science',
    q: 'Why do humans see a rainbow as an arc rather than a full circle?',
    a: 'The ground cuts it off — from an aircraft it can be a complete circle',
    note: 'It is always a cone of a fixed angle around the point opposite the sun, which is usually below the horizon.',
  },
  {
    id: 's042',
    theme: 'science',
    q: 'What is odd about the fact that the same element makes both the hardest natural substance and one of the softest?',
    a: 'Nothing chemically — carbon’s bonding geometry differs completely',
    note: 'Diamond and graphite again, but the point is that structure beats composition almost every time.',
  },
  {
    id: 's043',
    theme: 'science',
    q: 'Why do you get a shock from a door handle in winter but rarely in summer?',
    a: 'Dry air insulates; humid air lets the charge leak away continuously',
    note: 'Central heating dries indoor air enormously, which is why it is worse indoors than out.',
  },
  {
    id: 's044',
    theme: 'science',
    q: 'What single measurement did Eratosthenes need, besides the distance between two cities, to work out the size of the earth?',
    a: 'The angle of a shadow at noon',
    note: 'Around 240 BC, to within a few per cent. Two sticks and some arithmetic.',
  },
  {
    id: 's045',
    theme: 'science',
    q: 'Why does a spinning ice skater speed up when she pulls her arms in, and where does the extra energy come from?',
    a: 'Angular momentum is conserved; she does work pulling her arms against centrifugal force',
    note: 'The energy is not free — she supplies it with her muscles, and can feel it.',
  },
  {
    id: 's046',
    theme: 'science',
    q: 'What is the biological reason that cutting an onion makes you cry, and why does chilling it help?',
    a: 'It releases a volatile sulphur compound; cold slows its evaporation',
    note: 'The gas reacts with the water in your eyes to make a mild acid. Your eyes flush it out.',
  },
  {
    id: 's047',
    theme: 'science',
    q: 'A person is said to be "colour blind". What is usually actually missing, and why is total colour blindness so rare?',
    a: 'One type of cone works differently; having none at all is a much rarer condition',
    note: 'Most "colour blindness" is red-green confusion, and it is on the X chromosome — hence far commoner in men.',
  },
  {
    id: 's048',
    theme: 'science',
    q: 'What do the aurora, a neon sign and a sodium street lamp have in common?',
    a: 'All are gases glowing when their atoms are excited',
    note: 'The colour is the element’s fingerprint. The aurora is green because oxygen is.',
  },
  {
    id: 's049',
    theme: 'science',
    q: 'Why is a vacuum flask silvered on the inside?',
    a: 'To reflect radiant heat, which a vacuum cannot block',
    note: 'The vacuum stops conduction and convection. Radiation needs no medium, so it needs a mirror.',
  },
  {
    id: 's050',
    theme: 'science',
    q: 'Why does bread go stale faster in a fridge than at room temperature, when nearly everything else lasts longer?',
    a: 'Starch retrogradation is fastest just above freezing',
    note: 'Staling is not drying. Freezing properly is fine; chilling is the worst of both.',
  },
  {
    id: 's051',
    theme: 'science',
    q: 'What are you actually seeing when you see a "shooting star", and how big is it typically?',
    a: 'A grain of dust burning up — often smaller than a grain of sand',
    note: 'The light comes from air being heated and ionised, not from the object glowing.',
  },
  {
    id: 's052',
    theme: 'science',
    q: 'Why does a pot of water stop rising in temperature once it boils, however high you turn the heat?',
    a: 'The extra energy goes into the phase change, not the temperature',
    note: 'Latent heat. A rolling boil cooks no faster than a gentle one — it just wastes gas.',
  },
  {
    id: 's053',
    theme: 'science',
    q: 'What is the reason a compass needle points north, and why is the earth’s "north magnetic pole" technically a south pole?',
    a: 'Opposites attract — the needle’s north is drawn to a magnetic south',
    note: 'The naming is historical and backwards, and every physics teacher has to explain it.',
  },
  {
    id: 's054',
    theme: 'science',
    q: 'Why can you hear someone in the next room through a wall, but not see them, when both sound and light are waves?',
    a: 'The wavelengths differ enormously — sound diffracts around and through obstacles',
    note: 'Sound wavelengths are metres; visible light is a fraction of a micron. Scale decides everything.',
  },
  {
    id: 's055',
    theme: 'science',
    q: 'What do a bee’s vision, a banknote’s security thread and a scorpion under a lamp have in common?',
    a: 'Ultraviolet',
    note: 'Bees see it, banknotes fluoresce under it, and scorpions glow blue-green in it for reasons nobody is sure of.',
  },
  {
    id: 's056',
    theme: 'science',
    q: 'What is the "placebo effect" measuring, and why is a trial with no placebo arm considered nearly worthless?',
    a: 'Improvement from expectation and natural recovery — with no arm you cannot separate them from the drug',
    note: 'Most conditions improve on their own. Without a control you are measuring time.',
  },
  {
    id: 's057',
    theme: 'science',
    q: 'Why does a dropped slice of buttered toast so often land butter side down, according to the physics rather than the joke?',
    a: 'Table height gives roughly half a rotation',
    note: 'Robert Matthews got an Ig Nobel for it. From a taller table it would land butter up.',
  },
  {
    id: 's058',
    theme: 'science',
    q: 'What single fact about DNA makes it possible to identify a person from a hair, and also to reconstruct a species’ family tree?',
    a: 'Every cell carries the same copy, and copies accumulate small differences over time',
    note: 'Identity and ancestry are the same measurement at two different scales.',
  },
  {
    id: 's059',
    theme: 'science',
    q: 'Why do aircraft leave trails on some days and not others?',
    a: 'The air must be cold and humid enough for the exhaust water to condense and persist',
    note: 'It is a cloud made of engine exhaust. On dry days it evaporates before you see it.',
  },
  {
    id: 's060',
    theme: 'science',
    q: 'What is happening chemically when a cut apple goes brown, and why does lemon juice stop it?',
    a: 'Enzymatic oxidation; the acid and vitamin C block it',
    note: 'The same enzyme family that makes tea leaves black and bruised bananas dark.',
  },
  {
    id: 's061',
    theme: 'science',
    q: 'Why is the deepest part of the ocean under more pressure than anywhere in the atmosphere, by a factor of about a thousand?',
    a: 'Water is roughly 800 times denser than air',
    note: 'Ten metres of water adds one atmosphere. The Mariana Trench adds about eleven hundred.',
  },
  {
    id: 's062',
    theme: 'science',
    q: 'What do you call the phenomenon whereby a sound’s pitch changes as its source passes you, and what does it let astronomers measure?',
    a: 'The Doppler effect — the speed of stars and galaxies',
    note: 'Redshift is the same effect on light. It is how we know the universe is expanding.',
  },
  {
    id: 's063',
    theme: 'science',
    q: 'A yawn is often said to increase oxygen. What is the better-supported current explanation?',
    a: 'Cooling the brain',
    note: 'Yawning is commoner when the ambient air is cool, and rarer when it is hotter than body temperature.',
  },
  {
    id: 's064',
    theme: 'science',
    q: 'Why does an old photograph fade, and why do the colours not fade evenly?',
    a: 'Light and oxygen break the dyes down at different rates',
    note: 'Cyan usually goes first, which is why old prints turn red. Magenta lasts longest.',
  },
  {
    id: 's065',
    theme: 'science',
    q: 'What is the reason a glass of beer left overnight goes flat, in terms of a law about gases and liquids?',
    a: 'Henry’s law — dissolved gas leaves as its partial pressure above the liquid falls',
    note: 'Which is why a sealed bottle keeps and an open one does not, whatever the temperature.',
  },
  {
    id: 's066',
    theme: 'science',
    q: 'Why can birds sit safely on a high-voltage line?',
    a: 'There is no potential difference across them — both feet are at the same voltage',
    note: 'A bird large enough to touch two lines at once is a bird that does not.',
  },
  {
    id: 's067',
    theme: 'science',
    q: 'What are you tasting when food tastes "of nothing" during a heavy cold, and what does that reveal about taste?',
    a: 'Only the five basic tastes — most of flavour is smell',
    note: 'The tongue does sweet, salt, sour, bitter and umami. Everything else arrives through the nose.',
  },
  {
    id: 's068',
    theme: 'science',
    q: 'Why does a mirror in a steamy bathroom fog, but a mirror that has been left running under hot water does not?',
    a: 'Condensation needs a surface colder than the dew point',
    note: 'Warm the glass and the water has nowhere to condense. Anti-fog coatings work differently — they spread it.',
  },
  {
    id: 's069',
    theme: 'science',
    q: 'What is the connection between a firefly, a deep-sea anglerfish and a glowing bacterial culture?',
    a: 'Bioluminescence — light from a chemical reaction, usually luciferin',
    note: 'It has evolved independently dozens of times. In the deep ocean it is the rule, not the exception.',
  },
  {
    id: 's070',
    theme: 'science',
    q: 'Why do we say a battery "runs out" when energy cannot be destroyed?',
    a: 'The chemical reaction reaches equilibrium — the energy has been spent, not lost',
    note: 'It is all still there, as heat and as reaction products, just no longer able to do work.',
  },
  {
    id: 's071',
    theme: 'science',
    q: 'What single word describes both a substance that will not dissolve and a problem that cannot be solved — and is the same word in both cases?',
    a: 'Insoluble',
    note: 'Chemistry lent the word to logic, or possibly the other way round. Both mean "cannot be broken up".',
  },
  {
    id: 's072',
    theme: 'science',
    q: 'A blue whale’s heart is often compared to a small car. What is the corresponding fact about its arteries that people find hardest to believe?',
    a: 'The aorta is wide enough to put your head into',
    note: 'The claim that a child could swim through it is an exaggeration, but not by as much as you would hope.',
  },
  {
    id: 's073',
    theme: 'science',
    q: 'Why does the same amount of sunlight warm a dark car far more than a white one, and what happens at night?',
    a: 'Dark absorbs more; at night the dark car also radiates faster and cools quicker',
    note: 'A good absorber is a good emitter. The property is symmetric, which is Kirchhoff’s law.',
  },
  {
    id: 's074',
    theme: 'science',
    q: 'What is the reason a helium-filled balloon deflates within a day while an air-filled one lasts weeks?',
    a: 'Helium atoms are small enough to diffuse through the rubber',
    note: 'They also leak past the knot. Foil balloons last because the barrier is metal, not latex.',
  },
  {
    id: 's075',
    theme: 'science',
    q: 'The metric system defines the second, the metre and the kilogram. Which of the three was, until 2019, still defined by a physical object, and where was it?',
    a: 'The kilogram — a cylinder near Paris',
    note: 'It was losing mass relative to its copies, which is a problem when it is the definition.',
  },
  {
    id: 's076',
    theme: 'science',
    q: 'Why do submarines use sound rather than light or radio to see, and what does that imply about how loud the ocean is?',
    a: 'Water absorbs light and radio quickly but carries sound extremely well',
    note: 'A whale call can travel hundreds of kilometres. The ocean is a very noisy place.',
  },
  {
    id: 's077',
    theme: 'science',
    q: 'What do the terms "AM" and "FM" describe about a radio wave, and why does FM sound better but travel less far?',
    a: 'Amplitude and frequency modulation — FM resists noise but does not bend round the horizon',
    note: 'Noise is mostly amplitude, so encoding in frequency ignores it. Longer AM waves follow the earth’s curve.',
  },
  {
    id: 's078',
    theme: 'science',
    q: 'What is the reason nearly all large land animals are more or less the same shape when scaled, but an insect is not?',
    a: 'Strength scales with area, weight with volume — the square-cube law',
    note: 'Which is why an ant lifts many times its weight and an ant the size of a horse would collapse.',
  },
  {
    id: 's079',
    theme: 'science',
    q: 'Why is it easier to float in the Dead Sea, and what would happen to a fish put in it?',
    a: 'Extreme salinity raises density; the fish would die of osmotic water loss',
    note: 'It is called the Dead Sea for a reason. Only some microbes manage it.',
  },
  {
    id: 's080',
    theme: 'science',
    q: 'What is a "half-life", and why does something with a half-life never quite reach zero?',
    a: 'The time for half to decay; halving repeatedly never reaches nothing',
    note: 'In practice it reaches one atom and then that one decays, which is where the mathematics stops being useful.',
  },
  {
    id: 's081',
    theme: 'science',
    q: 'A person is described as having a "photographic memory". What do memory researchers say about the claim?',
    a: 'No case has ever been verified under controlled conditions',
    note: 'Eidetic imagery exists in some children and fades. Nobody has demonstrated page-perfect recall on demand.',
  },
  {
    id: 's082',
    theme: 'science',
    q: 'Why does soap work, in one sentence about molecules?',
    a: 'One end likes water, the other likes grease',
    note: 'It stitches the two together so the grease can be carried away. The whole of cleaning, in one molecule.',
  },
  {
    id: 's083',
    theme: 'science',
    q: 'What does a "leap second" correct for, and why is it irregular when a leap day is not?',
    a: 'The earth’s slowing, irregular rotation',
    note: 'A year is predictable; tides and the earth’s core are not. They are added by announcement, months ahead.',
  },
  {
    id: 's084',
    theme: 'science',
    q: 'Why can a small hole in a curtain project an image of the world outside onto the opposite wall?',
    a: 'It restricts each point to one ray — a pinhole camera',
    note: 'The image is upside down and always in focus, which is why it needs no lens.',
  },
  {
    id: 's085',
    theme: 'science',
    q: 'What is the reason a struck bell rings at a particular note regardless of how hard you hit it?',
    a: 'The frequency is set by geometry and material, not by energy',
    note: 'Hitting harder changes loudness, not pitch. Which is why tuning a bell means removing metal.',
  },
  {
    id: 's086',
    theme: 'science',
    q: 'Two mirrors facing each other appear to show infinite reflections, but the images fade. Why?',
    a: 'Each reflection loses a few per cent of the light',
    note: 'A very good mirror reflects about 95%. Fifty bounces leaves you eight per cent of the original.',
  },
  {
    id: 's087',
    theme: 'science',
    q: 'What does the word "organic" mean in chemistry, and why is it a historical misnomer?',
    a: 'Carbon-based — it once meant "produced only by living things"',
    note: 'Wöhler synthesised urea from inorganic material in 1828 and quietly demolished the distinction.',
  },
  {
    id: 's088',
    theme: 'science',
    q: 'Why does a hot air balloon rise, and what is the single number the pilot is actually controlling?',
    a: 'The air inside is less dense; the pilot controls its temperature',
    note: 'About 100°C hotter than outside gives roughly a quarter less density. That is the whole aircraft.',
  },
  {
    id: 's089',
    theme: 'science',
    q: 'What is the connection between the smell of rain on dry ground and a word coined in 1964 from Greek?',
    a: 'Petrichor — from "petra", stone, and "ichor", the blood of the gods',
    note: 'It is oils from plants absorbed into the soil, released when the surface wets. Two Australian scientists named it.',
  },
  {
    id: 's090',
    theme: 'science',
    q: 'A "double-blind" trial hides something from two groups. Which two, and why does hiding it from the second matter?',
    a: 'Patients and the researchers assessing them — assessors unconsciously bias measurements',
    note: 'The observer effect is not a physics joke here. It is the main reason single-blind trials overstate effects.',
  },
  {
    id: 's091',
    theme: 'science',
    q: 'Why does a river meander instead of running straight, even across a flat plain?',
    a: 'Faster water on the outside of any bend erodes it, deepening the curve',
    note: 'A perfectly straight channel is unstable: the smallest wobble amplifies itself.',
  },
  {
    id: 's092',
    theme: 'science',
    q: 'What is a "catalytic converter" converting, and why does it need to get hot before it works?',
    a: 'Exhaust gases into less harmful ones — catalysts need a light-off temperature',
    note: 'Which is why most of a car’s lifetime emissions come from the first two minutes of each journey.',
  },
  {
    id: 's093',
    theme: 'science',
    q: 'Why is the inside of a microwave oven a metal box with a mesh in the door?',
    a: 'The holes are smaller than the wavelength, so the waves cannot escape',
    note: 'A Faraday cage. Microwaves are about 12 cm long; the holes are a couple of millimetres.',
  },
  {
    id: 's094',
    theme: 'science',
    q: 'What single property distinguishes a metal from a non-metal in the way electrical engineers care about, and what does temperature do to it?',
    a: 'Free electrons — metals conduct worse when hotter, semiconductors better',
    note: 'That reversal is the whole basis of the transistor and therefore of everything.',
  },
  {
    id: 's095',
    theme: 'science',
    q: 'Why is human blood red, horseshoe crab blood blue, and some worm blood green?',
    a: 'Different metals in the oxygen-carrying molecule — iron, copper, and others',
    note: 'Horseshoe crab blood is still used to test medicines for bacterial contamination.',
  },
  {
    id: 's096',
    theme: 'science',
    q: 'What is happening when a bone "sets", and why is the repaired section often stronger than the original for a while?',
    a: 'A callus of new bone forms, initially thicker than the shaft',
    note: 'It is remodelled back down over months. Break the same bone again and it usually goes somewhere else.',
  },
  {
    id: 's097',
    theme: 'science',
    q: 'Why does a struck match need to be struck, when the chemicals in it are already combustible?',
    a: 'Friction supplies the activation energy',
    note: 'Safety matches split the reactants between the head and the strip, which is why one will not light on a wall.',
  },
  {
    id: 's098',
    theme: 'science',
    q: 'What do the words "laser" and "radar" have in common besides both being about waves?',
    a: 'Both are acronyms',
    note: 'Light Amplification by Stimulated Emission of Radiation; RAdio Detection And Ranging. Genuine ones, unlike most.',
  },
  {
    id: 's099',
    theme: 'science',
    q: 'Why is it impossible to reach absolute zero, according to the third law of thermodynamics?',
    a: 'Each step removes a fraction of the remaining heat — it takes infinite steps',
    note: 'Laboratories have reached a few billionths of a degree above it and stopped there for good reasons.',
  },
  {
    id: 's100',
    theme: 'science',
    q: 'A famous experiment involved a cat, a box and a vial of poison. What was the philosopher actually arguing?',
    a: 'That the interpretation was absurd when scaled up to everyday objects',
    note: 'Schrödinger meant it as a criticism. It is now the most-quoted illustration of the thing he was mocking.',
  },
]
