/**
 * Games and sport — why the rules are the rules.
 *
 * Not results, not records, not who won what in which year: those are lookups. These ask why
 * a pitch is that size, why a rule was written, or what problem a piece of equipment solved —
 * which a table can argue its way to whether or not anybody follows the sport.
 */
import type { Question } from '../types'

export const SPORT: readonly Question[] = [
  {
    id: 'p001',
    theme: 'sport',
    q: 'Why does a golf ball have dimples, when a smooth one would seem more aerodynamic?',
    a: 'They trip the airflow into turbulence, which reduces the wake and doubles the distance',
    note: 'Discovered because scuffed old balls flew further than new ones. Golfers noticed before engineers explained it.',
  },
  {
    id: 'p002',
    theme: 'sport',
    q: 'Why is a marathon 42.195 kilometres, a number nobody would choose?',
    a: 'The 1908 London course was extended to finish in front of the royal box',
    note: 'The distance was only fixed permanently in 1921, using that one race as the standard.',
  },
  {
    id: 'p003',
    theme: 'sport',
    q: 'Why does tennis score 15, 30, 40 rather than 1, 2, 3?',
    a: 'Probably a clock face, with 45 shortened to 40',
    note: 'The quarter-hour theory is the best available. Nobody can prove it, and nobody has a better one.',
  },
  {
    id: 'p004',
    theme: 'sport',
    q: 'Why is the offside rule in football necessary at all?',
    a: 'Without it, players would simply wait by the goal',
    note: 'Every invasion sport has some version. Without one, the game degenerates into long balls.',
  },
  {
    id: 'p005',
    theme: 'sport',
    q: 'Why do sprinters run anticlockwise on a track?',
    a: 'Convention, standardised in 1913 — possibly because it feels more natural',
    note: 'Early races went both ways. Once records existed, the direction had to be fixed.',
  },
  {
    id: 'p006',
    theme: 'sport',
    q: 'Why does a cricket ball have a raised seam, and what does a bowler use it for?',
    a: 'It disturbs the airflow asymmetrically — swing',
    note: 'Which is why the shine on one side matters, and why ball-tampering is a scandal rather than a nuisance.',
  },
  {
    id: 'p007',
    theme: 'sport',
    q: 'Why is a boxing ring square?',
    a: 'It was once literally a ring — the ropes and posts made it square',
    note: 'A crowd drew a circle around the fighters. The name outlived the shape by two centuries.',
  },
  {
    id: 'p008',
    theme: 'sport',
    q: 'Why do swimmers shave, and how much does it actually help?',
    a: 'Slightly less drag and better feel for the water — the psychological effect may be larger',
    note: 'Studies show a real but small improvement, and a measurable change in stroke efficiency.',
  },
  {
    id: 'p009',
    theme: 'sport',
    q: 'Why does a high jumper go over the bar backwards?',
    a: 'The body’s centre of mass can pass under the bar',
    note: 'Fosbury changed the sport in 1968. It only became safe once landing pits stopped being sand.',
  },
  {
    id: 'p010',
    theme: 'sport',
    q: 'Why is a football pitch not a fixed size, unlike almost every other sport?',
    a: 'The laws specify a range, not a number',
    note: 'A legacy of grounds being fitted into whatever land was available. Only the goal and the markings are fixed.',
  },
  {
    id: 'p011',
    theme: 'sport',
    q: 'Why do cyclists ride in a tight group, and how much energy does it save?',
    a: 'Drafting — up to about 40% for a rider in the middle',
    note: 'Which is why a lone breakaway almost always fails against an organised peloton.',
  },
  {
    id: 'p012',
    theme: 'sport',
    q: 'Why does a curveball curve, and what was long doubted about it?',
    a: 'The Magnus effect from spin — people insisted it was an optical illusion',
    note: 'Settled with high-speed photography. The break is real and mostly happens late.',
  },
  {
    id: 'p013',
    theme: 'sport',
    q: 'Why is the Olympic marathon usually run in the morning or evening rather than midday?',
    a: 'Heat — core temperature is the limiting factor',
    note: 'The 2020 Tokyo marathon was moved 800 km north to Sapporo for the same reason.',
  },
  {
    id: 'p014',
    theme: 'sport',
    q: 'Why is a chess clock used, and what did it solve?',
    a: 'Players stalling — some games lasted days',
    note: 'One nineteenth-century game had a player think for over two hours on a single move.',
  },
  {
    id: 'p015',
    theme: 'sport',
    q: 'Why does a football swerve when struck off-centre?',
    a: 'Spin plus airflow — the same Magnus effect as a curveball',
    note: 'Roberto Carlos’s 1997 free kick is the standard illustration, and it has been modelled precisely.',
  },
  {
    id: 'p016',
    theme: 'sport',
    q: 'Why do rowers face backwards?',
    a: 'Pulling is stronger than pushing',
    note: 'The legs do most of the work either way, but the arm and back geometry only works pulling.',
  },
  {
    id: 'p017',
    theme: 'sport',
    q: 'Why is a tennis ball fuzzy and yellow, and when did the colour change?',
    a: 'Fuzz for aerodynamics; yellow in 1972 for television',
    note: 'Wimbledon held out until 1986. Attenborough, then at the BBC, pushed for the change.',
  },
  {
    id: 'p018',
    theme: 'sport',
    q: 'Why is a "hat-trick" called that, and which sport does it come from?',
    a: 'Cricket — a bowler taking three wickets in three balls was given a hat',
    note: 'The club bought it. Football borrowed the term much later.',
  },
  {
    id: 'p019',
    theme: 'sport',
    q: 'Why do weightlifters exhale sharply and sometimes shout?',
    a: 'Bracing the core, and a measurable strength increase from the vocal effort',
    note: 'The shout is not showmanship. Studies find a few per cent of extra force.',
  },
  {
    id: 'p020',
    theme: 'sport',
    q: 'Why is a football match 90 minutes long?',
    a: 'An 1866 agreement split the difference between two clubs’ customs',
    note: 'One played 45-minute halves, the other something else. The compromise became universal.',
  },
  {
    id: 'p021',
    theme: 'sport',
    q: 'Why do runners at altitude set distance records less often but sprinters set them more?',
    a: 'Thinner air means less oxygen but less drag',
    note: 'Mexico City 1968 produced extraordinary sprint marks and dreadful distance times.',
  },
  {
    id: 'p022',
    theme: 'sport',
    q: 'Why is a rugby ball oval?',
    a: 'It was originally a pig’s bladder inside a leather case',
    note: 'The shape was accidental, then kept because it bounces unpredictably and is easier to carry.',
  },
  {
    id: 'p023',
    theme: 'sport',
    q: 'Why does a basketball hoop stand at exactly ten feet?',
    a: 'That was the height of the railing Naismith nailed the peach baskets to',
    note: 'Entirely arbitrary, and unchanged since 1891 despite players getting much taller.',
  },
  {
    id: 'p024',
    theme: 'sport',
    q: 'Why do sprinters use starting blocks, and what did they use before?',
    a: 'To push against — they dug holes in the cinder track',
    note: 'Blocks arrived in the 1930s and made false-start detection possible, which mattered more.',
  },
  {
    id: 'p025',
    theme: 'sport',
    q: 'Why is a marathon runner’s pace so much slower than a sprinter’s, physiologically?',
    a: 'Different energy systems — one is aerobic, the other is not',
    note: 'A sprinter is essentially not breathing for the race. The systems barely overlap.',
  },
  {
    id: 'p026',
    theme: 'sport',
    q: 'Why does a boxer wear gloves, and what did they change about the sport?',
    a: 'They protect the hands, so punches to the head became survivable to throw',
    note: 'Bare-knuckle fighters hit the body more. Gloves arguably increased brain injury.',
  },
  {
    id: 'p027',
    theme: 'sport',
    q: 'Why is the pole vault pole made of fibreglass rather than metal or bamboo?',
    a: 'It stores and returns energy by bending',
    note: 'The vaulter converts run-up speed into elastic energy. The record jumped by a metre when poles changed.',
  },
  {
    id: 'p028',
    theme: 'sport',
    q: 'Why does a table tennis player blow on the ball or wipe the table between points?',
    a: 'Sweat changes the bounce and the spin',
    note: 'Players are also allowed to towel off every six points, which is a rule about the ball, not the player.',
  },
  {
    id: 'p029',
    theme: 'sport',
    q: 'Why is there a "shot clock" in basketball?',
    a: 'To stop teams stalling with a lead',
    note: 'Introduced in 1954 after a game finished 19–18. It saved the professional sport.',
  },
  {
    id: 'p030',
    theme: 'sport',
    q: 'Why do goalkeepers wear a different colour?',
    a: 'So the referee can identify who may handle the ball',
    note: 'Mandated in 1909. Before that only a cap distinguished them.',
  },
  {
    id: 'p031',
    theme: 'sport',
    q: 'Why is a "love" score in tennis called that?',
    a: 'Most likely from playing for love — for nothing',
    note: 'The French "l’œuf", an egg for zero, is the popular story and is probably folk etymology.',
  },
  {
    id: 'p032',
    theme: 'sport',
    q: 'Why do Formula 1 cars have such wide tyres but almost no tread?',
    a: 'Dry grip needs contact area; tread only helps in the wet',
    note: 'Wet tyres have tread to move water. A slick in the rain has no grip at all.',
  },
  {
    id: 'p033',
    theme: 'sport',
    q: 'Why does a skier crouch, and what are the two separate reasons?',
    a: 'Less drag, and a lower centre of gravity',
    note: 'At speed the drag matters more. Downhill racers hold a tuck that is exhausting to maintain.',
  },
  {
    id: 'p034',
    theme: 'sport',
    q: 'Why is a cricket Test match five days long?',
    a: 'It was originally played until a result — some lasted longer',
    note: 'The 1939 "Timeless Test" was abandoned after ten days because the visitors had a boat to catch.',
  },
  {
    id: 'p035',
    theme: 'sport',
    q: 'Why do football teams change ends at half time?',
    a: 'To share any advantage from wind, slope or sun',
    note: 'Some historic grounds had a slope of over two metres, which was worth a goal.',
  },
  {
    id: 'p036',
    theme: 'sport',
    q: 'Why is a penalty shootout considered an unfair way to decide a match, statistically?',
    a: 'The team shooting first wins noticeably more often',
    note: 'Around 60% in some studies. Alternative orders have been trialled to fix it.',
  },
  {
    id: 'p037',
    theme: 'sport',
    q: 'Why do archers use a stabiliser rod sticking out from the bow?',
    a: 'It increases the moment of inertia, damping small movements',
    note: 'It also absorbs vibration. The bow becomes harder to wobble, not heavier to hold.',
  },
  {
    id: 'p038',
    theme: 'sport',
    q: 'Why is the Tour de France ridden in stages rather than as one race?',
    a: 'It was invented to sell newspapers over several weeks',
    note: 'L’Auto created it in 1903 as a circulation stunt. The yellow jersey matches the paper’s newsprint.',
  },
  {
    id: 'p039',
    theme: 'sport',
    q: 'Why do runners breathe in a rhythm tied to their stride?',
    a: 'The impact compresses the diaphragm — matching avoids fighting it',
    note: 'Odd ratios are recommended so the same foot does not always land on the exhale.',
  },
  {
    id: 'p040',
    theme: 'sport',
    q: 'Why does a bowling ball hook down the lane?',
    a: 'Oil on the front of the lane, dry at the back — the ball grips when it reaches the dry',
    note: 'The oil pattern is invisible and is changed between competitions. It is a hidden variable.',
  },
  {
    id: 'p041',
    theme: 'sport',
    q: 'Why is a baseball’s stitching red, and what does it do aerodynamically?',
    a: 'Visibility; the raised seams let a pitcher control the airflow',
    note: 'A four-seam and a two-seam grip produce measurably different flight from the same arm.',
  },
  {
    id: 'p042',
    theme: 'sport',
    q: 'Why do gymnasts chalk their hands?',
    a: 'It absorbs sweat and increases friction',
    note: 'Magnesium carbonate. Too much makes it worse, which is why they clap it off.',
  },
  {
    id: 'p043',
    theme: 'sport',
    q: 'Why is the men’s and women’s marathon the same distance when most other events differ?',
    a: 'It was never shortened — the women’s race was simply added later',
    note: 'It was not an Olympic event until 1984, on the grounds that it was thought dangerous.',
  },
  {
    id: 'p044',
    theme: 'sport',
    q: 'Why do fencers wear a wire trailing behind them in some formats?',
    a: 'Electronic scoring — touches are too fast to judge by eye',
    note: 'Introduced in the 1930s. The best fencers move faster than a referee can resolve.',
  },
  {
    id: 'p045',
    theme: 'sport',
    q: 'Why is a football’s pattern of pentagons and hexagons a good design?',
    a: 'It approximates a sphere from flat panels',
    note: 'A truncated icosahedron. Modern balls use fewer, oddly shaped panels for the same reason with better glue.',
  },
  {
    id: 'p046',
    theme: 'sport',
    q: 'Why is there a "false start" rule with a fixed reaction time in sprinting?',
    a: 'Below about a tenth of a second, nobody can have reacted to the gun',
    note: 'The threshold is a claim about human physiology, and it is regularly challenged.',
  },
  {
    id: 'p047',
    theme: 'sport',
    q: 'Why do sailing races start with boats already moving?',
    a: 'A boat cannot start from stationary quickly',
    note: 'The start line is crossed at speed on a timed run, which makes the start itself a skill.',
  },
  {
    id: 'p048',
    theme: 'sport',
    q: 'Why does a dart board have that particular arrangement of numbers?',
    a: 'High numbers sit next to low ones to punish inaccuracy',
    note: '20 is flanked by 1 and 5. The layout is a deliberate penalty function.',
  },
  {
    id: 'p049',
    theme: 'sport',
    q: 'Why do long jumpers land with their feet ahead of their body?',
    a: 'The measurement is taken from the nearest mark',
    note: 'Falling backwards costs the whole gain, which is why the landing is drilled as hard as the jump.',
  },
  {
    id: 'p050',
    theme: 'sport',
    q: 'Why is a "home advantage" real, and what did empty stadiums during 2020 reveal?',
    a: 'It shrank substantially — much of it was crowd influence on referees',
    note: 'Home teams received noticeably fewer favourable decisions with nobody watching.',
  },
  {
    id: 'p051',
    theme: 'sport',
    q: 'Why do horses in a race carry weights?',
    a: 'Handicapping, to equalise the field',
    note: 'A better horse carries more lead. The aim is a race where every horse could plausibly win.',
  },
  {
    id: 'p052',
    theme: 'sport',
    q: 'Why is the javelin’s design different from the one used before 1986?',
    a: 'The centre of gravity was moved forward so it lands nose-down and travels less far',
    note: 'Throws were approaching the far end of stadiums. The rule change was a safety measure.',
  },
  {
    id: 'p053',
    theme: 'sport',
    q: 'Why does a swimmer push off the wall underwater rather than surfacing immediately?',
    a: 'There is no wave drag underwater',
    note: 'It became so effective that the distance allowed underwater had to be capped at 15 metres.',
  },
  {
    id: 'p054',
    theme: 'sport',
    q: 'Why is chess notation algebraic rather than descriptive now?',
    a: 'It is unambiguous and does not depend on which side you are',
    note: 'Descriptive notation had two names for every square. Algebraic won in the 1970s.',
  },
  {
    id: 'p055',
    theme: 'sport',
    q: 'Why do football players spit so much on the pitch?',
    a: 'Hard breathing produces thick saliva that is unpleasant to swallow',
    note: 'It is a consequence of mouth breathing at high intensity, not a habit.',
  },
  {
    id: 'p056',
    theme: 'sport',
    q: 'Why is a tie in chess called a draw, and why are there several ways to reach one?',
    a: 'Stalemate, repetition, insufficient material, the fifty-move rule and agreement',
    note: 'Stalemate was once a win for the stalemating side. Making it a draw changed the endgame entirely.',
  },
  {
    id: 'p057',
    theme: 'sport',
    q: 'Why do cricketers polish one side of the ball on their trousers?',
    a: 'The asymmetry produces swing',
    note: 'Entirely legal with sweat and spit; anything else is not. The line is about what you apply.',
  },
  {
    id: 'p058',
    theme: 'sport',
    q: 'Why is the Olympic flame lit in Greece and carried to the host city?',
    a: 'A link to the ancient games — the relay itself was invented in 1936',
    note: 'The lighting ceremony is 1928; the torch relay was a Berlin innovation with a specific political purpose.',
  },
  {
    id: 'p059',
    theme: 'sport',
    q: 'Why does a boomerang return, and what shape is it in cross-section?',
    a: 'Each arm is an aerofoil, and the spin precesses the flight path',
    note: 'Hunting boomerangs do not return. The returning kind is a toy and a training device.',
  },
  {
    id: 'p060',
    theme: 'sport',
    q: 'Why do marathon runners take on liquid in small amounts rather than drinking deeply?',
    a: 'The gut absorbs slowly, and over-drinking risks hyponatraemia',
    note: 'The risk of drinking too much is now taken more seriously than the risk of too little.',
  },
  {
    id: 'p061',
    theme: 'sport',
    q: 'Why does a football’s pressure matter so much to how it plays?',
    a: 'It changes the bounce, the speed off the boot and the swerve',
    note: 'The laws specify a range. A ball at the bottom of it plays like a different object.',
  },
  {
    id: 'p062',
    theme: 'sport',
    q: 'Why are there weight classes in combat sports but not in most others?',
    a: 'Mass converts directly into advantage when the opponent is the obstacle',
    note: 'Rowing has them too, for the same reason: the boat carries whatever you weigh.',
  },
  {
    id: 'p063',
    theme: 'sport',
    q: 'Why is a "sudden death" overtime considered unfair by many statisticians?',
    a: 'The coin toss can decide it before both sides have had possession',
    note: 'Several leagues have changed the rule specifically to guarantee both teams a chance.',
  },
  {
    id: 'p064',
    theme: 'sport',
    q: 'Why does a curling stone curl, and why is the physics still argued about?',
    a: 'The rotation and the ice interact — the standard friction explanation predicts the wrong direction',
    note: 'A stone curls the way it turns, which is the opposite of a spinning glass on a table.',
  },
  {
    id: 'p065',
    theme: 'sport',
    q: 'Why do sweepers sweep in front of a curling stone?',
    a: 'It briefly melts the surface, reducing friction and straightening the path',
    note: 'It can add several metres. The brushes themselves have been regulated after an equipment scandal.',
  },
  {
    id: 'p066',
    theme: 'sport',
    q: 'Why is the modern pentathlon made up of those five specific events?',
    a: 'They imagine a nineteenth-century courier behind enemy lines',
    note: 'Ride an unfamiliar horse, fence, shoot, swim a river and run. Coubertin’s idea, and it shows.',
  },
  {
    id: 'p067',
    theme: 'sport',
    q: 'Why do runners on a curved track start at staggered positions?',
    a: 'The outer lanes are longer',
    note: 'The stagger is calculated so every lane runs the same distance. It is pure geometry.',
  },
  {
    id: 'p068',
    theme: 'sport',
    q: 'Why does a football referee add "stoppage time" rather than stopping the clock?',
    a: 'Tradition, and it keeps the game flowing',
    note: 'Most other sports stop the clock. Football’s approach makes the added time a judgement call and a grievance.',
  },
  {
    id: 'p069',
    theme: 'sport',
    q: 'Why is a squash ball warmed up before play?',
    a: 'Cold, it barely bounces',
    note: 'The dots on the ball indicate how much it needs. The warm-up is part of the game, not a courtesy.',
  },
  {
    id: 'p070',
    theme: 'sport',
    q: 'Why do most athletes in explosive sports have a higher proportion of one muscle fibre type?',
    a: 'Fast-twitch fibres — powerful and quick to fatigue',
    note: 'The proportion is largely genetic. Training shifts it much less than most people assume.',
  },
  {
    id: 'p071',
    theme: 'sport',
    q: 'Why is doping so hard to police, in one structural sentence?',
    a: 'Tests can only look for things already known and defined',
    note: 'Designer steroids were used for years before anyone knew to test. The tester is always behind.',
  },
  {
    id: 'p072',
    theme: 'sport',
    q: 'Why do rowers in an eight not all pull at the same instant, quite?',
    a: 'They do — the boat’s speed varies enormously through the stroke anyway',
    note: 'The hull decelerates on the recovery. Rowing is a very inefficient-looking way to be very fast.',
  },
  {
    id: 'p073',
    theme: 'sport',
    q: 'Why is a badminton shuttlecock so much slower over distance than a ball, despite leaving the racket faster?',
    a: 'Enormous drag from the skirt',
    note: 'It is the fastest racket sport at impact and among the slowest at the other end of the court.',
  },
  {
    id: 'p074',
    theme: 'sport',
    q: 'Why does a football goal have a net?',
    a: 'To prove the ball went in',
    note: 'Patented in 1889 after disputes. A remarkably late addition to a very old game.',
  },
  {
    id: 'p075',
    theme: 'sport',
    q: 'Why do skiers wax their skis differently for different snow?',
    a: 'The friction that melts a lubricating water layer varies with temperature',
    note: 'Skis do not slide on snow; they slide on a microscopic film of water they create.',
  },
  {
    id: 'p076',
    theme: 'sport',
    q: 'Why is a "personal best" a more meaningful measure for most athletes than a placing?',
    a: 'It controls for the field you happened to be in',
    note: 'A place depends on who turned up. The clock does not care.',
  },
  {
    id: 'p077',
    theme: 'sport',
    q: 'Why do football clubs have a "transfer window" rather than year-round trading?',
    a: 'To stop squads changing mid-competition and distorting it',
    note: 'Introduced across Europe in 2002 after a dispute about freedom of movement.',
  },
  {
    id: 'p078',
    theme: 'sport',
    q: 'Why is the marathon’s finishing time so much closer between men and women than the 100 metres?',
    a: 'Endurance differences are smaller than explosive power differences',
    note: 'The gap narrows further at ultra distances, where it occasionally disappears.',
  },
  {
    id: 'p079',
    theme: 'sport',
    q: 'Why are tennis balls sold in pressurised tubes?',
    a: 'The internal pressure leaks out and the ball goes dead',
    note: 'An opened tin has a shelf life of weeks. Pressureless balls exist and feel wrong to most players.',
  },
  {
    id: 'p080',
    theme: 'sport',
    q: 'Why does a boxer "roll with" a punch?',
    a: 'Moving with it reduces the deceleration and therefore the force',
    note: 'The same physics as bending your knees on landing. You are lengthening the collision.',
  },
  {
    id: 'p081',
    theme: 'sport',
    q: 'Why is the offside line in rugby different from football’s?',
    a: 'It is behind the ball, because passing forward is illegal',
    note: 'Two sports solving the same problem — stopping players camping — in opposite ways.',
  },
  {
    id: 'p082',
    theme: 'sport',
    q: 'Why do cyclists shave their legs?',
    a: 'Mostly for treating road rash and massage — the aerodynamic gain is small but real',
    note: 'Wind tunnel tests found a measurable saving, which surprised everybody including the riders.',
  },
  {
    id: 'p083',
    theme: 'sport',
    q: 'Why is a snooker table cloth brushed and ironed in one direction?',
    a: 'The nap affects how the ball runs',
    note: 'A slow shot up the table behaves differently from the same shot down it.',
  },
  {
    id: 'p084',
    theme: 'sport',
    q: 'Why do football penalties get taken from twelve yards specifically?',
    a: 'It was set in 1902 as a distance judged fair to both',
    note: 'The penalty kick itself was introduced in 1891, and was considered ungentlemanly to need.',
  },
  {
    id: 'p085',
    theme: 'sport',
    q: 'Why does a diver enter the water with as little splash as possible, and what is the technique called?',
    a: 'The rip entry — flat hands make a hole the body follows',
    note: 'It looks like it should hurt more. It is actually the safest way in at that speed.',
  },
  {
    id: 'p086',
    theme: 'sport',
    q: 'Why does a football team playing at altitude have an advantage over a visiting one?',
    a: 'Acclimatisation takes weeks',
    note: 'La Paz is at 3,600 metres. FIFA briefly banned matches above 2,500 and had to back down.',
  },
  {
    id: 'p087',
    theme: 'sport',
    q: 'Why is a Formula 1 pit stop faster than a road-car tyre change by a factor of about a thousand?',
    a: 'A single central nut, pre-positioned crew and heated tyres',
    note: 'Under two seconds, with about twenty people each doing one thing.',
  },
  {
    id: 'p088',
    theme: 'sport',
    q: 'Why do sports leagues use a draft that favours the worst teams?',
    a: 'Competitive balance — a league of foregone conclusions loses its audience',
    note: 'It also creates an incentive to lose deliberately, which leagues then have to police.',
  },
  {
    id: 'p089',
    theme: 'sport',
    q: 'Why is a "golden goal" no longer used in football?',
    a: 'It made teams play defensively rather than attack',
    note: 'It was intended to encourage attacking play and produced exactly the opposite.',
  },
  {
    id: 'p090',
    theme: 'sport',
    q: 'Why do runners "hit the wall" at around 30 km in a marathon?',
    a: 'Stored glycogen runs out at roughly that point',
    note: 'Which is why the race is often described as a 30 km run followed by a 12 km problem.',
  },
  {
    id: 'p091',
    theme: 'sport',
    q: 'Why does a ski jumper hold the skis in a V rather than parallel?',
    a: 'It generates more lift',
    note: 'Boklöv was ridiculed and scored down for it in the 1980s. Within a decade everybody did it.',
  },
  {
    id: 'p092',
    theme: 'sport',
    q: 'Why is a chess grandmaster’s advantage over an amateur mostly about memory rather than calculation?',
    a: 'They recognise patterns, not individual pieces',
    note: 'Shown by de Groot: masters recall real positions far better and random ones no better at all.',
  },
  {
    id: 'p093',
    theme: 'sport',
    q: 'Why do stadiums use a "safe standing" design in some countries and forbid standing in others?',
    a: 'Crowd disasters led to all-seater rules; rail seating is the engineered compromise',
    note: 'Hillsborough in 1989 is the reason British grounds became all-seater.',
  },
  {
    id: 'p094',
    theme: 'sport',
    q: 'Why does a runner’s split time often improve in the second half of a well-run race?',
    a: 'Negative splitting — most people start too fast',
    note: 'Nearly every distance world record has been set with a faster second half.',
  },
  {
    id: 'p095',
    theme: 'sport',
    q: 'Why is a "clean sheet" a goalkeeper’s statistic when defence is a team activity?',
    a: 'It is a team result credited to an individual — and it is a known weakness of the metric',
    note: 'A keeper behind a dominant team gets more of them without touching the ball.',
  },
  {
    id: 'p096',
    theme: 'sport',
    q: 'Why is the pole in pole vault allowed to be any length and stiffness the athlete wants?',
    a: 'The athlete has to carry, plant and control it — the pole is not free advantage',
    note: 'A stiffer pole returns more energy and requires more speed to bend at all.',
  },
  {
    id: 'p097',
    theme: 'sport',
    q: 'Why did the Fosbury flop become possible only in the 1960s?',
    a: 'Foam landing pits replaced sand and sawdust',
    note: 'You cannot land on your neck in a sandpit. The equipment enabled the technique.',
  },
  {
    id: 'p098',
    theme: 'sport',
    q: 'Why do football commentators talk about "expected goals", and what is it measuring?',
    a: 'The quality of chances rather than the outcome',
    note: 'It reduces the noise of finishing. Over a season it predicts results better than the results do.',
  },
  {
    id: 'p099',
    theme: 'sport',
    q: 'Why is there no world record for the marathon on any course, unlike the track?',
    a: 'Courses differ — records require strict criteria on drop and start-finish separation',
    note: 'Boston’s times do not count as records because the course is net downhill and point to point.',
  },
  {
    id: 'p100',
    theme: 'sport',
    q: 'Why is the phrase "it is a game of two halves" more true than it sounds, tactically?',
    a: 'Teams adjust at half time with information they did not have at kick-off',
    note: 'It is the only scheduled point at which a manager can talk to everybody at once.',
  },
]
