/**
 * Words — etymology, naming, and the history hiding inside ordinary vocabulary.
 *
 * The easiest theme to write badly: "what does this word mean" is a dictionary, not a game.
 * Every question here works the other way round — it describes the *thing* and asks for the
 * word, or gives the word's history and asks what it must originally have described. Both
 * are reachable by thinking, which is the whole test.
 */
import type { Question } from '../types'

export const WORDS: readonly Question[] = [
  {
    id: 'w001',
    theme: 'words',
    q: 'Sailors measured depth by dropping a lead weight on a knotted rope. Two marks meant safe water for a riverboat. What phrase, still used for something perfectly adequate, comes from that measurement?',
    a: 'Mark twain',
    note: 'Two fathoms — safe, but only just. Samuel Clemens took his pen name from the call.',
  },
  {
    id: 'w002',
    theme: 'words',
    q: 'The word comes from the Greek for "not cut". It was chosen because the thing it names was believed to be the smallest possible piece of matter. What word?',
    a: 'Atom',
    note: 'From "a-tomos", uncuttable. The name outlived the belief by about a century.',
  },
  {
    id: 'w003',
    theme: 'words',
    q: 'Roman soldiers were sometimes paid an allowance for a particular commodity that was hard to get and essential to preserving food. What English word for wages comes from it?',
    a: 'Salary',
    note: 'From "sal", salt. It is also why somebody good is "worth their salt".',
  },
  {
    id: 'w004',
    theme: 'words',
    q: 'This word for a sudden commercial success originally described a very large bomb — one big enough to destroy an entire city block. What word?',
    a: 'Blockbuster',
    note: 'RAF slang from the Second World War, borrowed by Hollywood about fifteen years later.',
  },
  {
    id: 'w005',
    theme: 'words',
    q: 'Bookmakers once wrote the odds on a board. A horse whose odds nobody could work out because the animal was unknown gave us a phrase for an unexpected winner. What phrase?',
    a: 'A dark horse',
    note: 'Coined by Disraeli in a novel, about a horse "of which nothing was known".',
  },
  {
    id: 'w006',
    theme: 'words',
    q: 'The word means "to breathe into". It was used for the moment a god was thought to breathe an idea into a person. What word, now used of any good idea, is it?',
    a: 'Inspiration',
    note: 'The same root as "respiration". Taking a breath and having an idea are the same word.',
  },
  {
    id: 'w007',
    theme: 'words',
    q: 'A medieval English tax assessor counted these to work out what a household owed, because they were hard to hide and scaled with the size of the house. What did they count?',
    a: 'Hearths (or chimneys)',
    note: 'The hearth tax. You cannot hide a chimney, which is exactly why it was chosen.',
  },
  {
    id: 'w008',
    theme: 'words',
    q: 'This word for an enthusiastic supporter is a shortening of a word meaning "of the temple" — and originally implied someone excessively, even dangerously, devoted. What word?',
    a: 'Fan',
    note: 'From "fanatic", from "fanum", a temple. The short form arrived with baseball.',
  },
  {
    id: 'w009',
    theme: 'words',
    q: 'Sixteenth-century glassmakers could not make a large sheet without a flaw, so the cheapest, most distorted piece — the one at the centre where the rod had been — went into the cheapest windows. What is that piece called?',
    a: 'A bullseye (bull’s-eye pane)',
    note: 'Now sold at a premium as "period character", which the original buyers would find funny.',
  },
  {
    id: 'w010',
    theme: 'words',
    q: 'The English word for this piece of furniture comes from the French for "to sit". The French word for the same object comes from the English for a place to store things. Name either.',
    a: 'Chair, or "chaise"; and the French use "commode" and "dressing"',
    note: 'Furniture words cross the Channel constantly and both sides think the other’s is fancier.',
  },
  {
    id: 'w011',
    theme: 'words',
    q: 'A "clue" was originally a ball of thread. Which Greek myth explains exactly how a ball of thread came to mean a piece of evidence?',
    a: 'Theseus and the Minotaur',
    note: 'Ariadne’s thread. Following the clew out of the labyrinth is literally following a clue.',
  },
  {
    id: 'w012',
    theme: 'words',
    q: 'This word for something extremely small comes from the name of a coin that was itself worth so little that it was proverbially the smallest thing anybody could give. What word?',
    a: 'Mite',
    note: 'The widow’s mite. The tiny arachnid is named after the coin, not the other way round.',
  },
  {
    id: 'w013',
    theme: 'words',
    q: 'Because Dutch traders were commercial rivals, English acquired a set of phrases using their name to mean something fake, unfair or cowardly. Name any two.',
    a: 'Dutch courage, going Dutch, double Dutch, Dutch uncle',
    note: 'Seventeenth-century trash talk that outlived the wars by three hundred years.',
  },
  {
    id: 'w014',
    theme: 'words',
    q: 'The word describes a person who has been thrown out of an aeroplane, a company or a conversation — but its literal root means "to place outside". What single word covers all three?',
    a: 'Eject (or ejected)',
    note: 'Same root as "jettison" and "project": to throw.',
  },
  {
    id: 'w015',
    theme: 'words',
    q: 'This word for a hospital ward comes from the same root as the word for a place where sick people were kept apart for exactly forty days. What number is hiding in it?',
    a: 'Forty — quarantine',
    note: 'From the Italian "quaranta giorni". A thirty-day version, "trentine", came first and was found too short.',
  },
  {
    id: 'w016',
    theme: 'words',
    q: 'A "sandwich" is named after a man who wanted to keep doing something without stopping to eat. What was he doing?',
    a: 'Gambling (playing cards)',
    note: 'The Earl of Sandwich. The rival story — he was working at his desk — is duller and probably true.',
  },
  {
    id: 'w017',
    theme: 'words',
    q: 'The English name for this animal means "earth pig", and it is borrowed unchanged from Afrikaans. It is also famously the first word in many dictionaries. What is it?',
    a: 'Aardvark',
    note: 'It is not a pig, and it is not related to one. It is the only survivor of its entire order.',
  },
  {
    id: 'w018',
    theme: 'words',
    q: 'In printing, a large capital letter at the start of a chapter that sinks into the first few lines of text has a name that describes what it does to the line. What is it called?',
    a: 'A drop cap',
    note: 'Its opposite, sitting on the line and rising above it, is a "raised cap".',
  },
  {
    id: 'w019',
    theme: 'words',
    q: 'The word for a book’s introduction and the word for a stage in a play both come from the same Greek root meaning "before the word". Name either.',
    a: 'Prologue (and preface)',
    note: '"Pro-logos". An epilogue is the same word with "after".',
  },
  {
    id: 'w020',
    theme: 'words',
    q: 'This word for a small mistake is also a word for a slip of paper, and the connection is that both were originally something that had come loose and fallen out. What word?',
    a: 'Slip',
    note: 'From the same root as "slippery". A slip of paper has slipped out of something.',
  },
  {
    id: 'w021',
    theme: 'words',
    q: 'A "curfew" was originally an instruction to do something very specific at a set hour, and the French phrase behind it says exactly what. What were people told to do?',
    a: 'Cover the fire',
    note: '"Couvre-feu". Banking the hearth at night stopped a whole timber town burning down.',
  },
  {
    id: 'w022',
    theme: 'words',
    q: 'This word for one of a pair of matching things comes from a Latin word meaning "companion", and survives almost only in the phrase "without ___". What word?',
    a: 'Peer',
    note: 'From "par", equal. "Without peer" means having no equal, not having no friends.',
  },
  {
    id: 'w023',
    theme: 'words',
    q: 'Three English words for a period of time come from words meaning "moon". Give any one.',
    a: 'Month (also "menses", "moon" itself)',
    note: 'The month is the moon. Almost every calendar started as a way of counting it.',
  },
  {
    id: 'w024',
    theme: 'words',
    q: 'A "silhouette" is named after a French finance minister. What quality of his brief and unpopular tenure gave the word its meaning?',
    a: 'Extreme cheapness (austerity)',
    note: 'Étienne de Silhouette taxed the rich and cut spending. A cut-paper profile was the portrait you could afford.',
  },
  {
    id: 'w025',
    theme: 'words',
    q: 'The word for the space between two buildings, the word for a narrow sea passage, and the word for a difficult situation are all the same English word. Which?',
    a: 'Strait (or "straits")',
    note: 'From "strictus", narrow. Dire straits are literally a tight spot.',
  },
  {
    id: 'w026',
    theme: 'words',
    q: 'This musical instruction, written at the top of a score, is Italian for "cheerful" — but musicians treat it purely as an instruction about speed. Which?',
    a: 'Allegro',
    note: 'Most tempo marks are moods, not speeds. "Largo" means broad; "grave" means serious.',
  },
  {
    id: 'w027',
    theme: 'words',
    q: 'Two English words for the same colour come from two different plants used to dye cloth. One is a Latin word for the country the plant came from; the other is the plant. Name either colour word.',
    a: 'Indigo (from India), or woad',
    note: 'They produce chemically identical dye. Woad was European; indigo undercut it and won.',
  },
  {
    id: 'w028',
    theme: 'words',
    q: 'A "muscle" is named after a small animal, because of what a flexing bicep was thought to look like moving under the skin. What animal?',
    a: 'A mouse',
    note: 'From "musculus", little mouse. Once you have seen it you cannot unsee it.',
  },
  {
    id: 'w029',
    theme: 'words',
    q: 'This word for a formal complaint shares its root with the word "grave" — not the burial kind, but the one meaning heavy. What word?',
    a: 'Grievance',
    note: 'To grieve is to be weighed down. A grievance is a heaviness you have handed to somebody else.',
  },
  {
    id: 'w030',
    theme: 'words',
    q: 'The word "companion" is built from two Latin pieces that together describe a very specific shared activity. What activity?',
    a: 'Eating bread together',
    note: '"Com-panis". The people you break bread with. The Spanish "compañero" is the same idea.',
  },
  {
    id: 'w031',
    theme: 'words',
    q: 'Why does the English word for the number after eleven not follow the pattern of "thirteen", "fourteen" and the rest?',
    a: 'Because twelve, like eleven, means "leftover" after counting ten',
    note: '"Twe-lif" — two left. Old Germanic counting ran out of names at ten and improvised twice.',
  },
  {
    id: 'w032',
    theme: 'words',
    q: 'A "chapel" is named after half a cloak. Whose, and why half?',
    a: 'Saint Martin’s — he cut it in two to share with a beggar',
    note: 'The relic was kept in a "cappella". Its keeper was the "chaplain".',
  },
  {
    id: 'w033',
    theme: 'words',
    q: 'This word for enormous comes from the name of a biblical creature, and its partner word for something enormous at sea comes from a different one. Name either.',
    a: 'Behemoth (land) or Leviathan (sea)',
    note: 'Job names both. Hobbes borrowed the sea one for the state and the land one for the church.',
  },
  {
    id: 'w034',
    theme: 'words',
    q: 'The English word for a person who writes a dictionary was defined by one such person as "a harmless drudge". Who wrote that definition?',
    a: 'Samuel Johnson',
    note: 'His definition of "lexicographer", in his own dictionary. He also defined "oats" as food for horses and Scotsmen.',
  },
  {
    id: 'w035',
    theme: 'words',
    q: 'Two body parts share a name with two parts of a shoe, and a third shares its name with part of a mountain. Give any pair.',
    a: 'Tongue and sole; heel and heel; foot of a mountain',
    note: 'Bodies are the oldest metaphor there is. Every landscape has a mouth, a neck and a head.',
  },
  {
    id: 'w036',
    theme: 'words',
    q: 'This punctuation mark is named from the Greek for "to cut off", because it marks where letters have been removed. What is it?',
    a: 'The apostrophe',
    note: 'Which is why "it’s" has one and "its" does not: nothing has been cut out of "its".',
  },
  {
    id: 'w037',
    theme: 'words',
    q: 'A "posh" origin story says it stood for a booking preference on ships to India. Why do etymologists reject it?',
    a: 'No ticket or record showing the abbreviation has ever been found',
    note: '"Port Out, Starboard Home" is a beautiful story invented long after the word appeared.',
  },
  {
    id: 'w038',
    theme: 'words',
    q: 'The English words for a large body of salt water and for the ability to understand differ by one letter and are unrelated — but a third word means both a stretch of water and a bishop’s office. Which?',
    a: 'See',
    note: 'A bishop’s see is his seat, from "sedes". Nothing to do with the sea or with seeing.',
  },
  {
    id: 'w039',
    theme: 'words',
    q: 'This word for a small amount of money comes from a word for a small change of clothes — specifically, what was left over. Which word do we still use for loose coins?',
    a: 'Change',
    note: 'What comes back is what has been exchanged. The coins are named after the transaction.',
  },
  {
    id: 'w040',
    theme: 'words',
    q: 'Two European languages call the colour orange after the fruit; English does too. What did English speakers call that colour before the fruit arrived?',
    a: 'Yellow-red (“geoluread”)',
    note: 'The fruit named the colour, not the other way round. Robins were "redbreasts" for the same reason.',
  },
  {
    id: 'w041',
    theme: 'words',
    q: 'A "nightmare" contains an old word that has nothing to do with horses. What did that word mean?',
    a: 'A crushing spirit that sits on a sleeper’s chest',
    note: 'The "mara". Sleep paralysis, given a name and a face, long before it had an explanation.',
  },
  {
    id: 'w042',
    theme: 'words',
    q: 'The word "sarcasm" comes from a Greek verb describing something rather more violent than speech. What does the verb mean?',
    a: 'To tear flesh',
    note: '"Sarkazein", from "sarx", flesh — the same root as "sarcophagus", the flesh-eating stone.',
  },
  {
    id: 'w043',
    theme: 'words',
    q: 'This word for a fixed way of doing things is a printing term for a whole page cast as one solid plate, so that it could not be altered. What word?',
    a: 'Stereotype',
    note: 'A cliché is the same idea in French — the sound the plate made when cast.',
  },
  {
    id: 'w044',
    theme: 'words',
    q: 'Name the only English word in common use that is its own opposite in the phrases "the alarm went off" and "the milk went off" — or give any other word that means two contradictory things.',
    a: 'Off (also: cleave, sanction, dust, oversight)',
    note: 'They are called contronyms, or Janus words, after the god with two faces.',
  },
  {
    id: 'w045',
    theme: 'words',
    q: 'A "boycott" is named after a man who had it done to him. What was his job?',
    a: 'A land agent (estate manager) in Ireland',
    note: 'Captain Charles Boycott, 1880. His tenants simply stopped dealing with him, and gave the tactic his name within weeks.',
  },
  {
    id: 'w046',
    theme: 'words',
    q: 'This word for a public square, a shopping centre and a computer error all come from the same root meaning "to strike". Which word means the error?',
    a: 'Bug is not it — the answer is "crash"; the shared root word is "plaza/piazza/place" from "platea"',
    note: 'Accept "place": plaza, piazza and place are the same word taking three routes into English.',
    hard: true,
  },
  {
    id: 'w047',
    theme: 'words',
    q: 'A "tabloid" was originally a trademarked product sold by a pharmaceutical company. What kind of product?',
    a: 'A compressed pill (tablet)',
    note: 'Burroughs Wellcome. "Tabloid journalism" meant news compressed into a small dose — a compliment at first.',
  },
  {
    id: 'w048',
    theme: 'words',
    q: 'Why is the "e" in "one" pronounced nothing like the "e" in "gone", although both words are spelled the same way at the end?',
    a: 'Because "one" acquired a "w" sound in speech that the spelling never recorded',
    note: 'It is why "only" and "alone" — both from the same word — sound so different.',
  },
  {
    id: 'w049',
    theme: 'words',
    q: 'This word describes both a piece of a fireplace and a stubborn person, and the link is that both are hard to shift. What word?',
    a: 'Brick — accept "grate"/"grating" as a near miss',
    note: 'Calling somebody "a brick" was Victorian praise: solid, dependable, part of the wall.',
  },
  {
    id: 'w050',
    theme: 'words',
    q: 'The word "robot" was coined for a 1920 play. What does it mean in the playwright’s language, and what does that tell you about the play’s politics?',
    a: 'Forced labour — the play is about a workers’ revolt',
    note: 'Čape’s "R.U.R.". His brother Josef suggested the word. The robots win.',
  },
  {
    id: 'w051',
    theme: 'words',
    q: 'Which everyday English word for a person’s name is also the word for a set of clothes, because both were originally what you were "given" to wear or be called?',
    a: 'Handle is the slang; the answer is "title"',
    note: 'Accept "style": a person’s style was both their manner of dress and their formal form of address.',
    hard: true,
  },
  {
    id: 'w052',
    theme: 'words',
    q: 'A "decimation" was a Roman military punishment. Exactly what fraction of the unit was killed, and how were they chosen?',
    a: 'One in ten, chosen by lot',
    note: 'By their own comrades. The point was not the deaths but that everybody was a possible executioner.',
  },
  {
    id: 'w053',
    theme: 'words',
    q: 'This word for excellent comes from the name of a Greek city whose inhabitants had a reputation for it — and the same city gives us a word for its opposite. Name either.',
    a: 'Laconic (Laconia/Sparta); the opposite is "sybaritic" from Sybaris',
    note: 'Spartans were famously terse; Sybarites famously not. Both cities became adjectives.',
  },
  {
    id: 'w054',
    theme: 'words',
    q: 'Why does English use "pound" for both a weight and a unit of money, and what does the abbreviation £ actually stand for?',
    a: 'Because a pound was originally a pound weight of silver; £ is a stylised "L" for "libra"',
    note: 'lb is the same libra. The pound sterling was once a real pound of the stuff.',
  },
  {
    id: 'w055',
    theme: 'words',
    q: 'The word "sincere" is often said to come from a phrase about wax used to hide cracks in marble. Why do etymologists doubt it?',
    a: 'The Latin roots do not support it — it is a folk etymology',
    note: '"Sine cera" is a lovely story with no evidence. It survives because it is more memorable than the truth.',
  },
  {
    id: 'w056',
    theme: 'words',
    q: 'A word meaning "to walk about" gave English a word for a type of philosopher. Which school, and why did they walk?',
    a: 'The Peripatetics — Aristotle taught while walking the colonnade',
    note: 'The "peripatos" was the covered walk at the Lyceum. The school is named after the architecture.',
  },
  {
    id: 'w057',
    theme: 'words',
    q: 'This word for a slow, difficult journey comes from a Dutch word for a single day’s travel by ox wagon. What word?',
    a: 'Trek',
    note: 'From Afrikaans. The Great Trek was a very large number of those days in a row.',
  },
  {
    id: 'w058',
    theme: 'words',
    q: 'Two words for a dead language’s influence on English: one names the language of the Roman empire, the other names a hill in Athens. Give the second.',
    a: 'Attic',
    note: 'The top room is "Attic" because the style of its decorative order came from Attica.',
    hard: true,
  },
  {
    id: 'w059',
    theme: 'words',
    q: 'What do the words "assassin", "algebra" and "alcohol" have in common besides all being English?',
    a: 'All entered English from Arabic',
    note: 'The "al-" is the definite article. "Algebra" is "al-jabr", the reunion of broken parts.',
  },
  {
    id: 'w060',
    theme: 'words',
    q: 'A "pedigree" is named after the shape a family tree makes on the page, and the French phrase behind it names a bird. Which bird, and which part of it?',
    a: 'A crane’s foot ("pied de grue")',
    note: 'Three lines meeting at a point — exactly how a descent line branches.',
  },
  {
    id: 'w061',
    theme: 'words',
    q: 'The English word "news" is often said to be an acronym of the compass points. What is the real explanation?',
    a: 'It is simply the plural of "new" — new things',
    note: 'A good rule: almost no word older than the twentieth century is an acronym.',
  },
  {
    id: 'w062',
    theme: 'words',
    q: 'This word for a chief or leader is used in English, and in its original language it means simply "old man". What word?',
    a: 'Sheikh (also "senator", "senior", "sire" from the same idea)',
    note: 'Nearly every word for authority is a word for age. "Alderman" is "elder man".',
  },
  {
    id: 'w063',
    theme: 'words',
    q: 'What single change to a word turns a place where ships are repaired into a place where a defendant stands, and why is it the same word?',
    a: 'None — "dock" is the same word; both are enclosed spaces',
    note: 'The dock in a court is an enclosure, from Flemish "dok", a cage or pen.',
  },
  {
    id: 'w064',
    theme: 'words',
    q: 'The word "kidnap" is a compound of two slang words. What did the second one mean?',
    a: 'To snatch or steal ("nab")',
    note: 'And "kid" meant child. The word was coined for stealing children to ship to the American colonies.',
  },
  {
    id: 'w065',
    theme: 'words',
    q: 'A "tragedy" is named, according to the usual etymology, after an animal. Which, and give either explanation of why.',
    a: 'A goat — either the prize for the winning play, or the animal sacrificed',
    note: '"Tragos-oide", goat-song. Nobody is sure which explanation is right, which is oddly fitting.',
  },
  {
    id: 'w066',
    theme: 'words',
    q: 'This word for an official record shares its origin with the word for a ship’s roll call, and both come from a word meaning a small wheel. What word?',
    a: 'Roll (and "role", "enrol", "roster")',
    note: 'A record was a rolled scroll. An actor’s role was their part written on one.',
  },
  {
    id: 'w067',
    theme: 'words',
    q: 'What is the connection between the word "muscat", the word "musket" and the word "mosquito"?',
    a: 'Nothing etymologically — but "musket" and "mosquito" both come from words for small flies',
    note: 'A musket was named after a sparrowhawk; "mosquito" is Spanish for little fly. Accept the fly link.',
    hard: true,
  },
  {
    id: 'w068',
    theme: 'words',
    q: 'The English word "gossip" originally described a specific relationship between two adults and a child. What relationship?',
    a: 'Godparent',
    note: '"God-sibb", related in God. The word slid from the person to what they did at the christening.',
  },
  {
    id: 'w069',
    theme: 'words',
    q: 'A "quarantine" is forty days. A "fortnight" is fourteen nights. What period of time does "sennight" describe, and why has it vanished?',
    a: 'A week — seven nights; "week" simply won',
    note: 'English counted in nights, not days. "Fortnight" is the last survivor of the habit.',
  },
  {
    id: 'w070',
    theme: 'words',
    q: 'This word for an obvious statement comes from a Greek word for a place, because such statements are the common ground everybody stands on. What word?',
    a: 'Topic — accept "commonplace"',
    note: 'From "topos", place. Aristotle’s "Topics" is a list of the standard places to find an argument.',
  },
  {
    id: 'w071',
    theme: 'words',
    q: 'Why does the English name for the bird "turkey" refer to a country the bird has never lived in?',
    a: 'It was confused with the guineafowl, imported through Turkey',
    note: 'The Turks call it "hindi", meaning Indian. Almost every language blames somewhere else.',
  },
  {
    id: 'w072',
    theme: 'words',
    q: 'This word for the highest point of anything is, in its original use, a term for the moment in a story when everything is at its most tense. What word?',
    a: 'Climax',
    note: 'From the Greek for ladder. It meant the rising steps, not the top one — the modern sense reverses it.',
  },
  {
    id: 'w073',
    theme: 'words',
    q: 'A "chauffeur" is French for a person who does something a modern driver never does. What?',
    a: 'Stokes a fire (heats)',
    note: 'Early cars were steam-driven. The person who kept the boiler going kept the name.',
  },
  {
    id: 'w074',
    theme: 'words',
    q: 'The English words "guest" and "host" and the word "hostile" all come from one root. What did that root mean, and why does it cover both?',
    a: 'Stranger — a stranger is either a guest or an enemy',
    note: 'Latin "hostis" went one way, "hospes" the other. The ambiguity is the whole history of hospitality.',
  },
  {
    id: 'w075',
    theme: 'words',
    q: 'This word for a large public building comes from a Greek word meaning "royal", though the buildings it names in English are almost never royal. What word?',
    a: 'Basilica',
    note: 'A Roman civic hall, borrowed wholesale by the early church because the shape suited a crowd.',
  },
  {
    id: 'w076',
    theme: 'words',
    q: 'What do the words "denim", "jeans" and "duffel" all have in common?',
    a: 'Each is named after the town the cloth came from',
    note: 'De Nîmes, Genoa, and Duffel in Belgium. Cloth is nearly always named after a place.',
  },
  {
    id: 'w077',
    theme: 'words',
    q: 'The word "curious" once meant something about the person doing the looking that it no longer means. What?',
    a: 'Careful, painstaking',
    note: 'Same root as "cure" and "curate": taking care. A curious person took pains, before they took an interest.',
  },
  {
    id: 'w078',
    theme: 'words',
    q: 'This English word for a rebellion is borrowed from a Hindi word for a soldier’s uprising, and entered the language in 1857. What word?',
    a: 'Mutiny is English; the answer is "sepoy" as the soldier — accept "the Indian Mutiny"',
    note: 'Accept "sepoy", from Persian "sipahi", soldier. The same root gives the Turkish "spahi".',
    hard: true,
  },
  {
    id: 'w079',
    theme: 'words',
    q: 'A "pamphlet" is named after a twelfth-century poem so widely copied that its title became the word for any short booklet. What was the poem about?',
    a: 'Love',
    note: '"Pamphilus, seu de Amore" — Pamphilus, or On Love. The first viral document.',
  },
  {
    id: 'w080',
    theme: 'words',
    q: 'Which everyday English word began as a brand name for a vacuum flask, and which as a brand for a cotton bud? Give either.',
    a: 'Thermos, or Q-tip — accept "hoover", "biro", "escalator"',
    note: 'Escalator is the surprising one: Otis lost the trademark by using it generically in its own adverts.',
  },
  {
    id: 'w081',
    theme: 'words',
    q: 'This word for a formal agreement is built from a root meaning "to draw together", and the same root gives us a word for what happens to muscles. What word?',
    a: 'Contract',
    note: 'The document and the muscle do the same thing: pull tight.',
  },
  {
    id: 'w082',
    theme: 'words',
    q: 'The word "villain" originally described a person’s legal status, not their morals. What status?',
    a: 'A farm worker tied to an estate',
    note: 'From "villa". The slide from "peasant" to "criminal" is a small, ugly piece of social history.',
  },
  {
    id: 'w083',
    theme: 'words',
    q: 'Which two words in the phrase "hue and cry" are, historically, near-synonyms, and what did the phrase legally require of a bystander?',
    a: 'Both mean an outcry; bystanders were legally obliged to join the chase',
    note: 'Ignoring it was itself an offence. Medieval policing was compulsory and everybody’s job.',
  },
  {
    id: 'w084',
    theme: 'words',
    q: 'This word for a person’s characteristic manner comes from the name of a writing implement. What word?',
    a: 'Style',
    note: 'A "stilus" was the stylus you wrote on wax with. Your handwriting became your manner.',
  },
  {
    id: 'w085',
    theme: 'words',
    q: 'The words "disaster" and "influenza" both blame the same thing for human misfortune. What?',
    a: 'The stars',
    note: '"Dis-astro", a bad star; "influenza", the influence of the heavens. Both are astrology fossilised in a dictionary.',
  },
  {
    id: 'w086',
    theme: 'words',
    q: 'A "quarry" is both a place stone is cut and an animal being hunted. Are the two words related, and if not, where does the hunting one come from?',
    a: 'Unrelated — the hunted one is from the entrails given to the hounds',
    note: 'From "cuirée", the reward on the hide. The stone one is from "quadrus", a square block.',
  },
  {
    id: 'w087',
    theme: 'words',
    q: 'This word for an alphabetical list at the back of a book is also a finger. Which finger, and why that one?',
    a: 'The index finger — the one that points',
    note: 'From "indicare", to point out. The book’s index points, so it has the same name.',
  },
  {
    id: 'w088',
    theme: 'words',
    q: 'The word "nice" has meant, at various times, foolish, precise, fastidious and pleasant. What did it mean first?',
    a: 'Ignorant or foolish',
    note: 'From Latin "nescius", not knowing. It has drifted further than almost any word in English.',
  },
  {
    id: 'w089',
    theme: 'words',
    q: 'What is the connection between a "cardigan", a "raglan" sleeve and a "balaclava"?',
    a: 'All three come from the Crimean War',
    note: 'Two commanders and a battle. A single miserable winter dressed the next century.',
  },
  {
    id: 'w090',
    theme: 'words',
    q: 'This word for a book of maps is named after a figure from myth, because of what appeared on the title page of an early collection. Who?',
    a: 'Atlas',
    note: 'Mercator put him on the frontispiece. He is usually shown holding the heavens, not the earth.',
  },
  {
    id: 'w091',
    theme: 'words',
    q: 'A "shibboleth" is a word used to identify outsiders by their pronunciation. What does the original Hebrew word mean?',
    a: 'An ear of corn (or a stream)',
    note: 'Judges 12. The meaning was irrelevant — the point was that one tribe could not make the "sh".',
  },
  {
    id: 'w092',
    theme: 'words',
    q: 'Which English word for a small mark of punctuation comes from the Greek for "a stroke", and which from the Greek for "half a stop"? Give either.',
    a: 'Comma (a piece cut off) or "colon" (a limb/clause)',
    note: 'Both were originally names for pieces of a sentence, not for the marks that divide them.',
  },
  {
    id: 'w093',
    theme: 'words',
    q: 'The word "salon" and the word "saloon" are the same French word taking two routes. What happened to the second one in America?',
    a: 'It came to mean a bar',
    note: 'A grand reception room in Paris, a swing-door drinking hole in Dodge City. Same word, ninety years apart.',
  },
  {
    id: 'w094',
    theme: 'words',
    q: 'This word for a substance that speeds up a reaction without being consumed is built from Greek for "to loosen down". What word?',
    a: 'Catalyst',
    note: 'The same root as "analysis" — loosening apart. Chemistry borrowed the word from grammar.',
  },
  {
    id: 'w095',
    theme: 'words',
    q: 'Why do English speakers call the animal "pig" but the meat "pork", the animal "cow" but the meat "beef"?',
    a: 'The Anglo-Saxons farmed them and the Norman French ate them',
    note: 'Walter Scott points it out in "Ivanhoe". A whole conquest visible in a menu.',
  },
  {
    id: 'w096',
    theme: 'words',
    q: 'A "genuine" thing is, by the word’s origin, one that has been placed on something. On what, and by whom?',
    a: 'On the father’s knee — by him, acknowledging the child',
    note: 'From "genu", knee. Roman acknowledgement of paternity, preserved in a word about authenticity.',
    hard: true,
  },
  {
    id: 'w097',
    theme: 'words',
    q: 'This word for an unpleasant task shares a root with the word for a person who works in a place they do not own, and both come from a word meaning "to serve". What word?',
    a: 'Chore — accept "servitude"/"serf"',
    note: 'Accept "chare", an odd job, from the Old English for a turn of work — a "charwoman" did them.',
  },
  {
    id: 'w098',
    theme: 'words',
    q: 'The words "hospital", "hotel" and "hostel" are the same word. Which one kept the original meaning most closely, and what was it?',
    a: 'Hospital — a place of hospitality for travellers and the sick',
    note: 'They separated in French. A "hôtel-Dieu" is still a hospital, and "hôtel de ville" is the town hall.',
  },
  {
    id: 'w099',
    theme: 'words',
    q: 'What do the words "lord" and "lady" originally describe, and what does it tell you about early English households?',
    a: 'The loaf-keeper and the loaf-kneader — authority was about bread',
    note: '"Hlaford" and "hlaefdige". Whoever controlled the grain controlled the hall.',
  },
  {
    id: 'w100',
    theme: 'words',
    q: 'This English word means both a piece of unwanted email and a tinned meat, and the connection is a comedy sketch. Which show?',
    a: 'Monty Python’s Flying Circus',
    note: 'The sketch where the word drowns out all conversation — which is exactly what the email does.',
  },
]
