/**
 * Statement aggregates — CONTRACTS.md §8.
 *
 * One year of the ledger is reduced here to the ~20 numbers the "Statement of
 * Us" is written from. Everything downstream — the LLM prompt, the deterministic
 * template renderer, the stored `Statements.contentMarkdown` — reads
 * {@link StatementFacts} and never the database, which is what makes the whole
 * feature testable without an LLM and reproducible without a network.
 *
 * ## What is *not* in the facts
 *
 * No balances, no debts, no fixed pair of people. `totals.byPerson` says what each
 * person *paid*, over however many people the household has, and that is a
 * contribution rather than a claim (CONTRACTS.md §9). The system prompt below
 * says so in as many words, because a model handed a table of per-person totals
 * will otherwise cheerfully volunteer who owes whom.
 *
 * ## Where `StatementFacts` lives
 *
 * Here, next to the aggregation that produces it, because CONTRACTS.md §8 puts
 * it here. `srv/lib/llm/types.ts` re-declares the same shape for the template
 * provider, which only ever sees it as JSON inside a prompt and must not take a
 * compile-time dependency on a module that talks to a database. The two
 * declarations are structurally identical, so values flow between them freely.
 *
 * ## Why the queries are hand-written CQN
 *
 * `db.run()` accepts a CQN object, which is precisely what `SELECT.from(…)`
 * builds. Building it directly keeps this module free of a value import of
 * `@sap/cds` — so `aggregateYear()` runs against any handle with a `run()`
 * method (a `cds.deploy(…).to('sqlite::memory:')` service in the tests, the
 * ambient `cds.db` in the server) and the module stays importable from a plain
 * Node process. The queries are the exact CQN `SELECT.from('twowaymatch.Expenses')
 * .where({ status: 'confirmed', date: { between: from, and: to } })` produces.
 */

import type { MomentCode } from '#cds-models/twowaymatch'
import { CATEGORY_CODES, DEFAULT_CURRENCY, MOMENT_CODES } from './constants'
import { addDays, daysBetween, isoWeekKey, parseWhenISO } from './dates'
import { getProvider, renderStatementFromFacts } from './llm'
import type { LlmProvider } from './llm'
import { sumMoney, toAmount } from './money'

/** What one grouped occasion — a trip, a dinner, a party — came to. */
export interface EventFacts {
  name: string
  /** Everything posted to the event inside the reporting year. */
  total: number
  /** How many people were on it. Context for the prose, never an amount owed. */
  participantCount: number
}

/**
 * Aggregates the statement is written from (CONTRACTS.md §8).
 *
 * `people` and the keys of `totals.byPerson` are the same strings by
 * construction: the renderer looks a person's spend up by the name it prints.
 */
export interface StatementFacts {
  year: number
  /** Everyone who could pay for something, alphabetically. Two of them, or ten. */
  people: string[]
  currency: string
  totals: {
    overall: number
    byCategory: Record<string, number>
    /** What each person paid. A contribution, not a debt. */
    byPerson: Record<string, number>
    byMoment: Record<string, number>
  }
  counts: {
    expenses: number
    dateNights: number
    trips: number
    /** Gift postings in the year. Who gave what to whom is nobody's ledger. */
    gifts: number
  }
  /** The year's events that cost something, largest first. */
  events: EventFacts[]
  topMerchants: Array<{ merchant: string; total: number; visits: number }>
  longestDateNightStreakWeeks: number
  placesVisited: string[]
  firstMemory: { title: string; date: string } | null
  lastMemory: { title: string; date: string } | null
  quarters: Array<{ quarter: 1 | 2 | 3 | 4; total: number; highlight: string | null }>
}

/** Thrown when the year, the database handle or a stored row is unusable. */
export class StatementError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'StatementError'
  }
}

/**
 * The only thing {@link aggregateYear} needs from a CAP database service.
 *
 * Narrow on purpose: `cds.db`, a transaction, and a service deployed straight to
 * an in-memory SQLite all satisfy it, and nothing else about them is used.
 */
export interface StatementDb {
  run(query: unknown): Promise<unknown>
}

/** A statement generated by whichever provider was configured. */
export interface GeneratedStatement {
  markdown: string
  /** `LlmProvider.name` — `'template'` when no credentials are configured. */
  engine: string
}

/**
 * Token budget for a generated statement.
 *
 * CONTRACTS.md §7 defaults `maxTokens` to 8000, which is right for a short
 * completion and wrong for this one: on the default Anthropic model adaptive
 * thinking tokens are billed against `max_tokens`, so a model that thinks for a
 * few thousand tokens before writing three pages of prose gets truncated
 * mid-sentence. A statement is generated once a year, so the budget is set
 * generously rather than tuned.
 */
export const STATEMENT_MAX_TOKENS = 32_000

/** Two expenses more than this many days apart are two different trips (§8). */
const TRIP_GAP_DAYS = 3

/** The overview names three; five gives the prose something to choose from. */
const TOP_MERCHANTS = 5

const EXPENSES = 'twowaymatch.Expenses'
const MEMORIES = 'twowaymatch.Memories'
const PEOPLE = 'twowaymatch.People'
const EVENTS = 'twowaymatch.Events'
const EVENT_PARTICIPANTS = 'twowaymatch.EventParticipants'

const QUARTERS = [1, 2, 3, 4] as const

/** One confirmed expense, reduced to the fields the statement reads. */
interface ExpenseRow {
  /** `YYYY-MM-DD`, always present: the query window is on this column. */
  date: string
  amount: number
  currency: string | null
  category: string | null
  moment: MomentCode | null
  merchantRaw: string | null
  merchantNorm: string | null
  place: string | null
  /** `People.ID` of the payer, or null on an unattributed row. */
  paidBy: string | null
  /** `Events.ID`, or null for everyday spending. */
  event: string | null
}

/** One memory of the year. */
interface MemoryRow {
  date: string
  title: string | null
  place: string | null
  pinned: boolean
}

/** Somebody who can pay for something. Any number of them (§10). */
interface PersonRow {
  id: string
  name: string
}

/** A trip, a dinner, a party. */
interface EventRow {
  id: string
  name: string
}

/**
 * Aggregate one calendar year into {@link StatementFacts} (CONTRACTS.md §8).
 *
 * Only `status='confirmed'` expenses count: a draft is a photograph of a
 * receipt, not a thing that happened. Memories are included whether or not they
 * hang off an expense, because the romantic layer is allowed to outlive the
 * ledger.
 *
 * `db` is the CAP database service to read from. When it is omitted the ambient
 * `cds.db` of a running server is used — passing one explicitly is what lets a
 * test (or a script) point the same aggregation at a throwaway database.
 */
export async function aggregateYear(year: number, db?: unknown): Promise<StatementFacts> {
  if (!Number.isInteger(year) || year < 1000 || year > 9999) {
    throw new StatementError(`year must be a four-digit calendar year, got ${String(year)}`)
  }
  const handle = await resolveDb(db)
  const from = `${year}-01-01`
  const to = `${year}-12-31`

  const [expenseRows, memoryRows, personRows, eventRows, participantRows] = await Promise.all([
    runRows(handle, selectExpenses(from, to)),
    runRows(handle, selectMemories(from, to)),
    runRows(handle, selectPeople()),
    runRows(handle, selectEvents()),
    runRows(handle, selectEventParticipants()),
  ])

  return buildFacts(
    year,
    expenseRows.map(readExpense),
    memoryRows.map(readMemory),
    personRows.map(readPerson),
    eventRows.map(readEvent),
    participantRows.map(readParticipant),
  )
}

/**
 * Render the statement without a model, exactly as the `template` provider does.
 *
 * Delegates to `renderStatementFromFacts()` in `srv/lib/llm/template.ts` rather
 * than owning a second copy of the prose: the deterministic renderer is the
 * fallback at the end of CONTRACTS.md §7's selection order, so two renderers
 * would mean the credential-less path and the "LLM failed" path could drift
 * apart. This wrapper exists so callers that only want the markdown do not have
 * to construct an `LlmRequest` and pretend to be a model.
 */
export function renderTemplateStatement(f: StatementFacts): string {
  return renderStatementFromFacts(f)
}

/**
 * Generate the statement with the configured provider, falling back to the
 * deterministic renderer if it fails.
 *
 * The facts are embedded in the prompt as JSON, which is also how the `template`
 * provider recovers them when it is the one answering — so this single call site
 * behaves identically with and without credentials. `maxTokens` is set
 * explicitly; see {@link STATEMENT_MAX_TOKENS} for why the §7 default is not
 * good enough here.
 */
export async function generateStatement(
  facts: StatementFacts,
  provider: LlmProvider = getProvider(),
): Promise<GeneratedStatement> {
  try {
    const markdown = await provider.generate({
      system: STATEMENT_SYSTEM_PROMPT,
      prompt: buildStatementPrompt(facts),
      maxTokens: STATEMENT_MAX_TOKENS,
    })
    const trimmed = markdown.trim()
    if (trimmed.length === 0) throw new StatementError('the provider returned an empty statement')
    return { markdown: trimmed, engine: provider.name }
  } catch (error) {
    // A statement is a once-a-year keepsake: an outage must not cost the year,
    // so the failure is not re-thrown — the template output is a complete,
    // correct answer. It is logged, though: silently degrading would mean a
    // mistyped API key produces a perfectly good statement every year and
    // nobody ever finds out the model was never asked. Only the provider name
    // and the (already redacted) error message are logged — never the prompt,
    // which carries the whole year of the household's spending.
    console.warn(
      `[statement] ${provider.name} could not write FY${facts.year}, ` +
        `falling back to the template renderer: ${describeFailure(error)}`,
    )
    return { markdown: renderTemplateStatement(facts), engine: 'template' }
  }
}

/**
 * A thrown value reduced to one safe line.
 *
 * Never the stack: a `fetch` failure's stack can contain the endpoint URL, and
 * `LLM_BASE_URL` is allowed to carry credentials in its userinfo component.
 * Provider errors arrive here as `LlmError`, whose message has already been
 * through `redactSecrets()`.
 */
function describeFailure(error: unknown): string {
  if (error instanceof Error) return `${error.name}: ${error.message}`
  return 'unknown error'
}

/**
 * The persona, the shape of the document, and the two things a model must not
 * do with these figures.
 *
 * **No debt.** The facts contain per-person totals, and a model that has ever
 * seen a shared-expenses app will reach for "X owes Y" unprompted. It is wrong
 * here in the way that matters — this ledger records who paid, and nothing else
 * — so the prohibition is explicit rather than implied by the absence of a
 * balance field.
 *
 * **Swiss numbers.** The deterministic template renders `CHF 18'420.55`, and the
 * app's `formatMoney` does the same (FRONTEND-CONTRACT §5). A model left to its
 * own devices writes `CHF 18,420.55`, and the same statement then looks like two
 * different documents depending on whether an API key happened to be set.
 */
export const STATEMENT_SYSTEM_PROMPT = [
  'You are the finance function of a small household, writing its annual report.',
  'The joke is that the people who live there keep their life in an SAP-shaped ledger; the',
  'report is warm, dry, and entirely sincere underneath the corporate register. Never',
  'sarcastic about the people, only about the paperwork.',
  '',
  'Write GitHub-flavoured Markdown. Open with a level-1 title, then use exactly these',
  'level-2 headings, in this order: "Executive Summary", "Key Achievements",',
  '"Investment Overview", "Highlights by Quarter", "Outlook", "Closing note".',
  'Prose first; at most one small table. Use only the figures given — never invent an',
  'amount, a place, a merchant or an event — and give every amount its currency.',
  'Address people by the names in `people`. There may be two of them or ten: never assume',
  'a couple, never assume who lives with whom, and never use a name that is not in the facts.',
  '',
  'Nobody owes anybody. `totals.byPerson` records what each person PAID, which is a',
  'contribution and never a claim: do not write that anyone owes, is owed, should be paid',
  'back, is behind, or that anything needs settling up, squaring or evening out. There are',
  'no balances in this ledger. `events` and their participant counts are context for what a',
  'trip or a dinner cost in total — a per-person figure there is information, not a bill.',
  '',
  'Format money the Swiss way: currency code, space, apostrophe thousands separator, exactly',
  "two decimals — CHF 18'420.55. Never CHF 18,420.55, never CHF 18420.5, never a bare number.",
  'Percentages are whole numbers.',
].join('\n')

/** The user turn: a sentence of instruction and the facts as JSON. */
export function buildStatementPrompt(facts: StatementFacts): string {
  return [
    `Write the Statement of Us for FY${facts.year} from the audited figures below.`,
    '',
    '```json',
    JSON.stringify(facts, null, 2),
    '```',
    '',
    'Amounts are in the stated currency and already rounded. `counts.trips` groups trip',
    'expenses that ran within three days of each other, and `longestDateNightStreakWeeks`',
    'counts consecutive ISO weeks that contained a date night. `events` lists what each',
    'named occasion totalled and how many people were on it; `totals.byPerson` lists what',
    'each person paid for, which is the only thing this ledger tracks about money and people.',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// Aggregation
// ---------------------------------------------------------------------------

function buildFacts(
  year: number,
  expenses: ExpenseRow[],
  memories: MemoryRow[],
  people: PersonRow[],
  events: EventRow[],
  participants: Array<{ eventId: string; personId: string }>,
): StatementFacts {
  const nameById = new Map(people.map(person => [person.id, person.name]))
  const roster = rosterNames(people)

  const dateNightDates = expenses.filter(e => e.moment === 'date_night').map(e => e.date)
  const tripDates = expenses.filter(e => e.moment === 'trip').map(e => e.date)
  const titled = memories.filter(hasTitle)

  return {
    year,
    people: roster,
    currency: dominantCurrency(expenses),
    totals: {
      overall: sumMoney(expenses.map(e => e.amount)),
      byCategory: groupTotals(expenses, e => e.category, CATEGORY_CODES),
      byPerson: personTotals(expenses, nameById, roster),
      byMoment: groupTotals(expenses, e => e.moment, MOMENT_CODES),
    },
    counts: {
      expenses: expenses.length,
      // Evenings, not postings: dinner and the taxi home are one date night.
      // The sibling `trips` is a cluster count too, per §8.
      dateNights: new Set(dateNightDates).size,
      trips: countTrips(tripDates),
      gifts: expenses.filter(e => e.moment === 'gift').length,
    },
    events: eventFacts(expenses, events, participants),
    topMerchants: topMerchants(expenses),
    longestDateNightStreakWeeks: longestWeekStreak(dateNightDates),
    placesVisited: placesVisited(expenses, memories),
    firstMemory: bookend(titled, 'first'),
    lastMemory: bookend(titled, 'last'),
    quarters: QUARTERS.map(quarter => ({
      quarter,
      total: sumMoney(expenses.filter(e => quarterOf(e.date) === quarter).map(e => e.amount)),
      highlight: quarterHighlight(quarter, expenses, memories),
    })),
  }
}

/**
 * The names the statement may use, in the order the roster came back (by name).
 *
 * A person with no name is dropped rather than given a placeholder. There is no
 * placeholder to give: the household is any size, so there is no such thing as
 * "the fourth person's stand-in name", and a report that addresses `""` is worse
 * than one that addresses everyone it can name. Their spending still counts
 * toward `totals.overall`; it simply has no line. Two people who share a name
 * share a line, which is the truthful answer for a report keyed by what it
 * prints.
 */
function rosterNames(people: PersonRow[]): string[] {
  const names: string[] = []
  for (const person of people) {
    if (person.name.length > 0 && !names.includes(person.name)) names.push(person.name)
  }
  return names
}

/**
 * What each person paid, keyed by the name the report prints.
 *
 * Unlike {@link groupTotals}, a person with no spend is reported as `0` rather
 * than omitted: a category with nothing in it is a bucket nobody used, but a
 * person with nothing in it is a member of the household who had a quiet year,
 * and the renderer needs a figure for every name it is going to mention
 * (CONTRACTS.md §9 takes the same view of the period roster).
 *
 * A payer who is not in the roster — deleted, or never named — is left out
 * rather than filed under a UUID: an unattributed row would otherwise show up in
 * the report as a stranger who lives here.
 */
function personTotals(
  expenses: ExpenseRow[],
  nameById: Map<string, string>,
  roster: string[],
): Record<string, number> {
  const amounts = new Map<string, number[]>(roster.map(name => [name, []]))
  for (const row of expenses) {
    const name = row.paidBy === null ? undefined : nameById.get(row.paidBy)
    const bucket = name === undefined ? undefined : amounts.get(name)
    if (bucket !== undefined) bucket.push(row.amount)
  }

  const totals: Record<string, number> = {}
  for (const [name, values] of amounts) totals[name] = sumMoney(values)
  return totals
}

/**
 * What each event of the year cost, largest first.
 *
 * Derived from the postings rather than from the events' own dates, so a trip
 * that started on 30 December is reported against the year its bills landed in,
 * and an event nobody spent anything on is left out — "the dinner we planned and
 * never had" is not a line in an annual report. An expense whose event has since
 * been deleted keeps its money in `totals.overall` and loses only its label.
 */
function eventFacts(
  expenses: ExpenseRow[],
  events: EventRow[],
  participants: Array<{ eventId: string; personId: string }>,
): EventFacts[] {
  const amounts = new Map<string, number[]>()
  for (const row of expenses) {
    if (row.event === null) continue
    const bucket = amounts.get(row.event)
    if (bucket === undefined) amounts.set(row.event, [row.amount])
    else bucket.push(row.amount)
  }

  const headCount = new Map<string, number>()
  for (const link of participants) {
    headCount.set(link.eventId, (headCount.get(link.eventId) ?? 0) + 1)
  }

  return events
    .filter(event => amounts.has(event.id) && event.name.length > 0)
    .map(event => ({
      name: event.name,
      total: sumMoney(amounts.get(event.id) ?? []),
      participantCount: headCount.get(event.id) ?? 0,
    }))
    .sort((left, right) => right.total - left.total || compareText(left.name, right.name))
}

/**
 * Count trip clusters (CONTRACTS.md §8).
 *
 * Chained, not windowed: each expense is compared with the one before it, so a
 * fortnight of daily postings is one trip rather than five. A gap of exactly
 * three days keeps the trip alive; four days starts a new one. A single
 * isolated trip expense is still a trip.
 */
function countTrips(dates: string[]): number {
  let trips = 0
  let previous: string | null = null
  for (const date of [...dates].sort()) {
    if (previous === null || daysBetween(previous, date) > TRIP_GAP_DAYS) trips += 1
    previous = date
  }
  return trips
}

/**
 * Longest run of consecutive ISO weeks containing at least one date night (§8).
 *
 * Weeks are identified by `isoWeekKey()` and ordered by their Monday, which is
 * what keeps the year boundary honest: `2026-W53` is followed by `2027-W01`, and
 * comparing week *numbers* would see 53 → 1 as a break in the streak (or, worse,
 * would join 2026-W01 to 2025-W01). Two Mondays seven days apart are adjacent
 * weeks, whatever their labels say.
 */
function longestWeekStreak(dates: string[]): number {
  const mondayByWeek = new Map<string, string>()
  for (const date of dates) mondayByWeek.set(isoWeekKey(date), mondayOf(date))

  let longest = 0
  let run = 0
  let previous: string | null = null
  for (const monday of [...mondayByWeek.values()].sort()) {
    run = previous !== null && daysBetween(previous, monday) === 7 ? run + 1 : 1
    previous = monday
    if (run > longest) longest = run
  }
  return longest
}

/** The Monday of a date's ISO week; `dow` is Monday-0, so this is a subtraction. */
function mondayOf(date: string): string {
  return addDays(date, -parseWhenISO(date).dow)
}

/**
 * Merchants ranked by spend.
 *
 * Grouped by `merchantNorm` — the normalised form CONTRACTS.md §2.1 defines —
 * so that "MIGROS ZÜRICH HB" and "Migros Zurich HB" are one counterparty, but
 * displayed with the raw spelling that appears most often, because the statement
 * is read by humans and `migros zuerich hb` is not a name.
 */
function topMerchants(expenses: ExpenseRow[]): StatementFacts['topMerchants'] {
  interface Tally {
    /** Every raw spelling seen for this counterparty, and how often. */
    labels: Map<string, number>
    amounts: number[]
  }
  const tallies = new Map<string, Tally>()
  for (const row of expenses) {
    const label = row.merchantRaw ?? row.merchantNorm
    if (label === null) continue
    const key = row.merchantNorm ?? label.toLowerCase()
    const tally: Tally = tallies.get(key) ?? { labels: new Map(), amounts: [] }
    tally.labels.set(label, (tally.labels.get(label) ?? 0) + 1)
    tally.amounts.push(row.amount)
    tallies.set(key, tally)
  }

  return [...tallies.values()]
    .map(tally => ({
      merchant: mostCommon(tally.labels),
      total: sumMoney(tally.amounts),
      visits: tally.amounts.length,
    }))
    .sort(
      (left, right) =>
        right.total - left.total ||
        right.visits - left.visits ||
        compareText(left.merchant, right.merchant),
    )
    .slice(0, TOP_MERCHANTS)
}

/**
 * Every place that appears on an expense or a memory, most-visited first.
 *
 * Deduplicated case-insensitively but reported with the first spelling seen, and
 * ties are broken by that first appearance — `Array.prototype.sort` is stable, so
 * the date order the rows arrive in survives the ranking.
 */
function placesVisited(expenses: ExpenseRow[], memories: MemoryRow[]): string[] {
  const seen = new Map<string, { label: string; visits: number }>()
  for (const place of [...expenses, ...memories].map(row => row.place)) {
    if (place === null) continue
    const key = place.toLowerCase()
    const entry = seen.get(key)
    if (entry === undefined) seen.set(key, { label: place, visits: 1 })
    else entry.visits += 1
  }
  return [...seen.values()].sort((left, right) => right.visits - left.visits).map(e => e.label)
}

/**
 * The one thing worth remembering about a quarter.
 *
 * A written-up memory always wins, because a human chose to record it — pinned
 * first, then the earliest. Failing that the quarter is described by its largest
 * posting, which is a fact rather than an invention. A quarter with neither gets
 * `null`, and the renderer supplies its own line.
 */
function quarterHighlight(
  quarter: number,
  expenses: ExpenseRow[],
  memories: MemoryRow[],
): string | null {
  const written = memories.filter(hasTitle).filter(m => quarterOf(m.date) === quarter)
  if (written.length > 0) return (written.find(m => m.pinned) ?? written[0]).title

  const named = expenses.filter(hasMerchant).filter(e => quarterOf(e.date) === quarter)
  if (named.length === 0) return null
  const largest = named.reduce((top, row) => (row.amount > top.amount ? row : top), named[0])
  return `the quarter's largest posting was ${largest.merchantRaw}`
}

/** Memories arrive in date order, so the bookends are the ends of the list. */
function bookend(
  memories: Array<MemoryRow & { title: string }>,
  end: 'first' | 'last',
): { title: string; date: string } | null {
  const row = end === 'first' ? memories.at(0) : memories.at(-1)
  return row === undefined ? null : { title: row.title, date: row.date }
}

/**
 * Sum by group, emitting the well-known keys in contract order first.
 *
 * The key order of `byCategory` / `byMoment` is otherwise whatever order the
 * rows happened to arrive in, and these records are serialised into an LLM
 * prompt — a stable order makes the prompt (and therefore a cached response)
 * reproducible. Groups with no spend are omitted entirely rather than reported
 * as zero: "we spent nothing on Health" is not a fact the statement should
 * assert, and the renderer already reads an absent key that way. `byPerson` is
 * the deliberate exception; see {@link personTotals}.
 */
function groupTotals(
  expenses: ExpenseRow[],
  keyOf: (row: ExpenseRow) => string | null,
  order: readonly string[],
): Record<string, number> {
  const groups = new Map<string, number[]>()
  for (const row of expenses) {
    const key = keyOf(row)
    if (key === null) continue
    const bucket = groups.get(key)
    if (bucket === undefined) groups.set(key, [row.amount])
    else bucket.push(row.amount)
  }

  const keys = [
    ...order.filter(key => groups.has(key)),
    ...[...groups.keys()].filter(isUnknownIn(order)),
  ]
  const totals: Record<string, number> = {}
  for (const key of keys) totals[key] = sumMoney(groups.get(key) ?? [])
  return totals
}

/** Keys the contract does not know about still get reported — just afterwards. */
function isUnknownIn(order: readonly string[]): (key: string) => boolean {
  return key => !order.includes(key)
}

/** The currency most of the year was spent in; `CHF` when the year is empty. */
function dominantCurrency(expenses: ExpenseRow[]): string {
  const counts = new Map<string, number>()
  for (const row of expenses) {
    if (row.currency === null) continue
    counts.set(row.currency, (counts.get(row.currency) ?? 0) + 1)
  }
  return counts.size === 0 ? DEFAULT_CURRENCY : mostCommon(counts)
}

/** Quarter of a `YYYY-MM-DD` date. The month is validated at read time. */
function quarterOf(date: string): number {
  return Math.floor((Number(date.slice(5, 7)) - 1) / 3) + 1
}

/** Highest count wins; ties go to the first key inserted, which is the earliest. */
function mostCommon(counts: Map<string, number>): string {
  let best = ''
  let bestCount = -1
  for (const [value, count] of counts) {
    if (count > bestCount) {
      best = value
      bestCount = count
    }
  }
  return best
}

/** Locale-independent ordering, so the same data ranks the same on every machine. */
function compareText(left: string, right: string): number {
  if (left === right) return 0
  return left < right ? -1 : 1
}

function hasTitle(row: MemoryRow): row is MemoryRow & { title: string } {
  return row.title !== null
}

function hasMerchant(row: ExpenseRow): row is ExpenseRow & { merchantRaw: string } {
  return row.merchantRaw !== null
}

// ---------------------------------------------------------------------------
// Database access
// ---------------------------------------------------------------------------

/**
 * The handle to read from: the one passed in, else the running server's `cds.db`.
 *
 * `global.cds` is set by `@sap/cds` the moment it is loaded, so a CAP process
 * always has it and a bare Node process never does — which is exactly the
 * distinction this needs to make, without importing the module and requiring it
 * to be installed wherever this file is imported.
 */
async function resolveDb(handle: unknown): Promise<StatementDb> {
  if (handle !== undefined && handle !== null) {
    if (isDb(handle)) return handle
    throw new StatementError('the db handle passed to aggregateYear() has no run() method')
  }

  const cds = (globalThis as { cds?: unknown }).cds
  if (isRecord(cds)) {
    if (isDb(cds.db)) return cds.db
    if (isConnect(cds.connect)) {
      const connected: unknown = await cds.connect.to('db')
      if (isDb(connected)) return connected
    }
  }
  throw new StatementError(
    'no CAP database is connected — run aggregateYear() inside a CAP service or pass a db handle',
  )
}

/** Confirmed expenses of the year, oldest first (§8 needs the date order). */
function selectExpenses(from: string, to: string): unknown {
  return select(
    EXPENSES,
    [
      'date',
      'amount',
      'currency',
      'category_code',
      'moment',
      'merchantRaw',
      'merchantNorm',
      'place',
      'paidBy_ID',
      'event_ID',
    ],
    [{ ref: ['status'] }, '=', { val: 'confirmed' }, 'and', ...between('date', from, to)],
    ['date', 'ID'],
  )
}

/** Memories of the year, oldest first — `firstMemory` / `lastMemory` are its ends. */
function selectMemories(from: string, to: string): unknown {
  return select(
    MEMORIES,
    ['occurredOn', 'title', 'place', 'pinned'],
    between('occurredOn', from, to),
    ['occurredOn', 'ID'],
  )
}

/**
 * The roster, alphabetically.
 *
 * By name, not by seeding order or by `isDefault`: whoever was added first is
 * not the head of the household, and a list that puts the two seeded people
 * before everybody else would quietly rebuild the hard-coded pair that §10
 * deletes — the roster is a list of people, in no particular hierarchy.
 */
function selectPeople(): unknown {
  return select(PEOPLE, ['ID', 'name'], [], ['name', 'ID'])
}

/** Every event, whenever it happened; {@link eventFacts} keeps the ones with spend. */
function selectEvents(): unknown {
  return select(EVENTS, ['ID', 'name'], [], ['startsOn', 'ID'])
}

/** The link rows, which is all a head count needs. The key is the pair, so no ID. */
function selectEventParticipants(): unknown {
  return select(EVENT_PARTICIPANTS, ['event_ID', 'person_ID'], [], ['event_ID', 'person_ID'])
}

/** `column >= from and column <= to` in CQN. */
function between(column: string, from: string, to: string): unknown[] {
  return [{ ref: [column] }, '>=', { val: from }, 'and', { ref: [column] }, '<=', { val: to }]
}

/**
 * A CQN `SELECT`, ordered by every column in `orderBy` so ties are not left to
 * the database's discretion (the quarter highlight and the memory bookends both
 * depend on "the earliest one" being the same row every run). The last column is
 * normally the key, which is why the list is explicit: `EventParticipants` is
 * keyed by a pair and has no `ID` to fall back on.
 */
function select(entity: string, columns: string[], where: unknown[], orderBy: string[]): unknown {
  const query = {
    SELECT: {
      from: { ref: [entity] },
      columns: columns.map(ref => ({ ref: [ref] })),
      orderBy: orderBy.map(ref => ({ ref: [ref], sort: 'asc' })),
    },
  }
  return where.length === 0 ? query : { SELECT: { ...query.SELECT, where } }
}

async function runRows(db: StatementDb, query: unknown): Promise<Array<Record<string, unknown>>> {
  const result: unknown = await db.run(query)
  if (!Array.isArray(result)) {
    throw new StatementError('the database returned something other than a list of rows')
  }
  return result.filter(isRecord)
}

function readExpense(row: Record<string, unknown>): ExpenseRow {
  return {
    date: requireDate(row.date, 'expense'),
    amount: toAmount(row.amount ?? 0),
    currency: text(row.currency),
    category: text(row.category_code),
    moment: momentOf(row.moment),
    merchantRaw: text(row.merchantRaw),
    merchantNorm: text(row.merchantNorm),
    place: text(row.place),
    paidBy: text(row.paidBy_ID),
    event: text(row.event_ID),
  }
}

function readMemory(row: Record<string, unknown>): MemoryRow {
  return {
    date: requireDate(row.occurredOn, 'memory'),
    title: text(row.title),
    place: text(row.place),
    pinned: row.pinned === true || row.pinned === 1,
  }
}

function readPerson(row: Record<string, unknown>): PersonRow {
  const id = text(row.ID)
  if (id === null) throw new StatementError('a person row has no ID')
  return { id, name: text(row.name) ?? '' }
}

function readEvent(row: Record<string, unknown>): EventRow {
  const id = text(row.ID)
  if (id === null) throw new StatementError('an event row has no ID')
  return { id, name: text(row.name) ?? '' }
}

function readParticipant(row: Record<string, unknown>): { eventId: string; personId: string } {
  const eventId = text(row.event_ID)
  const personId = text(row.person_ID)
  if (eventId === null || personId === null) {
    throw new StatementError('an event participant row is missing one half of its key')
  }
  return { eventId, personId }
}

/**
 * Validates a stored date and normalises it to `YYYY-MM-DD`.
 *
 * The query window already excludes nulls, so a failure here means the column
 * holds something that is not a date, and the statement would silently file it
 * in the wrong quarter. Loud is better.
 */
function requireDate(value: unknown, what: string): string {
  const raw = text(value)
  if (raw === null) throw new StatementError(`a ${what} row has no date`)
  return parseWhenISO(raw).date
}

/**
 * The stored moment, if it is one the contract knows.
 *
 * Comparing against `MOMENT_CODES` rather than casting means the compiler checks
 * that `srv/lib/constants.ts` and the CDS `MomentCode` enum still agree: if
 * either list changes, this function stops type-checking.
 */
function momentOf(value: unknown): MomentCode | null {
  const code = text(value)
  if (code === null) return null
  for (const known of MOMENT_CODES) if (known === code) return known
  return null
}

/** Trimmed non-empty text, or null. Blank columns and `null` mean the same thing. */
function text(value: unknown): string | null {
  if (typeof value !== 'string') return null
  const trimmed = value.trim()
  return trimmed.length === 0 ? null : trimmed
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function isDb(value: unknown): value is StatementDb {
  return isRecord(value) && typeof value.run === 'function'
}

function isConnect(value: unknown): value is { to(name: string): Promise<unknown> } {
  return isRecord(value) && typeof value.to === 'function'
}
